### ISSUE TITLE
Search and Facet by Library and Campus

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#1]
In GitLab by @rkt6 on Feb 8, 2018, 11:06

See related for context: https://github.com/psu-libraries/psulib_blacklight/wiki/Library-Faceting-and-Locations-Management

Requires psu-libraries/psulib_traject#11

**Comment by banukutlu** [comment]
@ruthtillman can you review and update the requirements

**Comment by ruthtillman** [comment]
Possible display: do we want to do some kind of nesting for grouped libraries? specifically UP libraries at the top, then a subset? Ways that this could look include the LC Call numbers.

**Comment by ruthtillman** [comment]
@banukutlu updated the docs + proposed a meeting to look through the grouping.

**Comment by cdmo** [comment]
Just to park this somewhere, the following does an `OR` union set:

`{!terms f=access_facet}In the Library,Online`
