### ISSUE TITLE
Label Finding Aids separately from other Supplemental Links

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#1007]
Some of our supplemental links are to what are called "finding aids," detailed documents which allow a patron to learn more about and request archival materials that are more briefly described in the catalog. These are all already being indexed as `suppl_links_struct` but would benefit from a clearer name to let the person know it's not actually supplemental/related material, it's a place to get more information about the materials described by the record. This is important for highlighting Penn State's unique materials/archival collections.

## WDDLL

- [ ] Links to our finding aids have the label "Special Collections Materials" (this is my tbd header)
- [ ] Should list before any other Related Resources

## Finding Aid URLs

We used to have more ways of linking to finding aids, but all those should be part of our cataloging side cleanup, so the ticket was revised just to match our ARKs. Our base URLs should be the following:

```
http(s)://n2t.net/ark:/42409/fa8[rest of url]
```

So we can use:

```
*ark:/42409/fa8*
```

to be safer.

### Catkeys

These catkeys represent records with ARKs.

- 9182662
- 374137
- 4732299

**Comment by ruthtillman** [comment]
Logic looks good. One thing about desired outcome, though -- the goal is to change the box label from **Related Resoures** to **Special Collections Materials** vs. the link text.

Also question, this reminded me that we've had Penn State Digital Collections links (see https://github.com/psu-libraries/psulib_blacklight/search?q=psu_digital_collections_links ) and put the Lion Shield next to them. Could we see about putting the Lion Shield there too?

This is what Nick had done there: ![](https://user-images.githubusercontent.com/639920/110835713-26447980-826d-11eb-8acd-125d0d6718c2.png)

And the box label change is the same kind of thing.

**Comment by ajkiessl** [comment]
@ruthtillman Ah okay, I can do that.  So, we want the linking to still say 'View Finding Aid', but the header in the box to say 'Special Collections Materials'.  I can also add the Lion Shield.  Do you have an example of one with multiple related resources?  The logic in there may need to be reworked.  Would it be possible for there to be multiple 856's?  And would we expect them all to link to Special Collections?

**Comment by ruthtillman** [comment]
* So, we want the link to still say 'View Finding Aid', but the header in the box to say 'Special Collections Materials'.
  **yes**
 
* Do you have an example record with multiple related resources? The logic for ordering may need to be reworked. Would it be possible for there to be multiple 856's? And would we expect them all to link to Special Collections?
   initial research indicates that we don't seem to have these. It would be unlikely they'd follow the same ARK pattern but we might have another URL linking to an external resource or to a digital collections item. I've mocked up and sent you one with an external related resources link in Teams (and it's on Stage). If it was digital collections, it would probably be an 856 41 not an 856 42, so it wouldn't be "related."
