### ISSUE TITLE
Sort results by "newest-to-oldest" using record number 

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#1025]
We've had periodic requests to order search results by newest-to-oldest purchase date (because sometimes people buy new things that were published a while back, e.g. new copies of Dune). While this wouldn't really apply well to e-resources since we're constantly loading/reloading them, it might actually be beneficial for physical materials.

There isn't a great way to do this with MARC data but we could fudge it by ordering results by record number in descending order. e.g. 29835, 3924, 395, 23.

Is this something Solr would do at all well? It's more of a nice-to-have than a priority, but recording it as a frequent request.

**Comment by ruthtillman** [comment]
Tried testing on QA but got the "don't call Ruth" error message.

**Comment by ruthtillman** [comment]
maybe it requires a reindex that hasn't run?

**Comment by Smullz622** [comment]
Yes, it needs a reindex because the Solr schema was changed. I'm not sure how to do that on QA. @whereismyjetpack is that something you would be able to help with?

**Comment by Smullz622** [comment]
@ruthtillman It should be good now. Please let me know if you run into any other issues with it.

**Comment by ruthtillman** [comment]
Tested and working great! Hooray!
