### ISSUE TITLE
Webhooks for Teams in GitHub

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#103]
In GitLab by @rkt6 on Sep 18, 2018, 10:27

**Comment by etreece** [comment]
I haven't been looking in Teams either, but I'll wait for a consensus before closing this issue.

**Comment by banukutlu** [comment]
I do not look in Teams either but rather use email notifications for git updates. So I am fine with not setting this up.

@ruthtillman your opinion?

**Comment by mkutch** [comment]
Same as Banu

Maryam

On Oct 4, 2018, at 2:18 PM, Banu Hapeloglu Kutlu <notifications@github.com<mailto:notifications@github.com>> wrote:


I do not look in Teams either but rather use email notifications for git updates. So I am fine with not setting this up.

@ruthtillman<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fruthtillman&data=02%7C01%7Cmxk128%40psu.edu%7C86dc6e1a22ac4b12f84008d62a3ee1cb%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636742846907246738&sdata=eJUR5KwpvzmzHongd0EOmoob1RKCSoPhUkZxMCViZGc%3D&reserved=0> @mkutch<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmkutch&data=02%7C01%7Cmxk128%40psu.edu%7C86dc6e1a22ac4b12f84008d62a3ee1cb%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636742846907246738&sdata=HHrUToF7qZttXPPcauBc4z2bhAz%2BgGzSgPVmBTYMc1k%3D&reserved=0> your opinion?

**Comment by tdouty** [comment]
Sounds good to me.
________________________________

**Comment by banukutlu** [comment]
So let's not set this up then. Closing this.
