### ISSUE TITLE
Please add Alert on the catalog and my account

### ISSUE THREAD

**Issue by binkylush** [psu-libraries/psulib_blacklight#1036]
Text for alert - 

"Routine maintenance of the library catalog system is scheduled for 8/4/22 6-7 am."

The alert can link to the following page for more detail:

https://libraries.psu.edu/alerts/routine-maintenance-library-catalog-system-scheduled-8422-6-7-am

(The alert should be removed on Thursday am, 84.22.)

Thanks!

**Comment by banukutlu** [comment]
updated
