### ISSUE TITLE
Creators and contributors updates

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#104]
In GitLab by @bzk60 on Sep 20, 2018, 09:46

Updates to the index have changed the names and breakdowns of fields for people in authorial/creator/contributor roles. The ticket's name reflects the fact that we may need to rename to reflect more generic roles. They're traditionally called authors, however the 7xx fields may also include things like editors. So we should consider how we name it once we see it.

https://git.psu.edu/i-tech/psulib_traject/issues/36

Fields have been broken down from author_display and author_vern_display to fuller fields. The current fields are used in both search results and single result views.

List of current author display fields:
- author_person_display
- author_person_vern_display
- author_corp_display
- author_corp_vern_display
- author_meeting_display
- author_meeting_vern_display
- addl_author_display
- addl_author_vern_display

## search results display

let's remove it entirely from search results for now.

## single result view

Instead of:

https://git.psu.edu/i-tech/psulib_blacklight/blob/master/app/controllers/catalog_controller.rb#L114

Fields:

| Label | field |
| --- | --- |
| Author | author_person_display |
| Author | author_person_vern_display |
| Corporate Author | author_corp_display |
| Corporate Author | author_corp_vern_display |
| Conference Author | author_meeting_display |
| Conference Author | author_meeting_vern_display |

## facet
all_authors_facet

still seems good.

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 20, 2018, 09:48

created branch [`104-creators-and-contributors-updates`](https://git.psu.edu/i-tech/psulib_blacklight/compare/master...104-creators-and-contributors-updates)

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 20, 2018, 10:11

added ~938 label

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 20, 2018, 10:23

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 20, 2018, 10:33

@rkt6 Which author display fields should be in `search results display` and/or `single result view`? Starting to build up the documentation in #86 will be helpful at this point to be able to see the bigger picture for our index and also devs can refer to.

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 20, 2018, 11:03

mentioned in merge request psulib_traject!2

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 20, 2018, 14:15

@bzk60 thoughts:

# Search results view

Let's remove authors entirely _for now_. We'll be indexing the title for display including the title author field.

# Single results view

Instead of:

https://git.psu.edu/i-tech/psulib_blacklight/blob/master/app/controllers/catalog_controller.rb#L114

Fields:

| Label | field |
| --- | --- |
| Author | author_person_display |
| Author | author_person_vern_display |
| Corporate Author | author_corp_display |
| Corporate Author | author_corp_vern_display |
| Conference Author | author_meeting_display |
| Conference Author | author_meeting_vern_display |

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 21, 2018, 13:01

assigned to @cdm32 and unassigned @bzk60

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 21, 2018, 13:15

removed ~938 label

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 21, 2018, 14:41

Why do we call this "creators and contributors" when the actual changes are called "authors"?

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 21, 2018, 14:52

> Starting to build up the documentation in #86 

To me, #86 is more about bigger picture in terms of content types and workflows. E.g, we have books we get from X and they go through this process and end up with this metadata and we'd like to do treat them X way in Traject/Blacklight.

So, to me, this issue of fields to display (or just index) and in which context is perhaps a separate issue.

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 21, 2018, 15:00

Because one of the many ways we could have handled this was by describing as creators/contributors. At a higher level, that's still where we are and we may edit/change this based on feedback as we go forward.

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 21, 2018, 15:02

What are the other many ways we could handle this? Is there some exchange or documentation on that?

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 21, 2018, 15:08

It's mostly about display field label choices.

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 21, 2018, 15:36

So what are the decisions on field label choices that have been made? What are the choices/decisions that remain? Are the decisions that have been made somewhere in other issues or something? 

I mean I see that you provided three examples of the machine names of fields (Temple, Stanford and Princeton). When I look at the committed code though it doesn't really look like any of the three examples.

I still have to dig into the code, I'm trying to understand the framing of it though.

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 21, 2018, 15:51

I've got field names above with labels based off our current system. It should be a small change to update, but I want to see more how it looks/functions. This is a trickier area than most.

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 21, 2018, 15:57

>  based off our current system.

Current system meaning what Sirsi puts in The CAT, right?

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 21, 2018, 15:58

yep. I reviewed a number of sites and found they do it several different ways. So I decided to make the call that in order to move forward I don't try to make a final call at this point.

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 21, 2018, 16:04

Cool. So I recognize it would be more work for you, but it would have been kinda nice to see some record of that review or a discussion in a meeting, etc, so I know what we're talking about and what we're aiming for. And maybe this has happened, but I just haven't seen it/read it yet (if it has, let's link it up here). I assume here you're not talking strictly about the code you reviewed, but rather a different survey of other site's UI. Are we shooting to emulate one university's UI in particular, I wonder?

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 21, 2018, 16:06

Also, if this is just an experiment you'd like to see on the QA server, we can do that without merging for what it's worth. The deploy script lets us choose any branch. We can always send stuff to the little sandbox server too, though it would be on a much smaller version of the index. Just throwing that to the mix here

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 21, 2018, 16:07

Banu and Maryam and I had some discussion of this. I think it would be useful to sit down and have some discussion of how we want to do fields/display/labels and records layout. Particularly single page vs. search result.

At this point, the above is strictly about adding fields with labels following current catalog controller pattern.

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 21, 2018, 16:09

A sit down meeting to go through this would be helpful for me I would say, thanks! And @bzk60 if you know of some other issues or notes I should be reading for a primer, I'm totally game. Thanks.

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 21, 2018, 16:32

a meeting about the fields is a good idea. I say, Ruth, Charlie, Maryam and I, we can go over the display fields to wrap that doc up.

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 21, 2018, 14:52

> Starting to build up the documentation in #86 

To me, #86 is more about bigger picture in terms of content types and workflows. E.g, we have books we get from X and they go through this process and end up with this metadata and we'd like to do treat them X way in Traject/Blacklight.

So, to me, this issue of fields to display (or just index) and in which context is perhaps a separate issue.

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 21, 2018, 14:58

I'm at a loss a bit about what this issue is about. Can someone change the description? Like, what is this issue addressing, specifically? Sounds like we are talking about what we display to our users? I see the additional comment that addresses Single results view, so maybe that's all this issue is for then? It's hard for me to know what I'm expected to do here. So more accurately perhaps we should change the name of the issue and description to be just about that?

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 21, 2018, 15:02

I can update. Banu brought it in based on a *ticket in the traject repo* because that ticket affected some fundamental aspects of the Blacklight display. Therefore we:

- needed a ticket to ensure that these changes didn't get lost
- don't have quite the same context here as on an indexing project.

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 21, 2018, 15:44

> Let's remove authors entirely _for now_. We'll be indexing the title for display including the title author field.

we need a document we can refer to be able to review the merges and make required changes in solr schema, controllers etc. This might be documented in the issues but we need one document with the fields where all can see/edit/comment etc. @rkt6 starting with sth like this https://psu.app.box.com/notes/320774203905?

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 21, 2018, 15:51

Good idea! These will be ones related to search or to search and display?

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 21, 2018, 15:48

Would be good have what do we want to search by as well. So search and display, facet and sort as well.

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 21, 2018, 16:05

@cdm32 after reading the 86 again yes that is more for content and workflow, I agree display fields and I am also thinking facets and sort fields would be another issue.

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 21, 2018, 16:07

I think #86 is kind of a "what the heck is in the cat anyway" kind of super basic question followed by what do we do with it in blackcat?

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 21, 2018, 16:08

added #105. This document is to know basically what users will be search by, facet by, sort by and then how the results be displayed to them.

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 21, 2018, 16:09

I mean, yeah, they are related I guess. I don't know lol

**Comment by banukutlu** [comment]
In GitLab by @ bzk60 on Sep 21, 2018, 16:16

related but def. should be documented separately

**Comment by cdmo** [comment]
some headway

![Screenshot_2018-10-01 Expert systems, tools and applications - Blacklight.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a6d74562542000114643e0/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6417773e7955e30e6895e63aab0268181c1b1bf102444f00a3a6d568b6e762249a0d4bad8d340c2582644ef2fb9202af73e671d814d9efebd208d2f42f65a5d4d51a6d5a17129bfa0f64f5911fcb50f54ae44b51f213366bef7f3f2a129c166730792577f5a8800bdecf35e6a81a3d57c1e9e5ff151aa57ed9c30b756a515fb867.png)

**Comment by banukutlu** [comment]
Yes I agree that facet does not seem right - I would say let's remove that facet.

**Comment by cdmo** [comment]
Cool. One other note: I didn't merge author-y fields into title in the index
