### ISSUE TITLE
Maintenance alert for 8/18

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#1042]
`Service interruption: Realtime availability, "I Want It," and My Account will be briefly offline on 8/18/22 from 1-1:30pm`

Can link to: https://libraries.psu.edu/alerts/service-interruption-real-time-availability-my-account-i-want-it-brief-outage-81822-1-130-pm

should be removed on 8/18 sometime about/after 2pm?

**Comment by banukutlu** [comment]
alert added
