### ISSUE TITLE
Document BlackCat Fields

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#105]
In GitLab by @bzk60 on Sep 21, 2018, 16:07

https://psu.app.box.com/notes/320774203905

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 21, 2018, 17:40

@rkt6 I tried to have a first round of the doc - kinda like what we have currently in BL. feel free to change with what we should be have. would be good to meet to go over them. thanks!

**Comment by ruthtillman** [comment]
This looks good. I'll try to find a good time for a meeting to go over these.

**Comment by banukutlu** [comment]
@ruthtillman can you move this doc to wiki?

**Comment by ruthtillman** [comment]
https://github.com/psu-libraries/psulib_blacklight/wiki/Blacklight-Catalog-Fields
