### ISSUE TITLE
Limit search terms

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/psulib_blacklight#1053]
If a guest types a large search query, our solr instances will OOM, I have a message out to Radu asking about what solr config mitigations we can put in place, but perhaps we should also limit the number of terms a guest can enter into our search box? 

@ruthtillman  -- I recall you mentioning a limit another school was setting? I could be remembering wrong.

**Comment by ruthtillman** [comment]
@whereismyjetpack I would be ok with setting character limit at something like 256 or 512. I believe that several others have done that.

**Comment by ruthtillman** [comment]
👍 figured that -- is 256 or 512 better on the Solr end? Like does 512 feel safe, should we do 256, or pick another arbitrary number in the middle? I will put in a ticket in Bento.

**Comment by whereismyjetpack** [comment]
I _think_ It's more of a _term_ limit, and less of a _character_ limit. In the least the search that broke us was 492 words, 3133 characters. I am no solr expert, but there could be a 200 term search that breaks us, and another that does not due to stemming, and other solr magic. This limit would be meerly a guardrail to prevent a system halting action like the one above. I'm doing some research on what a reasonable limit would be.

**Comment by ruthtillman** [comment]
that makes sense -- if we're passing from Bento I don't know if we can cut terms so much as characters... but a fairly low number compared to that number. But maybe we try 256 and if someone complains we up it? And we see if it prevents the others from ever happening again?

**Comment by whereismyjetpack** [comment]
I have reason to believe that last nights solr outage was caused by someone pasting a long query into the bento box on the libraries site. can we get this added into this sprint? we can probably introduce a Setting for `Settings.search_length_limit` and default it to 512, We would need to impliment this in bento, and our searchbox. the controller can probably just grab the first `search_length_limit` characters or something like this

**Comment by whereismyjetpack** [comment]
FWIW google limits searches to 32 words.

**Comment by ruthtillman** [comment]
Let's go with these limits (total lengths including params):

- all_fields: 10
- title: 36
- author: 36
- subject: 15
- browse: 15
- fallback: 20
