### ISSUE TITLE
Review GoodJob to see if we can replace Redis

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#1056]
https://island94.org/2020/07/introducing-goodjob-1-0

This would need us to switch to postgres as well.

**Comment by whereismyjetpack** [comment]
For future reference: One motivating factor for using GoodJob was to perhaps have it run traject jobs. in order for this to work, we'd have to pull traject code into the blacklight codebase, and it wouldn't give us an interface for running adhoc jobs like argo workflows gets us.
