### ISSUE TITLE
The "don't call Ruth" error message

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#1059]
Rather than "Sorry, I don't understand your search," let's display an error message that says:

```
Sorry, our search index experienced a problem. Please try again in a moment. If this error persists, please [report the issue](https://libraries.psu.edu/website-feedback) to Libraries Strategic Technology.
```

This doesn't substitute for 404s or null search result pages, but should be used for the 5xx errors.

(url encoded as markdown here for ease of ticket writing.)

**Comment by banukutlu** [comment]
I think this can be handled by overriding this
https://github.com/projectblacklight/blacklight/blob/v7.30.0/config/locales/blacklight.en.yml#L146-L147
in our own locale which is https://github.com/psu-libraries/psulib_blacklight/blob/main/config/locales/blacklight.en.yml

Also to note: this error handling is going to be removed from BL, the change is on the main currently, not released yet. Here is the related PR `https://github.com/projectblacklight/blacklight/pull/2681/files` and issue `https://github.com/projectblacklight/blacklight/issues/2660`
