### ISSUE TITLE
Faceting Libraries - Explore OR vs. AND

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#106]
When faceting Libraries, the default behavior of the sidebar is "AND" vs. OR. So, for example, if you click Harrisburg and York, it will only show books which are in _both_ libraries. However, this is rarely a useful use case. People would generally only be looking for a book that's in either a single library or in several libraries (e.g. two close libraries, or the libraries on the UP campus).

What does this look like as a search?

What does this look like as useful display?

Connected to #1

Aha! Link: https://penn-state-university-libraries.aha.io/features/STPROJ-60

**Comment by cdmo** [comment]
@ruthtillman and I talked about this in Slack this morning and I think for now we've decided that [Blacklight's `single` option](https://github.com/projectblacklight/blacklight/wiki/Configuration---Facet-Fields#single-value-facets) will be sufficient for now.

Doing an `OR` union of sets would require modifying the Blacklight search function to replace term query parser with the terms query parser so you could output an `fq` like `fq={!terms f=access_facet}In the Library,Online`

Should we take this issue off of milestone MVP 1? I was thinking of moving it to the BlackCat 1.0 release as a kind of "lets revisit"

**Comment by banukutlu** [comment]
> @ruthtillman and I talked about this in Slack this morning and I think for now we've decided that [Blacklight's `single` option](https://github.com/projectblacklight/blacklight/wiki/Configuration---Facet-Fields#single-value-facets) will be sufficient for now.
> 
> Doing an `OR` union of sets would require modifying the Blacklight search function to replace term query parser with the terms query parser so you could output an `fq` like `fq={!terms f=access_facet}In the Library,Online`
> 
> Should we take this issue off of milestone MVP 1? I was thinking of moving it to the BlackCat 1.0 release as a kind of "lets revisit"

yes I agree with moving to BlackCat 1.0 milestone

**Comment by ruthtillman** [comment]
Closing this because I'm more interested in the add all online and I'm not sure if we really want to do this.
