### ISSUE TITLE
All Fields default search

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#107]
What is included in the index that is searched for All Fields default search?
![screenshot_2018-09-28 blacklight](https://user-images.githubusercontent.com/523381/46230754-8a8e4f80-c337-11e8-9a0f-c1d8bcc3c05e.png)

https://github.com/psu-libraries/psulib_blacklight/wiki/Blacklight-Catalog-Fields#search-by

**Comment by banukutlu** [comment]
@ruthtillman could you pls make sure if we have a task for each keywords search field that needs to be indexed so that we can close this issue?
