### ISSUE TITLE
Single item page fields

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#11]
https://github.com/psu-libraries/psulib_blacklight/wiki/Blacklight-Catalog-Fields#single-item-view-labels

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 7, 2018, 14:36

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 17, 2018, 15:52

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 17, 2018, 16:12

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 17, 2018, 16:13

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 20, 2018, 09:38

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 20, 2018, 09:46

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 20, 2018, 10:43

changed the description

**Comment by banukutlu** [comment]
@ruthtillman could you pls make sure if we have a task for each single item view field that needs to be mapped and displayed so that we can close this issue?

**Comment by ruthtillman** [comment]
I think we're good on this.
