### ISSUE TITLE
Email/SMS Body fields

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#110]
https://github.com/psu-libraries/psulib_blacklight/wiki/Blacklight-Catalog-Fields#emailsms-body

**Comment by ruthtillman** [comment]
Reviewed fields. All Email/SMS fields are either indexed or being refined and are represented in tickets. Use and order documented in the wiki. We can close this ticket.

**Comment by banukutlu** [comment]
after @cdmo pointed out, there is still work to do other than just the fields for this one.

**Comment by cdmo** [comment]
Oh all I was saying is that we need *some* issue for SMS/Email. It can be this one, or this one can be closed and it can be some other new issue. The work that needs to be done is actually implementing this thing is all.

**Comment by cdmo** [comment]
hi @ruthtillman, given our conversation in Teams a bit ago, I was wondering if we wanted to think again about SMS. Should we keep this functionality? Or because of the fact that since this functionality was originally developed, the vast majority of mobile phones became cameras and taking a picture of the computer screen is easier then having the record texted to you. I am on the fence myself.

I do think email should still be a feature for what it's worth.

**Comment by ruthtillman** [comment]
What's the difficulty in setting up? I think at least in the long run, I'd like to have it... though if it's not working well out-of-the-box we can leave for now.

**Comment by cdmo** [comment]
Haven't even looked at what's involved, I'd guess it's pretty simple. Just kinda had that doubt in my mind like "why even bother?" So I wanted to check with you. We'll throw it back in the backlog and get to it. Thanks!

**Comment by banukutlu** [comment]
@ruthtillman do we want to add author field to Email/SMS as well now that we added it to search results page?

**Comment by ruthtillman** [comment]
@banukutlu yes, let's add author.

**Comment by ruthtillman** [comment]
Is this something I can test live? I tried using it but it may not be hooked up yet?

**Comment by banukutlu** [comment]
> Is this something I can test live? I tried using it but it may not be hooked up yet?

@ruthtillman email should be working but sms not yet.

**Comment by ruthtillman** [comment]
Email worked nicely for me! Includes link to record. Future work might be call numbers except this could potentially be a MESS with all our numbers and locations.

**Comment by cdmo** [comment]
Author has been added, code deployed
