### ISSUE TITLE
http etda urls

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/psulib_blacklight#1169]
We presently pull "Access Online" links from solr, which pulls from the marc record. etda urls are cataloged as http://etda.libraries.... and they should be cataloged as https://etda.libraries...

This ticket serves as a method to track the feasability of re-cataloging these links as https://

alternatively we could, in the catalog, detect http links and rewrite them as https.

**Comment by ruthtillman** [comment]
Used Data Control and it was successful! :tada: thanks for reviewing it with me, Dann.
