### ISSUE TITLE
Check if we can automatically track when work is deployed

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#118]
Determine if we will use Deployed column? If we can automatically move issues to deployed probably yes.

https://help.waffle.io/tracking-deployed-work/automatically-track-when-work-is-deployed

**Comment by banukutlu** [comment]
Determine if we will use Deployed column? If we can automatically move issues to deployed probably yes.

https://help.waffle.io/tracking-deployed-work/automatically-track-when-work-is-deployed

**Comment by cdmo** [comment]
Gonna go ahead and close this... Waffle is gone...
