### ISSUE TITLE
Search results page fields

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#12]
https://github.com/psu-libraries/psulib_blacklight/wiki/Blacklight-Catalog-Fields#search-results-view-labels

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 20, 2018, 13:45

GetIt! Function. Don't display copy. Only display 856 if it has content/don't just display 856.

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 20, 2018, 13:47

assigned to @rkt6

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 20, 2018, 13:47

me: get screenshot

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jul 3, 2018, 13:14

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jul 3, 2018, 13:24

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jul 3, 2018, 13:25

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jul 3, 2018, 13:26

![CatSearchResultsFields](/uploads/4533354e998d2d6da5b88744817e8c0f/CatSearchResultsFields.png)

Screenshot of current results.

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jul 3, 2018, 13:31

Using the item date/year is a tricky proposition per some of our conversations about dates.

Example of how Cornell and Stanford support multiple year uncertainty: https://newcatalog.library.cornell.edu//?f%5Bformat%5D%5B%5D=Book&q=women%20strike%20for%20peace&search_field=all_fields && https://searchworks.stanford.edu/catalog?utf8=%E2%9C%93&search_field=search&q=women+strike+for+peace

Princeton doesn't do it, but includes the whole publication statement (which we can above).

Wisconsin and Brown (ugly) use what's probably a particular 264 subfield c (unsure which indicators)

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jul 3, 2018, 13:32

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 20, 2018, 09:59

changed the description

**Comment by ruthtillman** [comment]
Using the item date/year is a tricky proposition per some of our conversations about dates.

Example of how Cornell and Stanford support multiple year uncertainty: https://newcatalog.library.cornell.edu//?f%5Bformat%5D%5B%5D=Book&q=women%20strike%20for%20peace&search_field=all_fields && https://searchworks.stanford.edu/catalog?utf8=%E2%9C%93&search_field=search&q=women+strike+for+peace

Princeton doesn't do it, but includes the whole publication statement (which we can above).

Wisconsin and Brown (not preferred) use what's probably a particular 264 subfield c (unsure which indicators)

**Comment by ruthtillman** [comment]
Need to work through 856 still...

**Comment by banukutlu** [comment]
this has been broken down to smaller issues - closing.
