### ISSUE TITLE
Return a 404 in response to a RecordNotFound error

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#120]
Rescue Blacklight::Exceptions::RecordNotFound and redirect to correct 404 page

![screen shot 2018-10-05 at 4 59 19 pm](https://user-images.githubusercontent.com/6477867/46559997-1e27c900-c8c0-11e8-83ab-45138d88f764.png)

requires #161

**Comment by banukutlu** [comment]
```https://github.com/pulibrary/orangelight/pull/1057```

**Comment by cdmo** [comment]
are you just going to merge that commit in from orangelight?

**Comment by banukutlu** [comment]
did the same rescue from exception and redirect to 404. also https://github.com/psu-libraries/psulib_blacklight/commit/ecbb275c9f6f2f07cc72dd4b7bfcef2ade517dfa to explicity handle 404s and 500s

**Comment by cdmo** [comment]
Cool, thanks.
