### ISSUE TITLE
Explore: is it possible to select a whole page to bookmark?

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#1212]
This is a question we had, it's not high priority but it also makes sense when supporting lit review searches to let people save a bunch of promising results to bookmarks and then weed them out.

Is it feasible? Would it add too much complexity? Is it the kind of thing where we could check all and let someone uncheck before adding to bookmarks or would _that_ add too much complexity.

**Comment by Smullz622** [comment]
Update: This is feasible. For now, we're going to just do bookmark all without the additional step of checking/unchecking before adding. Having that step would add complexity; plus with the additional clicks, efficiency is about the same as the existing process.

Button placement: Plan for the time being is to put it under the sort by & per page buttons. Ideal would be in the same bar as those buttons, but they're just in Blacklight & we don't want to override more than necessary.

Button text: We'll want something more specific than 'Bookmark All' to indicate that it's only bookmarking what's on the page, not all search results ex. 'Bookmark Items on Page' or 'Bookmark Items X-X' with X being result number.

**Comment by ruthtillman** [comment]
I had trouble triggering this until I'd done one bookmark already to force the login, I'm guessing, then it worked perfectly. Is there a way to get it to make the login happen. @ajkiessl

**Comment by ajkiessl** [comment]
@ruthtillman Ah I hadn't considered this.  I'll take a look.
