### ISSUE TITLE
Production application deployment

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#122]

**Comment by cdmo** [comment]
Been chatting with @tdouty in Teams, here's where we're at as an update. Production is mostly deployed pending some issues with database features. Also, I had to install two extra yum packages to get mysql2 to install.

- [ ] mysql credentials are not working
- [ ] mariadb version is different on QA versus Prod

**Comment by cdmo** [comment]
This [phusion error](https://psu.app.box.com/notes/481599983871) seems to have cleared up.

**Comment by cdmo** [comment]
We had another issue late last week where the health check apparatus from the load balancer was hitting each server in the cluster twice per second.

**Comment by cdmo** [comment]
Logging is a bit out of control on the production cluster.

**Comment by cdmo** [comment]
@banukutlu we may want to consider lowering the error level of logging to `:info`

**Comment by cdmo** [comment]
Still seeing what looks like a pretty active health checking going on: [see logs](https://psu.app.box.com/notes/481745686777)

**Comment by cdmo** [comment]
Set the mariadb problem as a separate issue in our deploy repo. PR is in for first version of prod and qa app deploy script.

**Comment by banukutlu** [comment]
@cdmo I think we can close this issue, what do you think?

**Comment by cdmo** [comment]
Yep
