### ISSUE TITLE
Moving to Symphony SaaS

### ISSUE THREAD

**Issue by Smullz622** [psu-libraries/psulib_blacklight#1290]
We may have more on this moving forward, but for now, here is a list of things impacted by Symphony where we will want to test the success & error path:

- [ ] Real time availability displays accurately
- [ ] 'I Want It' appears on the correct records (e.g. appears on holdable items, not on non-holdable items)
- [ ] 'I Want It' directs to the correct place (Symphony vs ILL hold)

**Comment by binkylush** [comment]
[Symphony issue #636](https://github.com/psu-libraries/Symphony/issues/636)

**Comment by whereismyjetpack** [comment]
@Smullz622 this should be testable on our catalog solr 9 instance https://catalog-solr9.dev.k8s.libraries.psu.edu
