### ISSUE TITLE
Move integrity check config to webpacker.yml from environment configs with webpacker v4

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#141]
_Originally posted by @banukutlu in https://github.com/psu-libraries/psulib_blacklight/issues/136#issuecomment-430770429_

Also with v4 we will be able to remove the `yarn:install` override 45a8b78

**Comment by cdmo** [comment]
keep in mind, the task I wrote overwrites the *rails* yarn install, not the webpack yarn_install task. Rails > 5.1 has a built in yarn install via railties. <5.1 uses webpack:yarn_install -- so really we need to wait until rails updates (maybe that will be in lock step with v4 of webpacker?)

**Comment by banukutlu** [comment]
oh yes right we can remove when rails updates 👍

**Comment by ruthtillman** [comment]
Closed after 5/8/23 standup discussion
