### ISSUE TITLE
Upgrade to Ruby 2.5.3

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#142]
https://www.ruby-lang.org/en/news/2018/10/18/ruby-2-5-3-released/

**Comment by banukutlu** [comment]
after upgrading to 2.5.3 on local, hitting the below style warnings since `parser` gem (rubocop dependency) is not supporting 2.5.3 yet

```
warning: parser/current is loading parser/ruby25, which recognizes
warning: 2.5.1-compliant syntax, but you are running 2.5.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

there is an open issue about this: ```https://github.com/whitequark/parser/issues/530```

**Comment by cdmo** [comment]
So we'll keep an eye on that issue until moving to 2.5.3 then, right?

**Comment by banukutlu** [comment]
> So we'll keep an eye on that issue until moving to 2.5.3 then, right?

speaking of which https://github.com/whitequark/parser/releases/tag/v2.5.3.0 👍
