### ISSUE TITLE
Solr 8 Upgrade

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#144]

**Comment by cdmo** [comment]
Could change this to Solr 8.0? Or 8.1? Or 8.2? 8.2 is the stable release at the moment.

Wonder if maybe we should just close this. Or, alternatively, turn it into a "Solr upgrade strategy" documentation issue. Come to think of it we could have similar docs for other major dependencies like Ruby and Rails

**Comment by banukutlu** [comment]
just to note: Solr version 8.9.0 breaking for call number browse shelf keys:

```
ShelfListPresenter.new.list
    
`KeyError (key not found: ["A..0001107.0760--0508020704", 1])`
```
It should just be `A..0001107.0760--0508020704` but instead it's the tuple.

**Comment by whereismyjetpack** [comment]
current version of solr is 8.11.1 we should target this, we're currently doing testing on catalog-solr8.dev.k8s.libraries.psu.edu
