### ISSUE TITLE
Setup rspec-guard

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#146]
> I started using this: https://collectiveidea.com/blog/archives/2017/02/09/guard-is-your-friend watched files for changes and runs test automatically.

> _Originally posted by @cdmo in https://github.com/psu-libraries/psulib_blacklight/issues/69#issuecomment-431819053_

Also integrate guard with our Procfile.dev to run both rspec and niftany.

**Comment by cdmo** [comment]
on hold for now, `guard-rspec` doesn't work with rails 2.5 yet, see https://github.com/guard/guard-rspec/pull/403

**Comment by cdmo** [comment]
Removing milestone. Just check manually.

**Comment by cdmo** [comment]
I'm pretty satisfied with our current state of rspec test execution locally.
