### ISSUE TITLE
Email bookmark => Network Error

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#162]
When I click on an item to bookmark it, then I click to my bookmarks, then I click on "Email" and then I fill out the form to email and after I submit it, I get this error.

![screenshot 2018-10-30 13 58 53](https://user-images.githubusercontent.com/523381/47739726-6a122780-dc4c-11e8-8996-54e5f66c5471.png)

**Comment by banukutlu** [comment]
closing since this is resolved with #110
