### ISSUE TITLE
Update schema to be more inline with BL 7's default solr schema

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#175]
https://github.com/projectblacklight/blacklight/blob/master/lib/generators/blacklight/templates/solr/conf/schema.xml

- [x] text not stemmed
- [ ] convert to snake case
- [x] facet fields conversion/examination

**Comment by banukutlu** [comment]
https://psu.app.box.com/file/347208862735

**Comment by cdmo** [comment]
https://psu.app.box.com/notes/347313071460 narrative

**Comment by cdmo** [comment]
@banukutlu and I just talked about this over zoom, but we're wondering why it is necessary to have a `title_t` and a `title_display`. `title_t` is indexed AND stored. We can easily just display it and not have the overhead of another title field just for display. From what we can tell the only difference in what is brought into the solr core by traject is that punctuation is trimmed. So, the only guess is that trailing/leading punctuation is sometimes desirable for search? Possible, maybe for some foreign language or math notation? 

We'll investigate more in the future, but for now we'll keep an indexed and display-only version as a general strategy.

**Comment by banukutlu** [comment]
> https://psu.app.box.com/notes/347313071460 narrative about how title_t is extracted and indexed

this is awesome, thanks @cdmo
