### ISSUE TITLE
MVP1 Acceptance Tests

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#176]
this is for plain-english tests for MVP1 work

https://psu.app.box.com/notes/346675757749

rooting from #90

**Comment by banukutlu** [comment]
@ruthtillman are you still working on this or is it finished?

**Comment by ruthtillman** [comment]
@banukutlu I've got most of the search done but am still working a bit on it.

**Comment by ruthtillman** [comment]
First draft of these is done. We may add more as we go.
