### ISSUE TITLE
Title Fields updates

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#180]
https://github.com/psu-libraries/psulib_blacklight/wiki/Title-Fields-Indexing-and-Display

Coordinated updates for https://github.com/psu-libraries/psulib_traject/issues/14

* [x] solrconfig and schema updates
* [x] catalog_controller and solr_document updates 
* [x] Title display: 
   Vernacular title as linked title, Latin character title below
   If no vernacular Latin character title as linked title, and no title below
* [x]  Uniform, Additional and Related Titles display:
    Use line break as separator for and combine with vern versions

**Comment by ruthtillman** [comment]
Looks good!
