### ISSUE TITLE
Testing non-Latin script search

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#19]
In GitLab by @rkt6 on Mar 9, 2018, 08:25

When the Blacklight test instance is up and running, Ruth will bring together catalogers--Lily Huang (Chinese, Japanese, Korean), Susan Lane (Arabic, has interest in testing French re: some Sirsi issues), Katherine Strenko (Cyrillic)--to test non-Latin script search. Since we catalog using various non-Latin scripts, we need to ensure they're working in the catalog. We'll want to test others eventually, but Chinese, Korean, and Arabic represent large segments of our international student population as well as our collections.

**Comment by banukutlu** [comment]
@ruthtillman can you add an update to this ticket if you have any?

**Comment by ruthtillman** [comment]
Basic tests are pretty good so far. About to review Arabic. Then will close.
