### ISSUE TITLE
Extract for fixtures

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#194]
Need an extract of the below catkeys for our fixtures:

```id:6056346 OR id:2431513 OR id:1350394 OR id:12957804 OR id:1839879 OR id:1739750 OR id:2101414 OR id:15000267 OR id:1742385 OR id:1742314 OR id:12761636 OR id:1719185 OR id:14651607 OR id:16621095 OR id:1836205 OR id:16621187 OR id:12744851 OR id:15196486 OR id:12761233 OR id:22077781 OR id:11338033 OR id:22092979 OR id:21841437 OR id:22090542 OR id:22076459 OR id:21837282 OR id:21841438 OR id:21841435 OR id:2045016 OR id:21837545 OR id:5334461 OR id:286971 OR id:6434209 OR id:1954857 OR id:316074 OR id:361299 OR id:1618709 OR id:458856 OR id:4508585 OR id:3696293 OR id:15200946 OR id:21835545 OR id:13217672 OR id:13217692 OR id:3696252 OR id:3199219 OR id:14991763 OR id:3201012 OR id:3199220 OR id:21322961 OR id:14993654 OR id:22082958 OR id:22083276 OR id:21588551 OR id:3626147 OR id:3559984 OR id:21833256 OR id:22087836 OR id:13597912 OR id:22083281 OR id:22081919 OR id:22083306 OR id:20049333 OR id:17280642 OR id:5112336 OR id:3626135 OR id:2293245 OR id:21276123 OR id:11954839 OR id:19142604 OR id:10016724 OR id:22091400 OR id:11954990 OR id:10728954 OR id:20044789 OR id:19525926 OR id:22090269 OR id:18647510 OR id:19446664 OR id:22088949 OR id:472159 OR id:71224 OR id:470399 OR id:71529 OR id:834640 OR id:1793712 OR id:21601671 OR id:2080485 OR id:2080339 OR id:2069311 OR id:2010881 OR id:2003672 OR id:2788022 OR id:593070 OR id:14423715 OR id:15422566 OR id:17531126 OR id:22077448 OR id:114189 OR id:103934```

**Comment by banukutlu** [comment]
Need an extract of the below catkeys for our fixtures:

```id:6056346 OR id:2431513 OR id:1350394 OR id:12957804 OR id:1839879 OR id:1739750 OR id:2101414 OR id:15000267 OR id:1742385 OR id:1742314 OR id:12761636 OR id:1719185 OR id:14651607 OR id:16621095 OR id:1836205 OR id:16621187 OR id:12744851 OR id:15196486 OR id:12761233 OR id:22077781 OR id:11338033 OR id:22092979 OR id:21841437 OR id:22090542 OR id:22076459 OR id:21837282 OR id:21841438 OR id:21841435 OR id:2045016 OR id:21837545 OR id:5334461 OR id:286971 OR id:6434209 OR id:1954857 OR id:316074 OR id:361299 OR id:1618709 OR id:458856 OR id:4508585 OR id:3696293 OR id:15200946 OR id:21835545 OR id:13217672 OR id:13217692 OR id:3696252 OR id:3199219 OR id:14991763 OR id:3201012 OR id:3199220 OR id:21322961 OR id:14993654 OR id:22082958 OR id:22083276 OR id:21588551 OR id:3626147 OR id:3559984 OR id:21833256 OR id:22087836 OR id:13597912 OR id:22083281 OR id:22081919 OR id:22083306 OR id:20049333 OR id:17280642 OR id:5112336 OR id:3626135 OR id:2293245 OR id:21276123 OR id:11954839 OR id:19142604 OR id:10016724 OR id:22091400 OR id:11954990 OR id:10728954 OR id:20044789 OR id:19525926 OR id:22090269 OR id:18647510 OR id:19446664 OR id:22088949 OR id:472159 OR id:71224 OR id:470399 OR id:71529 OR id:834640 OR id:1793712 OR id:21601671 OR id:2080485 OR id:2080339 OR id:2069311 OR id:2010881 OR id:2003672 OR id:2788022 OR id:593070 OR id:14423715 OR id:15422566 OR id:17531126 OR id:22077448 OR id:114189 OR id:103934```

**Comment by mkutch** [comment]
@banukutlu where do u want me to put it for you

**Comment by banukutlu** [comment]
@mkutch thanks!

**Comment by banukutlu** [comment]
@mkutch could you pls review these fixtures file and see if there are any vendor records? We would like to track the file so if there are any we should take them out.

**Comment by banukutlu** [comment]
more catkeys to extract here https://psu.app.box.com/notes/346675757749
