### ISSUE TITLE
Post-MVP integration of image viewer?

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#20]
In GitLab by @rkt6 on Mar 15, 2018, 16:47

Maps library loves what Princeton did with the image viewer here: https://catalog.princeton.edu/catalog/5274591#view

This is definitely a nice-to-have, so just logging it so we don't forget. Not critical though.

**Comment by ruthtillman** [comment]
We're doing it! But this isn't the ticket for it, so closing it.
