### ISSUE TITLE
Index and display note fields

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#202]
https://github.com/psu-libraries/psulib_blacklight/wiki/Note-Fields-Index-and-Display

Requires https://github.com/psu-libraries/psulib_traject/pull/15

**Comment by banukutlu** [comment]
@ruthtillman the order of notes fields here:https://github.com/psu-libraries/psulib_blacklight/wiki/Blacklight-Catalog-Fields and https://github.com/psu-libraries/psulib_blacklight/wiki/Note-Fields-Index-and-Display are a bit different. Which order is the we should use?

**Comment by ruthtillman** [comment]
For ordering fields generally, let's stick with Blacklight-Catalog-Fields.

**Comment by cdmo** [comment]
@ruthtillman [Note-Fields-Index-and-Display](https://github.com/psu-libraries/psulib_blacklight/wiki/Note-Fields-Index-and-Display) shows "Location of Originals" and [Blacklight-Catalog-Fields](https://github.com/psu-libraries/psulib_blacklight/wiki/Blacklight-Catalog-Fields) shows "Location of Original"

**Comment by cdmo** [comment]
in the same vain of questions, should it be "Associated" or "Associated Materials"?

**Comment by cdmo** [comment]
Administrative Note, or Administrative History?

**Comment by cdmo** [comment]
Is "Reviewed/Cited In" the same as "References"?
Is "Table of Contents" the same as "Contents"?
Is "Summary" the same as "Abstract"?

And these don't appear to be in the Blacklight-Catalog-Fields page at all:

"Scale Note for Graphic Material"
"Indexed By"
"Selectively Indexed By"
"References"
"Summary" (unless this is "Abstract")
"Reading Grade"
"Interest Age"
"Interest Grade"
"Related Materials"
"Language Note"  

Finally, @banukutlu related, these are in our system, but aren't in the ordering page. What should we do with them?

"Catkey"
"Call number"
"URL"
"More Information"

**Comment by banukutlu** [comment]
@cdmo we will remove Catkey (I think we should just remove it now - it is already in the url if needed for testing purposes). Call number should be removed as well. 
@ruthtillman what about URL and More information?

**Comment by ruthtillman** [comment]
@banukutlu  ++ on removing catkey (we'll put it... somewhere on the page but not in the main area) I'll get on URL when I get back to workplace.

@cdmo: I think I've properly standardized these across the main fields + the note wiki index... and then ensured they were in the single record field list.

- Associated Materials
- Administrative History
- Location of Originals

and updated these:

Is "Reviewed/Cited In" the same as "References"? - yes
Is "Table of Contents" the same as "Contents"? - yes
Is "Summary" the same as "Abstract"? - yes
