### ISSUE TITLE
Index and display publication fields

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#204]
https://github.com/psu-libraries/psulib_blacklight/wiki/Publication-Info-Fields-Index-and-Display

Requires  psu-libraries/psulib_traject#18
Requires psu-libraries/psulib_traject#31

**Comment by banukutlu** [comment]
@ruthtillman, we have a `Publication Year` facet but are we gonna keep the `Publish Date` facet?
![Screen Shot 2019-02-01 at 11.45.03 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bae8d163be62e0012255ac7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216454f26b7191a379ee0c2f54415f4dbc30254d58eeb9cb74fce36f34985619e8833c0a7c923e19afb98719bb57ba2083468cbfeadf44c8fa2137a5dad11b61435c52dcbd4f3fb29842c259f34fe84d56ad163064e173306e0a.png)

**Comment by ruthtillman** [comment]
No, we won't.

**Comment by ruthtillman** [comment]
While it technically works very well, the number of years makes it unwieldy as currently laid out. Can we implement the range boxes similar to what Stanford and Princeton have. IDEALLY without the slider.

If we have to do the slider, let's start date at 1800

**Comment by banukutlu** [comment]
> While it technically works very well, the number of years makes it unwieldy as currently laid out. Can we implement the range boxes similar to what Stanford and Princeton have. IDEALLY without the slider.
> 
> If we have to do the slider, let's start date at 1800

@ruthtillman I  added #234 for implementing the range on pub year, so I guess we can close this issue?
