### ISSUE TITLE
Index and display of material characteristics

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#208]
Requires https://github.com/psu-libraries/psulib_traject/issues/20

**Comment by ruthtillman** [comment]
@cdmo @banukutlu this looks good! I'd be happy to view it on QA or screenshare!

**Comment by cdmo** [comment]
coming soon, subjects will be merged in shortly and then a full extract on QA again with the latest

**Comment by banukutlu** [comment]
Follow up issue will be handled with #208
