### ISSUE TITLE
blacklight gem to 7.0.1 from 7.0rc2

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#210]
https://github.com/projectblacklight/blacklight/releases/tag/v7.0.0

**Comment by banukutlu** [comment]
https://github.com/projectblacklight/blacklight/releases/tag/v7.0.0

**Comment by cdmo** [comment]
I am doing this in my branch for advanced search, fyi. It was a dependency there anyway.

**Comment by cdmo** [comment]
tied to #46

**Comment by banukutlu** [comment]
> I am doing this in my branch for advanced search, fyi. It was a dependency there anyway.

great!
