### ISSUE TITLE
webpack-dev-server vulnerability

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#212]
To address this [vulnerability](https://github.com/psu-libraries/psulib_blacklight/network/alert/package.json/webpack-dev-server/open), it is recommended to upgrade webpack-dev-server to at least version 3.1.11. As mentioned here: `https://github.com/rails/webpacker/issues/1873`, the suggested fix can only be done by upgrading to the latest (4.0.x) version of Webpacker (which is still in rc) because `webpack-dev-server` depends on `webpack > 4.0`. 

Upgrades done in branch [webpack-dev-server-update](https://github.com/psu-libraries/psulib_blacklight/tree/webpack-dev-server-update) but since Webpacker does not have a stable 4.0.x release, we hit further issues.  So putting this on-hold until a stable Webpacker 4.0.x release.

**Comment by banukutlu** [comment]
https://github.com/rails/webpacker/blob/master/docs/v4-upgrade.md

**Comment by cdmo** [comment]
I don't see any commits related to this issue, but I also don't see the alert for this specific issue anymore either. Do you know what is going on with this?

**Comment by banukutlu** [comment]
> I don't see any commits related to this issue, but I also don't see the alert for this specific issue anymore either. Do you know what is going on with this?

I haven't push my local changes but also that branch needs to be rebased - very far behind :/ 
I think we marked this as like do not show this alert 🤔

**Comment by banukutlu** [comment]
so yeah we should still fix this and to fix it we need to upgrade - I had some prior work done for it but there was still to do re upgrade

**Comment by cdmo** [comment]
but mitigated by the fact that this is dev only. I was just surprised that it seemed like it was gone from our repo's alerts. Must be that we dismissed it entirely. which is fine.

**Comment by banukutlu** [comment]
https://github.com/rails/webpacker/blob/master/docs/v4-upgrade.md

**Comment by banukutlu** [comment]
here is the dismissed alert: https://github.com/psu-libraries/psulib_blacklight/network/alert/package.json/webpack-dev-server/closed
