### ISSUE TITLE
Refactor the subjectify method

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#216]
refactor the subjectify method to outdent it a bit and also the way the separator is being handled in the erb.

**Comment by cdmo** [comment]
I changed the return value to be Rails formatted markup. Did not touch the guts of the method (could still use some outdenting IMO)

**Comment by cdmo** [comment]
@banukutlu do you want to throw this back in the backlog or close it?

**Comment by banukutlu** [comment]
@cdmo maybe backlog but probably with milestone changed to sth later than pre-release. But let's leave it in pre-release for now and see, we can change later.
