### ISSUE TITLE
Browse by Call Number / Nearby on Shelf

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#22]
> If I'm interested in this book, I want a way to find more books which are near it/like it!

# To-Do
- [x] #793 
- [x] #794
- [x] #800 
- [x] #864
- [x] #960 
- [x] #961

**Comment by ruthtillman** [comment]
Wiki information about browse display: https://github.com/psu-libraries/psulib_blacklight/wiki/Browse-Items-by-Library-of-Congress-Call-Number

and nearby on shelf: https://github.com/psu-libraries/psulib_blacklight/wiki/Nearby-on-Shelf

**Comment by ruthtillman** [comment]
Updated https://github.com/psu-libraries/psulib_blacklight/wiki/Browse-Items-by-Library-of-Congress-Call-Number with info from talking to Stanford.

**Comment by ruthtillman** [comment]
Re: the Nearby on Shelf -- once we've got the ability to do browse search, we can determine the most user-friend/aesthetically pleasing way to display nearby on shelf.
