### ISSUE TITLE
Index and display formats

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#220]
https://github.com/psu-libraries/psulib_blacklight/wiki/Formats

These will display as a facet in the sidebar and be used to display some info about the record, e.g. map to an item type.

**Comment by banukutlu** [comment]
@ruthtillman do we want a label on search results for format?

**Comment by ruthtillman** [comment]
In the long run, I'd like to do an icon or such. In the short run, a label "Format" -- sure.

**Comment by banukutlu** [comment]
@ruthtillman I added fontawesome so won't be displaying a label on search results. What about single item view? I guess we will have the label there - is it gonna be `Format`? Also are we gonna display an icon on single item view?

**Comment by ruthtillman** [comment]
@banukutlu can we use the similar layout to Princeton? So -- icon + format name (or occasionally names?) on search result. Then icon as thumbnail (until we get real good thumbnails) -- and Format: Book or whatever... on the single page.

**Comment by banukutlu** [comment]
@ruthtillman any icon for default format "Other"?

**Comment by ruthtillman** [comment]
@banukutlu no real preference for other. Possibly: https://fontawesome.com/icons/scroll or https://fontawesome.com/icons/file ? ... I was tempted to suggest https://fontawesome.com/icons/otter for the sound-alike, but...

**Comment by ruthtillman** [comment]
Updated Games logic to cut out some possible mistakes when the record 008 is bad but the main leader value is still ok.

**Comment by banukutlu** [comment]
> Updated Games logic in formats wiki page to cut out some possible mistakes when the record 008 is bad but the main leader value is still ok.

This will be handled with psu-libraries/psulib_traject#113

**Comment by ruthtillman** [comment]
Closing this issue. We may revisit with specific parameters as we go forward, but first pass of formats is done.
