### ISSUE TITLE
Index and display URLs

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#226]
https://github.com/psu-libraries/psulib_blacklight/wiki/URL-Fields

requires https://github.com/psu-libraries/psulib_traject/issues/98
related to https://github.com/psu-libraries/psulib_traject/issues/8

**Comment by cdmo** [comment]
I updated the wiki to streamline and add some details.

**Comment by cdmo** [comment]
Here are some sample links output from Traject when applying the logic from the wiki:

```
http://www.archive.org/details/breedingbirdsofp00harl
http://www.archive.org/details/oppositiontocivi00whit
http://collection1.libraries.psu.edu/u?/digitalbks1,13378
https://www.research.psu.edu/ovpr/magazine
http://www.craftsreport.com/commonfiles/backissues04.html
http://www.geocities.com/TimesSquare/Alley/4482/EEFDigijournals.html
http://archives.chadwyck.com/
http://purl.access.gpo.gov/GPO/LPS862
http://www.libraries.psu.edu/content/dam/psul/up/speccolls/documents/French%20Revolution%20Pamphlet%20Collection.pdf
https://scholarsphere.psu.edu/files/8910jt56k
https://scholarsphere.psu.edu/files/1n79h430f
https://scholarsphere.psu.edu/files/sn009x784
https://scholarsphere.psu.edu/files/02870v85d
http://www.penntap.psu.edu/
http://www.archives.gov/research/microfilm/m803.pdf
http://ezaccess.libraries.psu.edu/login?url=http://catalog.hathitrust.org/Record/009149587
http://www.co.berks.pa.us/planning
http://purl.access.gpo.gov/GPO/LPS87354
```

I assume that we'd like our proxied resources to only show the domain of the url following `url=`, right? E.g., `http://ezaccess.libraries.psu.edu/login?url=http://catalog.hathitrust.org/Record/009149587`

Also, as much I enjoy seeing "geocities.com", http://www.geocities.com/TimesSquare/Alley/4482/EEFDigijournals.html is a 404. Doe we care about URL resolution?

Then there's `http://purl.access.gpo.gov/GPO/LPS87354`. We probably don't want to show `purl.access.gpo.gov` but rather what the purl resolves to which is `www.nrel.gov`.

And this is only for a relatively small sample of items. So I wonder what other thorns might be lurking.

Lastly, what exactly is the "Version/Partial" link? I see we are only displaying on Single Item view but that it has the same label as Fulltext links. Like is this a secondary option or something? If the first URL isn't working?

**Comment by cdmo** [comment]
I'm assuming we'll only want to go after http or https prefixed URLs. Is that right? I've seen one ftp one so far that appears to be a cover image, for example (id: 10787648)

**Comment by cdmo** [comment]
Just keeping a streaming log of questions here. Another: where should the fulltext link and the supplemental link appear in [single-item view order-wise](https://github.com/psu-libraries/psulib_blacklight/wiki/Blacklight-Catalog-Fields)? I see "URL" and it says "May be displayed outside the list" but I'm not sure what that means. We have "Access Online" and "View More Online" according to the [wiki spec page](https://github.com/psu-libraries/psulib_blacklight/wiki/Indexing-and-Displaying-URLs).

**Comment by cdmo** [comment]
Another problem, under the current logic a link can be both fulltext and partial. Consider a record with a 1 in indicator 2. That is a Partial under current spec. It is also a fulltext if that field's subfield z or 3 don't contain one of the magic words. In this scenario the logic will make a fulltext and a partial from the same field.

**Comment by ruthtillman** [comment]
> "I'm assuming we'll only want to go after http or https prefixed URLs. Is that right? I've seen one ftp one so far that appears to be a cover image, for example (id: 10787648)"

- yes

> "Just keeping a streaming log of questions here. Another: where should the fulltext link and the supplemental link appear in single-item view order-wise? I see "URL" and it says "May be displayed outside the list" but I'm not sure what that means. We have "Access Online" and "View More Online" according to the wiki spec page."

... probably somewhere near the top so people can get right to it. Perhaps under the title? I'm open to moving that around. It's listed nearish the bottom because it's also kind of functional so we could have it at the top of sidebar, etc.

> "Another problem, under the current logic a link can be both fulltext and partial. Consider a record with a 1 in indicator 2. That is a Partial under current spec. It is also a fulltext if that field's subfield z or 3 don't contain one of the magic words. In this scenario the logic will make a fulltext and a partial from the same field."

@cdmo do you have a sample?

**Comment by cdmo** [comment]
Sorry for not providing a sample here that you requested @ruthtillman, I somehow completely missed that. We did just meet and I think we will adjust our expectations around what is treated as fulltext for the next go-round.
