### ISSUE TITLE
As a user, I want to see thumbnails of books covers

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#23]
In GitLab by @rkt6 on Mar 29, 2018, 16:06

(nice to have)

**Comment by banukutlu** [comment]
@ruthtillman is this out of scope for the initial release?

**Comment by ruthtillman** [comment]
Yes. We can make it an enhancement later down the road.

**Comment by banukutlu** [comment]
let's evaluate if we can add these as part of MVP3 if not we can move it back to backlog.

**Comment by mkutch** [comment]
I was talking with Charlie and he said that the code is using the ISBN to get book covers from google.  However, there are records with no ISBN (020 field) and there are records that have an ISBN but the isbn search doesn't return any results from google books. In these cases we can use the OCLC number (035 field). 

See catkey `1507850` (has no ISBN)
Google call -
`https://books.google.com/books?jscmd=viewapi&bibkeys=OCLC:213146`
Thumbnail url -
`https://books.google.com/books/content?id=MMQWAQAAMAAJ&printsec=frontcover&img=1&zoom=1`

See catkey `1062205` (has an ISBN but didn't return results. Has an OCLC number that returned thumbnail)
Google call -
`https://books.google.com/books?jscmd=viewapi&bibkeys=OCLC:15692148`
Thumbnail url -
`https://books.google.com/books/content?id=P8VaAAAAYAAJ&printsec=frontcover&img=1&zoom=1`

**Comment by cdmo** [comment]
Thanks @mkutch. We talked a bit about how to process. Sounds like you're suggesting use ISBN first and then if not found, then try OCLC? Or are you not sure of order/precedence?

**Comment by mkutch** [comment]
@cdmo What do you think about sending both? Then you could pick up the first thumbnail url. 

`https://books.google.com/books?jscmd=viewapi&bibkeys=0961545208,OCLC:15692148`
`https://books.google.com/books?jscmd=viewapi&bibkeys=9781493030101,OCLC:1013477802`

**Comment by cdmo** [comment]
@mkutch I could send both, of course, what I'm asking is, to your knowledge, does one take precedence over the other? Thanks.

**Comment by ruthtillman** [comment]
To the best of my knowledge, the challenge is knowing what kind of OCLC number coverage Google books has. Offhand, I don't know if one takes precedence. ISBNs _can_ be duplicates, whereas OCLC numbers shouldn't be. That's my only 2 cents on it.

**Comment by cdmo** [comment]
[Dynamic Links API documentation in Google Books API](https://developers.google.com/books/docs/dynamic-links)

**Comment by cdmo** [comment]
Will add OCLC number as part of the payload

**Comment by cdmo** [comment]
@mkutch came by and discussed adding LCCNs too. Certainly possible, something to consider.

**Comment by mkutch** [comment]
See catkey `25363852 `
This is an example of record where ISBN & OCLC number didn't have the thumbnail url but the LCCN had it. Interesting though was that the ISBN and OCLC number had all the other results returned except the thumbnail. 

https://books.google.com/books?jscmd=viewapi&bibkeys=ISBN:9781440859700,ISBN:1440859701,ISBN:9781440859724,ISBN:1440859728,ISBN:9781440859731,ISBN:1440859736,OCLC:1032289210,LCCN:2018012180

{
   "ISBN:9781440859700":{
      "bib_key":"ISBN:9781440859700",
      "info_url":"https://books.google.com/books?id=iK7DtQEACAAJ\u0026source=gbs_ViewAPI",
      "preview_url":"https://books.google.com/books?id=iK7DtQEACAAJ\u0026source=gbs_ViewAPI",
      "preview":"noview",
      "embeddable":false,
      "can_download_pdf":false,
      "can_download_epub":false,
      "is_pdf_drm_enabled":false,
      "is_epub_drm_enabled":false
   },
   "ISBN:1440859701":{
      "bib_key":"ISBN:1440859701",
      "info_url":"https://books.google.com/books?id=iK7DtQEACAAJ\u0026source=gbs_ViewAPI",
      "preview_url":"https://books.google.com/books?id=iK7DtQEACAAJ\u0026source=gbs_ViewAPI",
      "preview":"noview",
      "embeddable":false,
      "can_download_pdf":false,
      "can_download_epub":false,
      "is_pdf_drm_enabled":false,
      "is_epub_drm_enabled":false
   },
   "ISBN:9781440859724":{
      "bib_key":"ISBN:9781440859724",
      "info_url":"https://books.google.com/books?id=uXubtgEACAAJ\u0026source=gbs_ViewAPI",
      "preview_url":"https://books.google.com/books?id=uXubtgEACAAJ\u0026source=gbs_ViewAPI",
      "preview":"noview",
      "embeddable":false,
      "can_download_pdf":false,
      "can_download_epub":false,
      "is_pdf_drm_enabled":false,
      "is_epub_drm_enabled":false
   },
   "ISBN:1440859728":{
      "bib_key":"ISBN:1440859728",
      "info_url":"https://books.google.com/books?id=uXubtgEACAAJ\u0026source=gbs_ViewAPI",
      "preview_url":"https://books.google.com/books?id=uXubtgEACAAJ\u0026source=gbs_ViewAPI",
      "preview":"noview",
      "embeddable":false,
      "can_download_pdf":false,
      "can_download_epub":false,
      "is_pdf_drm_enabled":false,
      "is_epub_drm_enabled":false
   },
   "ISBN:9781440859731":{
      "bib_key":"ISBN:9781440859731",
      "info_url":"https://books.google.com/books?id=RhaftgEACAAJ\u0026source=gbs_ViewAPI",
      "preview_url":"https://books.google.com/books?id=RhaftgEACAAJ\u0026source=gbs_ViewAPI",
      "preview":"noview",
      "embeddable":false,
      "can_download_pdf":false,
      "can_download_epub":false,
      "is_pdf_drm_enabled":false,
      "is_epub_drm_enabled":false
   },
   "ISBN:1440859736":{
      "bib_key":"ISBN:1440859736",
      "info_url":"https://books.google.com/books?id=RhaftgEACAAJ\u0026source=gbs_ViewAPI",
      "preview_url":"https://books.google.com/books?id=RhaftgEACAAJ\u0026source=gbs_ViewAPI",
      "preview":"noview",
      "embeddable":false,
      "can_download_pdf":false,
      "can_download_epub":false,
      "is_pdf_drm_enabled":false,
      "is_epub_drm_enabled":false
   },
   "OCLC:1032289210":{
      "bib_key":"OCLC:1032289210",
      "info_url":"https://books.google.com/books?id=iK7DtQEACAAJ\u0026source=gbs_ViewAPI",
      "preview_url":"https://books.google.com/books?id=iK7DtQEACAAJ\u0026source=gbs_ViewAPI",
      "preview":"noview",
      "embeddable":false,
      "can_download_pdf":false,
      "can_download_epub":false,
      "is_pdf_drm_enabled":false,
      "is_epub_drm_enabled":false
   },
   "LCCN:2018012180":{
      "bib_key":"LCCN:2018012180",
      "info_url":"https://books.google.com/books?id=bVJyDwAAQBAJ\u0026source=gbs_ViewAPI",
      "preview_url":"https://books.google.com/books?id=bVJyDwAAQBAJ\u0026printsec=frontcover\u0026source=gbs_ViewAPI",
      "thumbnail_url":"https://books.google.com/books/content?id=bVJyDwAAQBAJ\u0026printsec=frontcover\u0026img=1\u0026zoom=5\u0026edge=curl",
      "preview":"partial",
      "embeddable":true,
      "can_download_pdf":false,
      "can_download_epub":false,
      "is_pdf_drm_enabled":false,
      "is_epub_drm_enabled":false
   }
}

**Comment by cdmo** [comment]
Thanks @mkutch looks like LCCN should be added to the mix too.

**Comment by ruthtillman** [comment]
Should we close this issue and add a second thing for adding more fields, e.g. LCCNs, etc. to this?

**Comment by cdmo** [comment]
Works for me, thanks.
