### ISSUE TITLE
Review of ISBN and adding ISSN

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#230]
requires https://github.com/psu-libraries/psulib_traject/issues/101

**Comment by ruthtillman** [comment]
Are we still looking at the issue of qualifiers, e.g. https://blackcat01qa.libraries.psu.edu/catalog/22599844 where everything is broken apart vs. in rows by full field?

**Comment by cdmo** [comment]
Looks like this needs to be fixed. The qualifiers should be listed in the same row as their ISSN/ISBN, right? I mean, of course, but just double checking. We can send this back to the backlog for a quick fix.

**Comment by ruthtillman** [comment]
Yes, listed in the same row!
