### ISSUE TITLE
Range limit on publication year facet

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#234]
Related to #204

Implement the range boxes similar to what Stanford and Princeton have IDEALLY without the slider.

If we have to do the slider, let's start date at 1800

https://github.com/projectblacklight/blacklight_range_limit

**Comment by banukutlu** [comment]
@ruthtillman We moved this issue to MVP3 and also @cdmo pointed out the accessibility issues of this gem: `https://github.com/projectblacklight/blacklight_range_limit/issues/93`

**Comment by cdmo** [comment]
We did get an accessibility review by Michelle McManus of this gem and it passed (the slider interface I mean, which seems like we won't even use)
