### ISSUE TITLE
Homepage display

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#241]
Remove default stuff, add real stuff.

**Comment by cdmo** [comment]
@ruthtillman 

Something like this to start?:


# Penn State University Libraries Catalog

## Other Library Resources

* [LionSearch]()
* [Databases]()
* [Course Reserves]()

**Comment by ruthtillman** [comment]
See: https://psu.app.box.com/notes/450795851979

**Comment by cdmo** [comment]
Changes are deployed, links to standalone pages aren't working yet, but can be reviewed. Of course, the overall styling will change as per @mtribone's mockups

**Comment by ruthtillman** [comment]
Looks mostly good -- can we have the part following "You can also:" as a bulleted list?

**Comment by ruthtillman** [comment]
Also, all the non-catalog resource links are 👍

**Comment by cdmo** [comment]
This has been changed and deployed, so it can be reviewed again. Thanks.

**Comment by ruthtillman** [comment]
Thanks, it looks good! We'll want to mess around a bit with styling, I think, but ++ content, general look/feel.

**Comment by cdmo** [comment]
Great! Considering this one done, of course, reopen when/if needed
