### ISSUE TITLE
Enable docValues for faceting and sorting fields, and general cleanup/tune of facets

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#248]
- [x] Enable docValues for all for faceting and sorting field. Currently not all string fields have it enabled.
- [x]  Remove stored=true from fields that have docValues enabled (including string and numeric fields) and use docValues to retrieve the original data. To do that, either move the schema to 1.6 or to add useDocValuesAsStored for each field type. 

Some refactoring based on audit of facets:
- [x] genre facet can be sim
- [x] subject topic facet can be sim
- [x] remove  "all_authors_facet_ssim"
- [x] remove "genre_full_facet_ssim" 

- [x] review access whence merged

**Comment by cdmo** [comment]
this has been merged in and there's not much to QA because it's all under the hood stuff. So closing.
