### ISSUE TITLE
Index and display Access facet

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#252]
https://github.com/psu-libraries/psulib_blacklight/wiki/Access-Facet

**Comment by banukutlu** [comment]
@ruthtillman will acces facet displayed on search results and/or single item view? or is it just a facet? also will it be included to advanced search? I updated the wiki a bit but could you pls correct if not accurate: https://github.com/psu-libraries/psulib_blacklight/wiki/Access-Facet?

**Comment by ruthtillman** [comment]
Reviewed. These are all accurate. Re: position in sidebar, it would be up top.
