### ISSUE TITLE
Solr cache and tuning

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#256]
- [x] configure filterCache, documentCache, queryResultCache
- [x] `mm` setting might be contributing to suboptimal performance for multi-term queries. For 2- and 3-word queries, this will force scoring of all documents in the _union_ of `DocSets` for all clauses. Figure out an `mm` setting that would restrict domain to at least 2-clause intersection for any multi-term query.
- [x] make sure all the JVM heap is allocated at once, set `Xms` to the same value as `Xmx`, and  add `-XX:+AlwaysPreTouch` flag
- [x] `swapoff -a` (disable swap space until next reboot)
- [x] `vm.swappiness=1` (Minimize swappiness)

**Comment by cdmo** [comment]
Swap is off

![Screenshot 2019-04-08 14 46 59](https://user-images.githubusercontent.com/523381/55748675-3e6e4700-5a0d-11e9-86b7-710c87129274.png)

**Comment by cdmo** [comment]
See https://github.com/psu-libraries/psulib_blacklight/issues/257#issuecomment-480974126 for `mm`

**Comment by cdmo** [comment]
here's a search debug query for ["geographic information systems"](https://gist.github.com/cdmo/4db8098542748a0512cd184b57cb54d9)

it searches
 - geographic
 - information
 - systems
 - geographic information systems
