### ISSUE TITLE
The Because of winn-dixie problem

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#257]
@mkutch just brought up a really good piece of feedback.

Do a search for `because of winn-dixie`. Currently our search returns anything that has any of these terms. Maryam is concerned that this isn't useful. After the first several results, none of the docs returned contain "winn-dixie" which has the affect of adding a lot of noise. Now, I would say that noise is mitigated by the fact that the relevant results are returned much higher.

@ruthtillman do you think this is a problem? Any general thoughts/response?

Maryam, chime in if I'm mis-stating or missing anything.

**Comment by mkutch** [comment]
Thanks @cdmo. 
Also when you start faceting (i.e. Language select non-English one) you notice that records come up that don't have winn-dixie.

I did another search `winn-dixie grocery store`  but don't understand why the records returned don't have winn-dixie in them. Even though the previous search was bringing up records with winn-dixie in them.

**Comment by cdmo** [comment]
It has to do with the algorithm in terms of percent of terms that must match (`mm`). But stepping aside from technical jargon, what _should the user experience be_? If you search `winn-dixie grocery store` should each record contain at least one mention of every word? Or not?

**Comment by mkutch** [comment]
🤷‍♀️

**Comment by ruthtillman** [comment]
Hi folks -- I was out Friday but I'm getting great results on the QA site for all things winn-dixie. I hope that means someone figured it out? Or is this solution messing with something else?

**Comment by ruthtillman** [comment]
Update too -- if we get good results, e.g. we search for Because of Winn-Dixie and that's the first results we get (even if we get a lot more later) or we search for `Winn-Dixie grocery stores` and we get stuff first about winn-dixie and then about general grocery stores but not _Because of Winn-Dixie_ we need to step back and say "is this what a person searching for X expects?" 

Criteria:

* do they get the most relevant result or results for their search up front?
* are the other searches completely unrelated or at least explicable (e.g. more results on grocery stores, yay, that's relevant and may even include stuff about Winn-Dixie ... and "Because of" titles is explicable, so we're ok as long as it comes after the primary title)

We might want to work on refining in title search so that more words are prioritized, I would be ok with that. Otherwise, I think this is something we refine later if we want to address it more.

**Comment by cdmo** [comment]
here's our `mm` determination:
` <str name="mm">2<-1 5<-2 6<90%</str>`

Clauses passed to Solr | Number required to match
-- | --
1 | 1
2 | 1
3 | 1
4 |2
5 | 3
6 | 5
7 | 6
8 | 7
9 | 8
10 | 9
11 | 9
12 | 10
13 | 11
14 | 12
15 | 13
16 | 14
17 | 15
18 | 16
19 | 17

.. and so on at 90% rounded down 


[Docs on `mm`](https://lucene.apache.org/solr/guide/7_4/the-dismax-query-parser.html#TheDisMaxQueryParser-Themm_MinimumShouldMatch_Parameter)

Others do similar things if I'm reading the correct repositories:

SUL `<str name="mm">8<-1 8<90%</str>` (means if 8 or less the number required is the total minus 1, so at 3 it'd be 2 that must match)
PUL `<str name="mm">6<90%</str>` (pretty sure this means 90% always)
TUL `<str name="mm">2<-1 5<-2 6<90%</str>` (exactly the same as ours)

**Comment by mkutch** [comment]
Thanks @cdmo!

If I'm reading the correct repository(solrconfig.xml)

Stanford has `<str name="q.op">AND</str>` . The doc you sent says 

> The default value of mm is 0% (all clauses optional), unless q.op is specified as "AND", in which case mm defaults to 100% (all clauses required).

on another page it said 
> The default mm value is 100% if q.op is "AND" and the query does not contain any explicit operators other than "AND".

So does that mean the their mm is 100% match of all words?

**Comment by cdmo** [comment]
@mkutch stopped by to do some experiments around `q.op`. Turning `q.op` to `AND` forces all to match, it acts an override of `mm`. With it on the results are much more focused. For example `because of winn-dixie` only return items with all of those clauses, which is 5 documents. See [this query in debug mode raw JSON](https://blackcat01qa.libraries.psu.edu/solr/blacklight-core/select?debugQuery=on&defType=edismax&facet.field=access_facet&facet.field=format&facet.field=language_facet&facet.field={!ex=pub_date_facet_single}pub_date_facet&facet.field=subject_topic_facet&facet.field=genre_facet&facet.field=lc_1letter_facet&facet=on&debug=all&q=because%20winn-dixie&q.op=AND&rows=10&f.language_facet.facet.limit=11&f.subject_topic_facet.facet.limit=21&f.genre_facet.facet.limit=21&sort=score%20desc,%20pub_date_sort_itsi%20desc,%20title_sort%20asc). 

As Maryam discovered too, my initial analysis was a little misleading because SUL is using `q.op=AND` and though PUL and TUL don't appear to use it, searching `because of winn-dixie` in both of their catalogs returns a similarly small set of items.

I can always add `q.op=AND` in the Blacklight config because it is a query-time config it doesn't require a re-index.

**Comment by mkutch** [comment]
Try any of the following keyword searches 

`propaganda costa rica` 

`myasthenia gravis dogs`

`homelessness middle east`

Do you think that the results returned are what was intended in the search?

**Comment by ruthtillman** [comment]
@mkutch can you please compare with searches performed both on the current Cat and the Bento interfaces? If we don't know whether we have resources on the subject (these sound like we'd have more article topics), we can't judge whether it's returning the best results for what we do/don't have. Thanks.

**Comment by mkutch** [comment]
Search on `homelessness middle east`
CAT - returns 15 records. 13 are books
Bento - returns over 20,000 records. First and fourth record match all 3 terms. After that looks like it's mostly matching on the word homelessness.

Search on `south america caravans`
CAT - returns 3 records (all books)
Bento - returns close to 54,000 records . Looking at first 20 recs and don't see match on all terms. noticing most matches on caravan.
