### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#264]
https://psu.app.box.com/notes/438846630467

*  Homepage
*  Search results page
*  Single item page

**Comment by banukutlu** [comment]
mockups are here: https://psu.app.box.com/folder/74509861960

**Comment by cdmo** [comment]
@ruthtillman 

Any thoughts on "Refine Search Results" versus the default "Limit your search"?

Forgive me if we covered this already, but I noticed it in the mockup and couldn't remember.

**Comment by ruthtillman** [comment]
I prefer "Refine search results"
