### ISSUE TITLE
Switch to solr cloud

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#267]
- [x] For local and qa environments with embedded zookeeper.
- [ ] ~update configset for prod, create a separate prod configset if necessary~ this may be needed later, for now not required
- [x] deploy configset to prod zk

**Comment by cdmo** [comment]
Info on solr dockerhub image: https://hub.docker.com/_/solr/. 
Running embedded zk issue: https://github.com/docker-solr/docker-solr/issues/180. 
Understanding docker run: https://docs.docker.com/engine/reference/run/. 
Solr Cloud mode from the ref guide: https://lucene.apache.org/solr/guide/7_4/getting-started-with-solrcloud.html

**Comment by cdmo** [comment]
dev and travis are now running solr cloud, next up is QA

**Comment by cdmo** [comment]
QA is in cloud. And updated configsets are in the prod cluster. I think we're all good here.

**Comment by banukutlu** [comment]
> QA is in cloud. And updated configsets are in the prod cluster. I think we're all good here.

🎉  great work @cdmo! thanks!
