### ISSUE TITLE
Advanced Search: Location

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#269]
Born from #239
Requires https://github.com/psu-libraries/psulib_traject/issues/121

Aha! Link: https://penn-state-university-libraries.aha.io/features/STPROJ-48

**Comment by ruthtillman** [comment]
Behavior expectations for Advanced Search by Location is here: https://github.com/psu-libraries/psulib_blacklight/wiki/Library-Faceting-and-Locations-Management#locations-advanced-search

**Comment by ruthtillman** [comment]
Order of operations thought:

1. Index from 949l (L)
2. Exclude locations the excludes list
3. Map to our other locations label list.
4. Add as to advanced search.
5. Profit?

**Comment by cdmo** [comment]
🤑

**Comment by ruthtillman** [comment]
GORGEOUS!
