### ISSUE TITLE
Link preceding/succeeding titles to title search

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#279]
Building from this: https://github.com/psu-libraries/psulib_blacklight/issues/205

Link to search for title. Example record: https://blackcat01qa.libraries.psu.edu/catalog/10406572

Continued By would search for `Voprosy istorii (Akademii͡a nauk SSSR. Institut istorii)` for example.

**Comment by ruthtillman** [comment]
Seems good but link text is broken? https://blackcat01qa.libraries.psu.edu/catalog/1232415 per @cdmo it's noted in https://github.com/psu-libraries/psulib_blacklight/issues/319 so otherwise this seems good!

**Comment by cdmo** [comment]
Will be fixed in next deploy :)
