### ISSUE TITLE
Log shipping to SPM

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#283]
Traject & Rails (https://apps.sematext.com/ui/integrations/apps/25811/integrations/ruby)
Solr
Other?

**Comment by cdmo** [comment]
https://rocketjob.github.io/semantic_logger/

**Comment by cdmo** [comment]
this one looks nice too https://github.com/twp/logging

Otis shared both of these

**Comment by banukutlu** [comment]
Radu implemented this so closing
