### ISSUE TITLE
Remove search on top from the advanced search page

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#292]

**Comment by banukutlu** [comment]
@ruthtillman I just checked some of the other Advanced Search implementations like Stanford, Princeton and Temple, they kept the search on top. What do you think, should we remove or keep it?

**Comment by ruthtillman** [comment]
Per our discussion, let's remove the whole bar!

**Comment by ruthtillman** [comment]
Just wanted to reinforce that I've seen this cause momentary confusion in some tests as well. The button saying "Search" makes people reviewing their terms think they can click "Search" at the top and have it perform the advanced search.
