### ISSUE TITLE
Pages: About and Search Tips

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#307]
See below "[Additional pages we need](https://psu.app.box.com/notes/450795851979)"

**Comment by cdmo** [comment]
I've added the `high_voltage` gem which allows easy static page creation and appears to be the defacto standard way of doing this sort of thing in the BL community. Content can be edited in `erb` format at https://github.com/psu-libraries/psulib_blacklight/tree/master/app/views/pages. Will this work for you @ruthtillman?

**Comment by ruthtillman** [comment]
Looks doable! Thank you!

**Comment by cdmo** [comment]
Considering this one done, of course, reopen when/if needed
