### ISSUE TITLE
Implement global look and feel

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#318]
based on @mtribone's mockups:

- [x] chrome of site
- [x] color scheme
- [x] branding
- [x] font families
- [x] ~font sizing hierarchies~ (no change needed yet)
- [x] ~line-height~ (no change needed yet)
- [x] sidebar facets (examine gutter widths) 
- [x] overall max-width
- [x] check breakpoints

**Comment by banukutlu** [comment]
mockups here: https://psu.app.box.com/folder/74509861960

**Comment by cdmo** [comment]
danke

**Comment by ruthtillman** [comment]
Looks good! We will add any edits via individual issues.
