### ISSUE TITLE
Item view

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#319]
Implementing mockup for individual item (moving links out of sidebar, removing sidebar, etc)

**Comment by cdmo** [comment]
Assuming it's this [guy](https://psu.app.box.com/file/446221885088)

**Comment by banukutlu** [comment]
> Assuming it's this [guy](https://psu.app.box.com/file/446221885088)

@ruthtillman ? for item view which mockup do we want to implement: the thumbnail left under or left beside one?

**Comment by banukutlu** [comment]
https://github.com/psu-libraries/psulib_blacklight/wiki/Blacklight-Catalog-Fields#single-item-view-labels

**Comment by ruthtillman** [comment]
yep that one.

**Comment by cdmo** [comment]
The mockup drops back to search results and paging through results, which I assume we actually do want to keep. I'll just use my judgment and we can go from there.

**Comment by cdmo** [comment]
Hi @ruthtillman, I'm about finished up with this issue as a "first step" kind of thing. Here's a screenshot example of an [item view (a first iteration)](https://user-images.githubusercontent.com/523381/58720762-1104a080-83a1-11e9-806d-1f2376d429f6.png). We'll deploy next week (after a review from @banukutlu) but while it's fresh in my mind I wanted to add a bit of context: 

1) The bookmark action is still just a checkbox input. I think I was wondering if we really wanted to keep the Bookmark feature or not. I think the answer is "we do" but thought I'd ask again just to make sure. If we do keep it, I can make the checkbox appear as a button (a la orangelight) 
2) I'm not sure about the display of secondary metadata. The mockup has it as a label + line break + contents at full width (or maybe it's not quite full width, I'll ask @mtribone ). [Text at full width on large screen is difficult to read](http://webtypography.net/2.1.2). This is to say that I've left it as the default two column layout for now (col 1 = label, col 2 = value).

**Comment by mtribone** [comment]
@cdmo Yeah I definitely think that you can start getting into media queries and make some adjustments to the line length of the secondary metadata at full screen. Perhaps make some tests of 1200px and above and see how the text adjusts.

**Comment by mtribone** [comment]
Maybe the "full screen" is for smaller resolutions and then 1200px and above gets centered at a certain width and has padding on the left and right.

**Comment by cdmo** [comment]
Cool, thanks for the feedback. I also feel like it'd be useful to get holding availability details in here too. So it might be useful to sort of leave it where it's at until we get availability merged in (which should be soon)

**Comment by cdmo** [comment]
I'm putting this back into the backlog so that these can be finished up:

- [ ] Holdings space is empty for online access items, the access online link needs to move up here
- [ ] markup is not being processed correctly for the serials fields

**Comment by cdmo** [comment]
Another issue I just noticed. When viewing a direct link to a catalog item the top-bar utilities and the bottom bar with the link to the marc view disappear, as opposed to viewing an item in the context of search results.

- [ ] Direct link view bug

**Comment by ruthtillman** [comment]
Unsure why Format is included in the Single Item vie. Per display page it's only on search results & such https://github.com/psu-libraries/psulib_blacklight/wiki/Blacklight-Catalog-Fields#single-item-view-labels

should be an easy removal.

**Comment by cdmo** [comment]
Thinking about how we display holdings and availability. Looking at the [mockup](https://psu.app.box.com/file/446221885088) we sort of have it displayed alongside physical holdings. This is problematic because we group by library. 

So displaying full text links. How should we go about that? It'll typically be a simple text value of "serialsolutions.com" or something and a link out. It could live a table lonely by itself? Or be a button? Or added to the top fields area with some special treatment of some sort? Ideas/thoughts @ruthtillman or @mtribone (or anyone?)?

**Comment by mtribone** [comment]
@cdmo system processing... let me think on this one a bit

**Comment by cdmo** [comment]
Just checked in during a Zoom session with @ruthtillman and @banukutlu and I think we're leaning towards displaying the fulltext links above in the top fields area. Unresolved is whether or not we give it a special treatment of some sort to make it stand out from the rest of the top fields.

**Comment by cdmo** [comment]
Latest changes have been deployed. However, I can see some issues still outstanding, especially at the small screen. See below.

![Screenshot_2019-06-18 Brill's companion to Aineias Tacticus edited by Maria Pretzler, Nick Barley - Blacklight](https://user-images.githubusercontent.com/523381/59689373-8d72ee00-91ad-11e9-91ce-112e144e0083.png)

todo:

- [ ] empty space between top fields and bottom fields when no availability
- [ ] small screen should shrink title font size and image should be responsively re-sizing to its container width
- [ ] links above search bar and below branding need to be cleaned up

**Comment by ruthtillman** [comment]
Also check how these affect search results -- right now, image on mobile is causing some spacing issues, as is bookmark.

**Comment by cdmo** [comment]
As per conversation with @ruthtillman and @banukutlu yesterday, we're going to 

- [ ] hide Cite (as in the plain text citation export)
