### ISSUE TITLE
Manage robots

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#320]
robots.txt

**Comment by cdmo** [comment]
example https://catalog.princeton.edu/robots.txt

**Comment by cdmo** [comment]
Hey @ruthtillman, I think it's time we open the blackcat catalog to bots. Currently we don't allow any search index spiders or respectful bots, but, with relative stability over the past couple of months I think it's a good time to open it up.

**Comment by ruthtillman** [comment]
@cdmo that's fine with me -- because I'll be out of town Mon-Wed, I won't be able to monitor/respond as quickly.
