### ISSUE TITLE
Look and feel details

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#322]
- [x] utility nav (figure out what to do first)
- [x] move Start Over button 
- [x] move constraints
- [x] maybe change facet area heading text
- [x] favicon

**Comment by cdmo** [comment]
These are all done and PR'd (#327). So, one caveat, I did go ahead and make advanced search and "start over" plain links instead of buttons. The interface can feel so heavy, so I think this is one easy way to ease the overall heaviness. Also, eve as it is I think it'd be good to make these plain text links smaller in font size. 

Another thing, I made start over and advanced search show up in the hamburger nav at mobile. We didn't do mobile so this was a judgement call I made.

**Comment by cdmo** [comment]
Changes from this issue have been deployed. Changes include: Updated links for utility nav and search bar, wider facets, constraints restyled and  moved to just above search results (not in individual item view yet), facet area heading text updated, PSU favicon, "start over" button moved.

**Comment by ruthtillman** [comment]
This is all looking really good!
