### ISSUE TITLE
Investigate notifications of new works

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#332]
The Cat via Symphony has ways of notifying people when new things by a favorite author, etc., are added. Can we implement anything like this in Blacklight?

**Comment by cdmo** [comment]
Sorta built in? If you use `catalog.atom` you can get a feed of any search, i.e., 

https://blackcat01qa.libraries.psu.edu/?f%5Ball_authors_facet%5D%5B%5D=Bryson%2C+Bill

If people still did RSS subscriptions we'd be all set. Does the CAT email?

**Comment by banukutlu** [comment]
@mkutch Would you investigate if webservices any endpoint we can use?
