### ISSUE TITLE
Investigate Capistrano

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#34]
In GitLab by @bzk60 on Apr 19, 2018, 15:11

https://github.com/capistrano/capistrano/blob/master/README.md  
https://gist.github.com/jrochkind/2161449  
https://github.com/pulibrary/orangelight#deploying-with-capistrano  

[Capify-the-project](../wiki/Capify-the-project)

Aha! Link: https://penn-state-university-libraries.aha.io/features/STPROJ-69

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Apr 19, 2018, 15:48

added ~1515 label

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Apr 19, 2018, 17:26

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Apr 24, 2018, 13:10

changed the description

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 17, 2018, 13:39

added ~938 label

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 19, 2018, 10:46

removed ~938 label

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 20, 2018, 15:40

added ~938 label

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 20, 2018, 15:56

changed the description

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 20, 2018, 15:56

changed the description

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 20, 2018, 16:29

removed ~938 label

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 23, 2018, 12:25

added ~938 label

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 23, 2018, 12:37

created branch [`35-investigate-capistrano`](https://git.psu.edu/i-tech/psulib_blacklight/compare/master...35-investigate-capistrano)

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 23, 2018, 14:02

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 31, 2018, 09:59

removed ~938 label

**Comment by banukutlu** [comment]
In GitLab by @ful105 on Aug 24, 2018, 13:44

removed milestone

**Comment by banukutlu** [comment]
In GitLab by @ful105 on Aug 24, 2018, 13:45

Take a look at for rollbacks (not for main deployment).

**Comment by cdmo** [comment]
see https://github.com/psu-libraries/psulib_blacklight_deploy/issues/42
