### ISSUE TITLE
Some/Many netLibrary records not displaying URL to online content

### ISSUE THREAD

**Issue by mkutch** [psu-libraries/psulib_blacklight#352]
To see more  do an author/creator search  on "netLibrary"
 
https://blackcat01qa.libraries.psu.edu/catalog/2893913
https://blackcat01qa.libraries.psu.edu/catalog/3937333
https://blackcat01qa.libraries.psu.edu/catalog/4739297
https://blackcat01qa.libraries.psu.edu/catalog/3938513

**Comment by cdmo** [comment]
@mkutch and I discussed in office. From the record we looked at the indicator 2 wasn't a `0` which is probably why it isn't being mapped. [Mapping rules from wiki](https://github.com/psu-libraries/psulib_blacklight/wiki/URL-Fields) need to be updated or perhaps a catloging fix needed?

**Comment by cdmo** [comment]
Found another record that is online, but doesn't seem to have an 856 at all

https://blackcat01qa.libraries.psu.edu/catalog/27050987
https://blackcat01qa.libraries.psu.edu/catalog/27050987/marc_view

**Comment by mkutch** [comment]
@cdmo Looks like this record is ON-ORDER so that could be why there is no 856 yet.

**Comment by ruthtillman** [comment]
I updated the URLs in the wiki to include the appropriate logic.
