### ISSUE TITLE
Refine logic to handle when copies only available via ILL

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#355]
There are a handful of locations which, if they are the currentLocationID, should trigger ILL availability display rather than standard display.

Locations which should trigger ILL display:

  "request_via_ill": {
    "BINDERY": "This copy unavailable, submit request via Interlibrary Loan",
    "BINDPRP-DN": "Dickinson School of Law, Carlisle - Material in Bindery Prep",
    "DARCHIVE-P": "This copy unavailable, submit request via Interlibrary Loan",
    "DEPTCHARGE": "Material has been checked out to a department",
    "HARSHBARGR": "Interreligious Lib. 111 Pasquerilla Spiritual Ctr. Unavailable",
    "ILL": "On loan to another library",
    "ILLEND": "On loan to another library",
    "LOST": "This copy unavailable, submit request via Interlibrary Loan",
    "MISSING": "This copy unavailable, submit request via Interlibrary Loan",
    "REPAIR": "Material being repaired",
    "CANCELED": "Order Canceled; see order record for details."
  },

Display layout:

| Call number | Material | Location |
| --- | --- | --- |
| $CallNumber | mapped material | Copy unavailable, request via Interlibrary Loan |

with each ILL request linked e.g. https://psu-illiad-oclc-org.ezaccess.libraries.psu.edu/illiad/upm/illiad.dll?Action=10&Form=30&isbn=&title=Physical%20review.%20A%2C%20General%20physics&aulast=American%20Physical%20Society.&callno=QC1.P42%20v.1%20p.1-538%201970&rfr_id=info%3Asid%2Fcat.libraries.psu.edu&date=1970-1989.

where variables are:

- title
- primary author (person/corporation/meeting)
- isbn
- date: from 264|*1|c or 260c
- OCLC no
- call number
- where did you find this item cited (we will want to send the new catalog URL)

Examples current as of 6/18, changes to the records may change utility.

Example: a book entirely in DARCHIVE-P https://blackcat01qa.libraries.psu.edu/catalog/1232415

Example: a book with some copies unavailable at all and some checked out. This should have both an I Want It button and a This Copy is Unavailable dialogue. This is not ideal, but because we cannot guarantee that volume 1 is completely unavailable while volume 2 is just retrievable with I Want It, we need to be clear about individual-level issues https://blackcat01qa.libraries.psu.edu/catalog/22080733

**Comment by ruthtillman** [comment]
Updated main ticket, now updating wiki

**Comment by mkutch** [comment]
The Hazleton Library will be undergoing a renovation beginning May 6, 2019 - January 13, 2020 with a contingency deadline of June 2020. The library building will be closed during construction. I was asked to add the message to Hazelton library books.  See https://cat.libraries.psu.edu/uhtbin/cgisirsi/0/0/0/5?searchdata1=^c1528456

> This copy unavailable, submit request via Interlibrary Loan.

We should add this to the list.

**Comment by mkutch** [comment]
@ruthtillman  the call number was hidden on the Illiad page. I spoke with Shane in ILL and asked if it could be visible because a patron would want to know what volume/date, for instance, they selected for verification. Regarding date , Shane modified the openurl mapping for date (it was only accepting 4 digit dates). So if you look try your link again you will see the date and call number visible and populated.
Also regarding the other fields (i.e publisher, edition....) they are openurl mapping isn't setup so if you sent it wouldn't be seen on their end.

**Comment by mkutch** [comment]
We also need to add the ILL link the Archival Thesis, since ILL has taken over archival thesis scanning for outside patrons. So if home location is "ARKTHESES" or "AH-X-TRANS", they want this special 3 prong link.  See
https://cat.libraries.psu.edu/uhtbin/cgisirsi/0/0/0/5?searchdata1=^c123730

**Comment by ruthtillman** [comment]
@mkutch might you be able to find a hundred catkeys or so to help us test? ... I'm also wondering whether current location will generally also be that or if they're being sent to ILL for scanning their current location has changed (and then whether that actually matters because if it's being scanned then maybe it's unavailable for request / it shouldn't happen much)

I ask because we're mostly using current locations at this point vs. home.

**Comment by mkutch** [comment]
@ruthtillman checking for current location of "ARKTHESES" or "AH-X-TRANS" works too. I confirmed with Shane also. 
I put a hundred catkeys with their current location and title in box (archivaltheses_sample.txt)

**Comment by ruthtillman** [comment]
Thanks @mkutch! I've documented this here: https://github.com/psu-libraries/psulib_blacklight/wiki/Holdings-and-Availability-Display#request-digitization-of-archival-thesis

**Comment by banukutlu** [comment]
> @ruthtillman the call number was hidden on the Illiad page. I spoke with Shane in ILL and asked if it could be visible because a patron would want to know what volume/date, for instance, they selected for verification. Regarding date , Shane modified the openurl mapping for date (it was only accepting 4 digit dates). So if you look try your link again you will see the date and call number visible and populated.
> Also regarding the other fields (i.e publisher, edition....) the openurl mapping isn't setup so if you sent it wouldn't be seen on their end. He said they don't need/require those field.

Thanks @mkutch, we won't send publisher and edition to Illiad.

**Comment by ruthtillman** [comment]
Notes for Aeon link for ArchivalTheses:

- Genre: If itemTypeID == ARCHIVES then Genre = ARCHIVES, else Genre = BOOK. For ArchivalTheses, this should always be BOOK.
- ItemNumber == ItemInfo/itemID (which is the Barcode)
- Location: currentLocationID mapped
- ItemInfo1 = restrictions_access_note_ssm (will mostly be blank)

SubLocation will not be used for Archival Theses.

**Comment by ruthtillman** [comment]
Aeon mappings for Archival Theses:

    ReferenceNumber: catkey
    Genre: If itemTypeID == ARCHIVES then Genre = ARCHIVES, else Genre = BOOK. For ArchivalTheses, this should always be BOOK.
    ItemTitle: 245ab title
    ItemAuthor: personal, corporate, or meeting author (1xx, not 7xx)
    Location: currentLocationID mapped
    ItemEdition: edition_display_ssm
    Call Number: CallInfo/callNumber
    ItemPublisher: publisher (260b:264|*1|b)
    ItemDate: 260c:264|*1|c
    ItemNumber: ItemInfo/itemID (which is the Barcode)
    ItemInfo1: restrictions_access_note_ssm (will mostly be blank)
