### ISSUE TITLE
Add Ask a Librarian

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#356]
Add "Ask a Librarian" side tag. For mobile, add to header hamburger? Don't let it pop under!

**Comment by ruthtillman** [comment]
Seems to only show up when a keyword is searched?

I'm not getting it when I just facet, eg.. https://blackcat01qa.libraries.psu.edu/?f%5Bformat%5D%5B%5D=Government+Document&search_field=all_fields&utf8=%E2%9C%93 but if I then perform a keyword search, like "space" I get Ask a Librarian.

It doesn't show up on Advanced Search. Perhaps it should.

And more testing:

1. When I do an advanced search, even with just controlled fields, it seems to show up: https://blackcat01qa.libraries.psu.edu/catalog?utf8=%E2%9C%93&op=AND&all_fields=&title=&author=&subject=&identifiers=&series=&publisher=&f_inclusive%5Baccess_facet%5D%5B%5D=In+the+Library&f_inclusive%5Bformat%5D%5B%5D=Games%2FToys&f_inclusive%5Bformat%5D%5B%5D=Juvenile+Book&f_inclusive%5Blanguage_facet%5D%5B%5D=English&range%5Bpub_date_itsi%5D%5Bbegin%5D=2000&range%5Bpub_date_itsi%5D%5Bend%5D=&sort=score+desc%2C+pub_date_itsi+desc%2C+title_sort+asc&search_field=advanced&commit=Search

2. When I click through to see more on a subject: https://blackcat01qa.libraries.psu.edu/?f[subject_facet][]=Xenomorphs+%28Fictitious+characters%29 or more by an author: https://blackcat01qa.libraries.psu.edu/?f%5Ball_authors_facet%5D%5B%5D=Grant%2C+Mira I don't see it.

So it seems to be not showing on purely faceted search?

This is fine for go-live, but long-term it should show on faceted results and Advanced Search page.

**Comment by cdmo** [comment]
I actually deployed this to prod today, with @ruthtillman permission, but, just wanted to make a note here of that - it was deployed before being approved officially.
