### ISSUE TITLE
Change title tag from "Blacklight" to "Catalog"

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#359]
Title tags currently based around the word "Blacklight" -- replace with "Catalog"

**Comment by cdmo** [comment]
This is done already - unless I've missed it. I checked <title> and it looks right to me. This is dictated by the locale file fwiw, changed on this [commit](https://github.com/psu-libraries/psulib_blacklight/commit/a37b95e8e6a632afdab645babae1e11c7069c762#diff-ad9f93c4468ae38646b8c7c3e32d3546R4) - the attribute is `application_name`

**Comment by ruthtillman** [comment]
Looks right
