### ISSUE TITLE
SMS (Email to text) not working

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#361]

**Comment by cdmo** [comment]
During a meeting on 6/25 we discussed using SMTP from PSU as an option

**Comment by cdmo** [comment]
Do we want to try this fix for the 0.2.x?

**Comment by banukutlu** [comment]
> Do we want to try this fix for the 0.2.x?

I think yes but if we have time if not we can hide it and leave it to 1.0.x

**Comment by cdmo** [comment]
What I was thinking too, cool

**Comment by ruthtillman** [comment]
2023 update: this is still hidden. I am going to close it, but we could consider it as a feature enhancement somewhere down the road.
