### ISSUE TITLE
Add Aeon request for archival materials

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#376]
Aeon fields to pass:

- ReferenceNumber: catkey
- Genre: If itemTypeID == ARCHIVES then Genre = ARCHIVES, else Genre = BOOK. For ArchivalTheses, this should always be BOOK.
- ItemTitle: 245ab title
- ItemAuthor: personal, corporate, or meeting author (1xx, not 7xx)
- Location: currentLocationID mapped
- ItemEdition: edition_display_ssm
- Call Number: CallInfo/callNumber
- ItemPublisher: publisher (260b:264|*1|b)
- ItemDate: 260c:264|*1|c
- ItemNumber: ItemInfo/itemID (which is the Barcode)
- ItemInfo1: restrictions_access_note_ssm

**Comment by banukutlu** [comment]
https://github.com/psu-libraries/psulib_blacklight/wiki/Holdings-and-Availability-Display#request-digitization-of-archival-thesis
