### ISSUE TITLE
Identify webservices call based on itemID

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#383]
Can we streamline bound-with by retrieving a WebServices response for just the item based on itemID? Maryam, can you check the WS documentation and share a URL?

**Comment by mkutch** [comment]
Yes, Replace titleID with itemID.  

https://cat.libraries.psu.edu:9443/symwsbc/rest/standard/lookupTitleInfo?clientID=BCPAC&itemID=000015871787&includeAvailabilityInfo=true&includeItemInfo=true&includeBoundTogether=true

**Comment by ruthtillman** [comment]
Thanks! And for getting data to go with the bound-withs, we'd probably want to remove includeBoundTogether since we just want the most specific record: e.g https://cat.libraries.psu.edu:9443/symwsbc/rest/standard/lookupTitleInfo?clientID=BCPAC&itemID=000051903985&includeAvailabilityInfo=true&includeItemInfo=true
