### ISSUE TITLE
Improve book cover matching with LCCNs etc.

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#393]
Expand on #23 for post-MVP.

**Comment by cdmo** [comment]
@ruthtillman: I'm QAing LCCN's locally and found [Kōshi yawa, zokuhen](https://catalog.libraries.psu.edu/catalog/51/marc_view) ends up with this as an LCCN: `j  66002863`. Also [Das Altertum : Geschichte und Gestalt der Mittelmeerwelt](https://catalog.libraries.psu.edu/catalog/4383/marc_view) ends up with `a  59003722`. And another [odd one](https://catalog.libraries.psu.edu/catalog/4373/marc_view) (`af 47001320`).

Prefixes seem okay after reading through the doc you linked to in the wiki as well as [the MARC 21 docs](https://www.loc.gov/marc/bibliographic/bd010.html). I just want to confirm.

**Comment by cdmo** [comment]
Sorry, I had forgotten we (@banukutlu) mapped OCLC number already https://github.com/psu-libraries/psulib_traject/issues/162 My comment above about mapping OCLC can be ignored.

**Comment by ruthtillman** [comment]
@cdmo Can you see what Google books is expecting for book cover? I'm wondering if we should sub a _ for spaces or something similar.

**Comment by ruthtillman** [comment]
Looks good!
