### ISSUE TITLE
Add "More in this series" for Series statements

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#4]
In GitLab by @rkt6 on Feb 8, 2018, 13:30

e.g. https://pulsearch.princeton.edu/catalog/5351412/

We may change how we handle or display it based on feedback, but the series search link that separates it from display makes it somewhat clear? Let's pursue this for first iteration of the app at least.

Princeton code:

https://github.com/pulibrary/orangelight/blob/327f6410e90fa2dfbf7b214724851433d3819881/app/helpers/application_helper.rb#L117-L160

**Comment by cdmo** [comment]
What's the status with this? Should it be in 1.x milestone?

**Comment by banukutlu** [comment]
This has been handled by #537
