### ISSUE TITLE
View More and View Less on Availability are Very Bright

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#411]
This is a placeholder note to review w/Mike Tribone: e.g. https://blackcat01qa.libraries.psu.edu/catalog/79172

When we have lots of libraries which have it + lots of copies, it gets even more so. Could this just be making the button visible but a little less bold?

Aha! Link: https://penn-state-university-libraries.aha.io/features/STPROJ-30

**Comment by cdmo** [comment]
This is our list of current work to do, but feels like maybe less urgent. I am going to remove it from the Pre-Release 2 milestone. If I'm wrong and it is something that needs to be done in the near term please change back.
