### ISSUE TITLE
Add Aeon Request for Non-Thesis Archival Materials

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#429]
URLs and fields documented here:

https://github.com/psu-libraries/psulib_blacklight/wiki/Holdings-and-Availability-Display#request-archival-materials-using-aeon

- ReferenceNumber: catkey
- Genre: If itemTypeID == ARCHIVES then Genre = ARCHIVES, else Genre = BOOK. For ArchivalTheses, this should always be BOOK.
- ItemTitle: 245ab title
- ItemAuthor: personal, corporate, or meeting author (1xx, not 7xx)
- Location: currentLocationID mapped
- ItemEdition: edition_display_ssm
- Call Number: CallInfo/callNumber
- ItemPublisher: publisher (260b:264|*1|b)
- ItemDate: 260c:264|*1|c
- ItemNumber: ItemInfo/itemID (which is the Barcode)
- ItemInfo1: restrictions_access_note_ssm

Trigger:

If the item is in library `UP-SPECCOL`, add a link to "Request Material" to each item. (leave current location text too). e.g. https://cat.libraries.psu.edu/uhtbin/cgisirsi/x/0/0/57/5/0?searchdata1=22076422%7BCKEY%7D&searchfield1=GENERAL%5ESUBJECT%5EGENERAL%5E%5E&user_id=WEBSERVER 

... if the item currentLocationID is `ARKTHESES` or `AH-X-TRANS`, keep current linking (note -- I don't know if these two have overlaps, it's possible there are no ARKTHESES or AH-X-TRANS in UP-SPECCOL?)

**Comment by banukutlu** [comment]
@mkutch which one we should be using for archival materials?

`https://aeon.libraries.psu.edu/RemoteAuth/aeon.dll?Action=10&Form=30`

`https://aeon.libraries.psu.edu/Logon/?Action=10&Form=30`

**Comment by mkutch** [comment]
We want the Logon link because we want the user to see to see the 2 different Login options.   Because if you are not PSU affliated  you don't have a webaccess account and so you need to be able to register with Aeon or go login with your Aeon account (Guest).  The RemoteAuth takes you directly to webaccess. 
![image](https://user-images.githubusercontent.com/43478453/63366227-44731d80-c347-11e9-8fec-ba457005630c.png)

**Comment by ruthtillman** [comment]
From QA, two things I hadn't properly accounted for, sorry.

1) For archival materials, Form=20. This should be an easy sub, I hope.
2) URL should contain a Value= parameter. Logic: `If itemTypeID == ARCHIVES then URL "Value" should be Value=GenericRequestManuscript, else it should be Value=GenericRequestMonograph.` I hope because we're already testing itemTypeID you should be able to set both the Genre and Form values in that one test.

I updated the wiki and will re-review after my next meeting to be sure I caught all Form=20 instances.

**Comment by banukutlu** [comment]
> From QA, two things I hadn't properly accounted for, sorry.
> 
> 1. For archival materials, Form=20. This should be an easy sub, I hope.
> 2. URL should contain a Value= parameter. Logic: `If itemTypeID == ARCHIVES then URL "Value" should be Value=GenericRequestManuscript, else it should be Value=GenericRequestMonograph.` I hope because we're already testing itemTypeID you should be able to set both the Genre and Form values in that one test.
> 
> I updated the wiki and will re-review after my next meeting to be sure I caught all Form=20 instances.

@ruthtillman Form=20 for archival materials and Form=30 for archival thesis, right?

**Comment by mkutch** [comment]
The 799 field needs to be added to Special Collections Aeon requests because they need it to be on their call slips.
See  https://github.com/psu-libraries/psulib_traject/issues/167  to see how you can get the field via webservice call.

**Comment by banukutlu** [comment]
> The 799 field (SubLocation) needs to be added to Special Collections Aeon requests because they need it to be on their call slips.
> See [psu-libraries/psulib_traject#167](https://github.com/psu-libraries/psulib_traject/issues/167) to see how you can get the field via webservice call.

@ruthtillman what do you think? should we map 799 to a new field and pass that to aeon url?
@mkutch

**Comment by ruthtillman** [comment]
@banukutlu yes, that sounds good. It just needs to be usable in Aeon, not searchable

**Comment by ruthtillman** [comment]
Special Collections is good to deploy what we've got now, and are happy the 799s will be added.

**Comment by cdmo** [comment]
Can this be closed @ruthtillman ? If so, that means the milestone can officially be closed too 🎉

**Comment by ruthtillman** [comment]
I think so -- provided we fold in 799s update somewhere.
