### ISSUE TITLE
Did you mean and Fuzzy Search

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#44]
In GitLab by @rkt6 on Jun 12, 2018, 10:16

Suggestive search is currently turned off in Solr. We should figure out what the error is and then see how well it works when it's working.

Aha! Link: https://penn-state-university-libraries.aha.io/features/STPROJ-68

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 12, 2018, 10:17

Also check on "Did you mean?" search and what it does.

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 12, 2018, 10:19

Check on Fuzzy searching

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 12, 2018, 10:20

changed title from **Explore s{-uggestive search-}** to **Explore s{+earch suggestions and alternatives+}**

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 12, 2018, 10:20

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 12, 2018, 10:20

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 12:56

assigned to @bzk60

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 12:56

added ~938 label

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 12:57

removed ~938 label

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 12:57

added ~1518 label

**Comment by ruthtillman** [comment]
Not going to pursue this feature. Could be helpful when it catches legitimate typos, but I haven't seen any implementations which actually work well and don't do as many weird as helpful things.
