### ISSUE TITLE
Clicking on facets on mobile device not quite working properly

### ISSUE THREAD

**Issue by mkutch** [psu-libraries/psulib_blacklight#445]
On mobile device, when I clicked on the gray block or  arrow `>` I was expecting the facet drop down, but I got no response. I had to click on the facet word.

**Comment by ruthtillman** [comment]
Additional info -- we're displaying a > and a generally longer gray area... on mobile it won't respond. But if you click on word it responds by opening.

**Comment by cdmo** [comment]
Looks like related or perhaps exactly the same as what we are seeing: https://github.com/projectblacklight/blacklight/issues/2127
