### ISSUE TITLE
Titles with html and other strange characters

### ISSUE THREAD

**Issue by mkutch** [psu-libraries/psulib_blacklight#460]
see https://psu.app.box.com/folder/83750921142

**Comment by cdmo** [comment]
here's link to the [Box Note directly](https://psu.app.box.com/file/502407232203) instead of the folder.

@mkutch can you give some more information about the problem you're seeing here? I looked at one, 13810251, and I didn't see a problem.. but, I think I'm missing it.

**Comment by mkutch** [comment]
@cdmo - It looks like some have been cleaned up since I last posted (like the multiple As with the tilda on top) . If you go to 
https://catalog.libraries.psu.edu/?utf8=%E2%9C%93&search_field=all_fields&q=xmlns
https://catalog.libraries.psu.edu/?utf8=%E2%9C%93&search_field=all_fields&q=mrow

 This is more cataloging cleanup issue. Is there a different place we should put issues like these?

**Comment by cdmo** [comment]
Think this would be a question for @ruthtillman

**Comment by ruthtillman** [comment]
I passed it on to the DAT team.

**Comment by ruthtillman** [comment]
Done!
