### ISSUE TITLE
Display of Online Content - 856 field

### ISSUE THREAD

**Issue by mkutch** [psu-libraries/psulib_blacklight#461]
We should look into making the display of online content to show more specific information on what to expect when you click on a link, as much as possible.  For instance see catkey `1408618` in Blackcat vs. The CAT. 

![image](https://user-images.githubusercontent.com/43478453/64261408-7a450400-cefa-11e9-92ee-c0b9da4f4347.png)

If a subfield 3 and/or subfield z exists to display them.
Also if we don't have subfield 3 and/or subfield z it's helpful to patron and staff to display the entire subfield u.

Aha! Link: https://penn-state-university-libraries.aha.io/features/STPROJ-25

**Comment by mkutch** [comment]
Another example ... See catkey `8272923`

![image](https://user-images.githubusercontent.com/43478453/64459861-f724d900-d0c6-11e9-8972-430e1d51ad24.png)

**Comment by cdmo** [comment]
Assigning to @ruthtillman, @mkutch. I think this is meant for her to address. Correct me if I'm wrong, of course.

**Comment by banukutlu** [comment]
handled with #672
