### ISSUE TITLE
Temporarily change banner to reflect CAT upgrade

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#478]
Change text of banner temporarily to reflect upgrade to the CAT (see emails).

Text should read:

Service Interruption: Saturday October 19, midnight to noon. [Learn more.](https://libraries.psu.edu/alerts)

@binkylush I don't know if you have any verbiage suggestions for the "Learn more"?

**Comment by ruthtillman** [comment]
In terms of timing, I think we could run this from Monday/Tuesday the 14/15th, so people get a heads up, until the following Sunday or Monday (depending on when we redeploy changes).

**Comment by banukutlu** [comment]
@ruthtillman Could you please update the announcement as you like here https://github.com/psu-libraries/psulib_blacklight/blob/master/config/locales/blacklight.en.yml#L7 and add a PR?

**Comment by ruthtillman** [comment]
Yes, I should be able to do it today or tomorrow.

**Comment by banukutlu** [comment]
> Yes, I should be able to do it today or tomorrow.

great, thanks. we can deploy it, as soon as we merge it.
