### ISSUE TITLE
Temporarily change Availability error message (deploy Friday 10/18?)

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#479]
During the upgrade on October 19th, the entire holdings/availability section won't load. During that period, the error message should be specific to the reason, rather than present it as a generic error.

Update
https://github.com/psu-libraries/psulib_blacklight/blob/2ab7b1bfd65551818121595a58a3bf7c27199cc7/app/javascript/psulib_blacklight/javascripts/availability.js#L548-L555

With the error message text:

```Required system maintenance is currently being performed. Availability and I Want It functions should be restored by noon October 19th. [See library alerts](https://libraries.psu.edu/alerts) for updates and details.```

We'll then need to revert this to the old error after the maintenance has been completed.

**Comment by cdmo** [comment]
How about we disable holdings and add just one error message to the top of the page? I just think it'd be better than displaying the same error so many times on the page and through the experience in the application. Thoughts?

**Comment by banukutlu** [comment]
> How about we disable holdings and add just one error message to the top of the page? I just think it'd be better than displaying the same error so many times on the page and through the experience in the application. Thoughts?

I liked this approach very much, what do you think @ruthtillman ?

**Comment by ruthtillman** [comment]
@banukutlu This is doable but only if we have someone, probably you or @cdmo, prepared to restore Blacklight as soon as that the system is working again (10am-noon Saturday). Because we can't just leave Availability turned off all weekend. The downside is the amount of work it would ask you to do outside of normal working hours. Thoughts? I may be available to chat details via Slack on and off today.

**Comment by banukutlu** [comment]
@ruthtillman sounds like you are fine with displaying one msg on top, cool 👍 
for the rest, we are thinking about our approach, we will let you know.

**Comment by banukutlu** [comment]
We will not display `Availability` and `I want It` during read-only and display the error msg on top under the search bar rather than displaying an error msg for each record.
