### ISSUE TITLE
Investigate / compare Favorites and alerts between Symphony and Blacklight.

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#48]
In GitLab by @rkt6 on Jun 20, 2018, 13:29

See what we can do with Favorite functionality in Blacklight/notifications.

Understanding how this is done in Symphony - Todd, Maryam (do we have stats?)

Understanding how this is done in Blacklight - Banu, Charlie

Connected to #71

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 20, 2018, 13:30

changed the description

**Comment by cdmo** [comment]
@ruthtillman are favorites the same thing as bookmarks?

also, aren't alerts something very different? shouldn't that be a separate issue?

@banukutlu and I also think this can be moved to mvp 2

**Comment by ruthtillman** [comment]
Banu asked me to review and I think short form would be:

1. implement bookmarks
2. consider updates/notifications as a future option.

**Comment by ruthtillman** [comment]
(we can use temporary bookmarks until My Account is implemented -- also updates/notifications would require My Account)

**Comment by banukutlu** [comment]
closing this to add as a two seperate issue
