### ISSUE TITLE
Search in other contexts / continue search in?

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#49]
https://github.com/psu-libraries/psulib_blacklight/wiki/Contextual-Links-and-Continue-Your-Search-In

Passes your search parameter to a few other places like WorldCat, etc.

LionSearch
WorldCat
EzBorrow
UBorrow
Google Scholar
Hathi Trust
Google Books

Also the following: Course Reserves, Find Articles, Materials Not At Penn State, Library Home Page and ASK!).

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 26, 2018, 10:21

changed the description

**Comment by banukutlu** [comment]
@ruthtillman can you add a wiki page for this, thanks!

**Comment by banukutlu** [comment]
@ruthtillman fyi, this haven't been deployed yet but I went ahead and displayed `continue search in` section when search results count < 3 (so for zero results as well). So after review, we can change that if needed.

**Comment by ruthtillman** [comment]
Seems deployed now. Everything except the UBorrow link is working fine: http://uborrow.relaisd2d.com/service-proxy/?command=mkauth&LS=PENNSTATE&PI=PENNSTATE&query=death 

I'm getting a timeout but it's also possible it's an issue with UBorrow. (note, I originally used a gibberish search but then after that timed out I redid the URL with a different query)

**Comment by ruthtillman** [comment]
Also not working in Bento.

**Comment by mkutch** [comment]
The UBorrow Link is now https://ub.relaisd2d.com/?LS=PENNSTATE&PI=PENNSTATE&query=

**Comment by ruthtillman** [comment]
Works right on QA site!
