### ISSUE TITLE
My Account integration with I want It

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#505]
pending https://github.com/psu-libraries/myaccount/issues/96

* AJAX or loaded request to my account (loaded being the referrer parameter)
* Make blackcat qa talk to myaccount qa, could do a config based/modular approach (pick your my account server kinda thing). But this is to enable complete end to end testing of the qa environment of blackcat and myaccount.

Aha! Link: https://penn-state-university-libraries.aha.io/features/STPROJ-18

**Comment by cdmo** [comment]
Can we close this Banu? It appears to be working and there's nothing for Ruth to review on this one.
