### ISSUE TITLE
Add Course Reserve Information to Availability

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#513]
Update Availability display to add `reserveCirculationRule` and `dueDate` fields for items which are on course reserve.

Basics: If `reserveCirculationRule` exists, display it so users know how long they can check it out + if it's checked out they'll know it's on course reserve. If `reserveCirculationRule` && `dueDate` exists, also display the due date so users know when to expect the book to become available again.

Documentation: https://github.com/psu-libraries/psulib_blacklight/wiki/Holdings-and-Availability-Display#item-info see reserveCirculationRule & dueDate as well as the mapping of rules to display messages.

Sample data: https://github.com/psu-libraries/psulib_blacklight/wiki/Holdings-and-Availability-Display#on-course-reserve-and-regular-shelf-sample-data

Aha! Link: https://penn-state-university-libraries.aha.io/features/STPROJ-17

**Comment by nicktiberi** [comment]
Updated sample data for this ticket from Ruth: https://github.com/psu-libraries/psulib_blacklight/wiki/Holdings-and-Availability-Display#course-reserve-sample-data

**Comment by ruthtillman** [comment]
Display of information looks good.

Found one checked out item on course reserve, which looked good. Waiting on Maryam to confirm some more catkeys. Also found a weird case which I'm going to run by Chris because it's data-related not a code issue.

**Comment by ruthtillman** [comment]
When displaying course reserve due date, add line due date with values from this list:

```yml
12WEEK: Circulates for 84 days
14DYNORENU: Circulates for 14 days with fees, no renewals
16WEEK: Circulates for 112 days
1WEEK: Circulates for 7 days, no renewals
22WEEK: Circulates for 154 days
24HOUR: Circulates for 24 hours with no fees
24HREQUIP: Circulates for 24 hrs, $1/hr fee, $100 max
24HRNORENU: Circulates for 24 hours, $3/hr fee, $15 max
28NORENU: Circulates for 28 days no renewals
28ONERENU: Circulates for 28 days with one renewal
2HOUR: Circulates for 2 hours with fees
3DAY: Circulates for 3 days
3DAYEQUIP: Equipment circulates for 3 days with $25/day fees
3DAYVIDEO: Video - Circulates for 3 days
45DAY: Circulates for 45 days
4DAY: Circulates for 4 days
4HOUREQUIP: Circulates for 4 hours
4WEEK: Circulates for 28 days, Community borrowers/Non-resident PA
4WKRESIDNT: Circulates for 28 days, Resident PA users
5DAYEQUIP: Equipment circulates for 5 days with $3/day overdue
7DAY: Circulates for 7 days
7DAYEQUIP: Equipment circulates for 7 days with $5/day overdue
8WEEK: Circulates for 56 days
FASTSEMEST: Circulates for a semester with unlimited renewals
ILLSP: Circulates for 14 days no renewals
LAPTOPPAT: Circulates for 7 days with fees, no renewals, no recalls 
NONCIRC-SC: Circulates for 9 hours no renewals
NONCIRC-Y: Circulates for 2 hours
RES-24HOUR: Reserve - 24 hour loan
RES-24HRTE: Reserve - 24 hour loan, no renewals, overdue fee, 2hr grace
RES-2HOUR: Reserve - 24 hour loan
RES-2HRRNW: Reserve - 24 hour loan w/ 1 renewal
RES-30MIN: Reserve - 30 minute loan
RES-4HOUR: Reserve - 4 hour loan
RES-5DAY: Reserve - 5 day loan
RES-6HOUR: Reserve - 6 hour loan
RES-7DAY: Reserve - 7 day loan
RES-OVERNT: Reserve - overnight loan
SEMESTER: Circulates for a semester
SEMSTRDISP: Circulates for a semester
VIDEO7DAY: 7 day loan, 8 renewals, can recall```

Let's not add a prefix to it for now.
