### ISSUE TITLE
Access Facet: Add Open Access status

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#528]
We have a strategic goal of furthering OA. We can add mappings for OA materials to our Access facet, though these will use different fields than currently populate the OA facet.

Basic logic is: IF 506$2 == `star` AND 856$7 == `0` THEN add Access == "Open Access"

See details: https://github.com/psu-libraries/psulib_blacklight/wiki/Open-Access-in-Access-Fields

Aha! Link: https://penn-state-university-libraries.aha.io/features/STPROJ-10

**Comment by cdmo** [comment]
So just want to make sure I am getting this right. Open Access will appear as an option in this facet?

![Screen Shot 2020-09-23 at 5 27 07 PM](https://user-images.githubusercontent.com/523381/94071534-0eae2d00-fdc2-11ea-8f44-c643b2c57b93.png)

**Comment by ruthtillman** [comment]
Yes. Because many of our online materials are paywalled, we want to flag those which we know to be open access. Also I need to review one thing re: logic, will ping Jeff E today.

**Comment by ruthtillman** [comment]
Update -- yes, this will cover everything we want to include in it!

**Comment by cdmo** [comment]
Closing this in lieu of https://github.com/psu-libraries/psulib_traject/issues/245
