### ISSUE TITLE
Review how other libraries indicate e-journals/refine access button?

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#535]
While visible in search results, the access online url can be a little subdued. Librarian doing instruction reports a lot of students needing it pointed out to them on full record pages. Review how other libraries are doing this/user test? (possibly limit just to e-journals?)

This is an example in which the link to Additional Creators overwhelms the link to access: https://catalog.libraries.psu.edu/catalog/28720498

**Comment by banukutlu** [comment]
Closing this since Access Online links have been refactored by other issues.
