### ISSUE TITLE
Link series titles in records

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#537]
From INC1330925

Request from a faculty member:

> Could the series title in a record be hyperlinked?

>  Contemporary World Issues is one example. Here's a book in that series: https://catalog.libraries.psu.edu/catalog/1756047 [https://catalog.libraries.psu.edu/catalog/1756047] The name of the series is listed in the record, but isn't hyperlinked

Here's where that could be linked to:

https://catalog.libraries.psu.edu/catalog?utf8=%E2%9C%93&op=AND&all_fields=&title=&author=&subject=&identifiers=&series=%22Contemporary+world+issues%22&publisher=&range%5Bpub_date_itsi%5D%5Bbegin%5D=&range%5Bpub_date_itsi%5D%5Bend%5D=&sort=score+desc%2C+pub_date_itsi+desc%2C+title_sort+asc&search_field=advanced&commit=Search

**Comment by ruthtillman** [comment]
Also to note: we only want to link the series title, which is in the subfield a. Sometimes the field contain, understandably, the number of item in the series, e.g. Practical Guides for Librarians |v 231. Sometimes it also contains the ISSN or such for an established/connected series if relevant, e.g. https://catalog.libraries.psu.edu/catalog/28317732/marc_view

By focusing just on the "a" we should be ok. (this is essentially a note to check indexing and determine whether we need to do anything else with it)
