### ISSUE TITLE
HathiTrust integration

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#54]
Integrate HathiTrust access into the Blacklight Catalog.

## HathiTrust ETAS

While ETAS is active, we will query the HathiTrust bibliographic API. If the item is available via ETAS, we will:
- link to ETAS checkout and force the user through validation if needed
- with text "Check out digital copy from HathiTrust" (subject to changes by admin)
- and display HathiTrust logo next to the link.

API documentation is available at: https://github.com/psu-libraries/psulib_blacklight/wiki/Google-Books-and-HathiTrust-Integration-Links & https://www.hathitrust.org/bib_api

Mockup images are available in:
https://psu.app.box.com/folder/74509861960 though logo image could be on right or left.

HathiTrust logos are available https://www.hathitrust.org/documents/hathitrust_logos.eps 

## Differentiating Search Inside and Full Text

Once ETAS is ended, we will need to differentiate between search inside and full text records. These can be determined using the API response. Field: `usRightsString:`  value: `Limited (search only)` or `Full View`

Example 1 partial-text: Title: `Colonial interiors. second series` OCLC # `2628707` and HathiTrust link goes to https://catalog.hathitrust.org/Record/000411343#accessLinks

Example 2 full-text: Title: `Farmers' institutes in Pennsylvania to be held under the auspices of the Pennsylvania Department of Agriculture.` OCLC # `40314611` and HathiTrust link goes to https://catalog.hathitrust.org/Record/012294353#accessLinks

![hathitrustexample1](https://user-images.githubusercontent.com/6477867/46040699-093c8000-c0df-11e8-8acf-e726ff406e97.png)

![hathitrustexample2](https://user-images.githubusercontent.com/6477867/46040704-0cd00700-c0df-11e8-880c-fa03b46822f7.png)

Aha! Link: https://penn-state-university-libraries.aha.io/features/STPROJ-65

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 21, 2018, 15:38

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 21, 2018, 15:38

removed assignee

**Comment by ruthtillman** [comment]
@mkutch could you document the API as it's being used in the Cat?

**Comment by ruthtillman** [comment]
Change explainer text in record to:

`By special arrangement in response to the COVID-19 pandemic, patrons may access this resource online through the HathiTrust Emergency Temporary Access Service.`

**Comment by cdmo** [comment]
This is in production, closing
