### ISSUE TITLE
Google Books integration / preview

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#55]
Determine whether we integrate Google Books (or Open Library), including its preview links.

Example 1 partial-text: Title: `Colonial interiors. second series` OCLC # `2628707` and Google Books link goes to https://books.google.com/books?id=RvQ8AAAAYAAJ&source=gbs_ViewAPI

Example 2 full-text: Title: `Farmers' institutes in Pennsylvania to be held under the auspices of the Pennsylvania Department of Agriculture.` OCLC # `40314611` and Google Books link goes to: https://books.google.com/books?id=1Qg2AQAAMAAJ&printsec=frontcover&source=gbs_ViewAPI#v=onepage&q&f=false

The examples and screenshots are the same as for Issue #54 and example 2 on Google Books is our copy.

![hathitrustexample1](https://user-images.githubusercontent.com/6477867/46040583-b662c880-c0de-11e8-851e-3027b222ae93.png)

![hathitrustexample2](https://user-images.githubusercontent.com/6477867/46040585-b9f64f80-c0de-11e8-8a78-72488e0f6c3a.png)

We could also try the OpenLibrary API which is allows for search inside -- or query that first. https://openlibrary.org/dev/docs/api/books

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 21, 2018, 15:40

changed the description

**Comment by ruthtillman** [comment]
Note: Google Books, we'll want to test whether the book can actually be searched inside/previewed or not.

Do we want to do some kind of assessment test of something like OpenLibrary to see how much we can get from there? I won't be meeting with Ellysa until the 15th however to talk about how usable that is

**Comment by ajkiessl** [comment]
https://developers.google.com/books/docs/v1/using#download-format

**Comment by ajkiessl** [comment]
Ok, so it looks like Google has a concise API used specifically for linking to previews: https://developers.google.com/books/docs/dynamic-links?csw=1

You can search using these params:

ISBN
    &bibkeys=ISBN:0451526538 (The API supports both ISBN 10 and 13.)
OCLC
    &bibkeys=OCLC:36792831
LCCN
    &bibkeys=LCCN:96072233

The "preview" element in the returned JSONwill tell us if a preview exists.  This value can be "full", "partial", or "noview".
The preview url (if one exists) can be pulled from the "preview_url" element in the JSON.

 It does not require an API key.

**Comment by ruthtillman** [comment]
order of priority: LCCN, OCLC, ISBN

in theory LCCN is the most likely to be actually unique but all of them can get tangled up in Google Books /deep sigh.

**Comment by ruthtillman** [comment]
Looking at Google Books, the classic link looks like: 

https://books.google.com/books?id=vZAyEAAAQBAJ

whereas the new link looks like:

https://www.google.com/books/edition/The_Doomsday_Machine/vZAyEAAAQBAJ

-- is it possible to get the new form of the URL from the API? It's quite possible that it's not -- the new form has the additional title segment that we can't replicate unless it happens to be in the API response.

**Comment by ajkiessl** [comment]
I don't think that it is possible.  Even the full API output only returns preview urls that have the old syntax.  For example: 

https://www.googleapis.com/books/v1/volumes?q=oclc:40314611&filter=partial

In fact, any of the fields that return a url returns them with the old syntax: `https://books.google.com/books?`

Not sure why that is.  The old style links do redirect to the new urls, though.

**Comment by ruthtillman** [comment]
Thanks @ajkiessl - that's fine, I was just hoping there might be an option. And one can search inside at either.

Other thoughts from review:

1. This is looking really good!
2. Would it be possible to remove it when an item has Access: Free to Read? Sample record: https://catalog.qa.k8s.libraries.psu.edu/catalog/27685626
  For now I think we'll leave it on for online items since they may be found by a person who doesn't have institutional access (via google) or, given how hard academic ebooks are to use -- there's a use case for just quickly previewing/searching inside.
3. @binkylush I think you're back tomorrow -- any thoughts on the language of the label? We used to say "Preview" but might "Search inside at Google Books" be more the direction in which we want to point users?

**Comment by ruthtillman** [comment]
Logic clarification:

show the google preview if exists UNLESS there's a HathiTrust box already there or the item has the access facet: free to read.

**Comment by ruthtillman** [comment]
Text update: "Search inside at Google Books"
