### ISSUE TITLE
Develop useful CAT and Blacklight searches for Regression Testing

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#56]
In GitLab by @rkt6 on Jun 21, 2018, 14:57

https://psu.app.box.com/notes/347333927582

Required by #206

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 21, 2018, 15:24

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 21, 2018, 15:43

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 11, 2018, 12:05

changed the description

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 12, 2018, 09:45

:hearts: this, searches are super helpful for tire kicking

**Comment by cdmo** [comment]
https://github.com/tulibraries/tul_cob/tree/master/spec/relevance
