### ISSUE TITLE
Display "digital bookplates" (just text for now) and dedications

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#57]
Ruth updated 2021-11-16 with current practices and mapping so things below may apply less. We will currently not display actual digital bookplates, but the data we're creating through indexing will let us create image bookplates/enhanced search/however we want to do it. See the wiki https://github.com/psu-libraries/psulib_blacklight/wiki/Endowments-and-Dedications for big picture and https://github.com/psu-libraries/psulib_traject/issues/12 for indexing.

## Digital Bookplates

Digital Bookplates should be displayed as follows (pseudocode):

```
Acquired with generous support from the {link to controlled search for {link to controlled search for 993a}{993n}{/link}
```

We currently don't use a label for them and don't seem to for now. These may repeat and should be _displayed on separate lines_.

Note that the book _may or may not_ have a similar 541 field, e.g. https://catalog.libraries.psu.edu/catalog/4322824 but the number is different than in the endowments link above.

## Dedications

These may repeat and should be _displayed on separate lines_.

| label | value |
| Dedication | 995a |

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 26, 2018, 10:34

changed the description

**Comment by banukutlu** [comment]
Would this be part of initial release?

**Comment by banukutlu** [comment]
more of indexing and displaying

**Comment by banukutlu** [comment]
look at Stanford's donor work

**Comment by mkutch** [comment]
Making a note here of examples of records with more than one Bookplate for a record at Stanford library. Looks like they have the fund info at the bib level (979 field).

- https://searchworks.stanford.edu/view/3087242

- https://searchworks.stanford.edu/view/6727193

**Comment by mkutch** [comment]
Currently, we display them in the CAT by searching for the fund that was used to purchase the item (for all items in the cat record). In other words, for every item in the holdings, we look up the fund used to purchase it and if it is an endowed fund, we display the link to the digital bookplate.

**Comment by cdmo** [comment]
@mkutch 979b is the magic that makes a [page like this](https://searchworks.stanford.edu/catalog?f%5Bfund_facet%5D%5B%5D=mn446rd9503&sort=new-to-libs&view=gallery) work.

The decoded route for Blacklight is 

`/catalog?f[fund_facet][]=mn446rd9503&sort=new-to-libs&view=gallery`

So:

Fund facet = mn446rd9503 (979b "druid:")
Sort = "new to libs" (what the library has acquired most recently displayed first)
View = Gallery

```
f| CRARYG b| druid:hm051nv6365 c| hm051nv6365_00_0001.jp2 d| Gordon B. and Mary L. Crary Endowed Book Fund 
```
