### ISSUE TITLE
access online display bug

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#579]
kinda aligned right weirdly, thanks @ruthtillman for finding this
![Screen Shot 2020-05-28 at 9 49 28 AM](https://user-images.githubusercontent.com/523381/83149824-901dd900-a0c8-11ea-9996-eb3faa58fb62.png)

**Comment by cdmo** [comment]
@ruthtillman this can be reviewed on QA

**Comment by ruthtillman** [comment]
Fix looks good! Thank you.
