### ISSUE TITLE
Announcement bar

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#58]
In GitLab by @rkt6 on Jun 26, 2018, 10:18

To note downtime, freezes, new features, roadmap link when it's in beta.

**Comment by cdmo** [comment]
@ruthtillman we'll need some text for this, of course.

**Comment by ruthtillman** [comment]
`Welcome to the new Penn State Libraries Catalog. [Learn more] about the project, [submit feedback] on your experience, or switch to the [classic Cat].` ?

(with appropriate links)

**Comment by cdmo** [comment]
I'll put it in, we'll take a look. I worry it might be a bit long, but let's see

**Comment by ruthtillman** [comment]
Current draft looks good.
