### ISSUE TITLE
HathiTrust links

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#585]
Requires https://github.com/psu-libraries/psulib_traject/issues/204 first

Per record, create a link direct to HathiTrust catalog record or scanned item with appropriate text accompanying

Use https://github.com/psu-libraries/psulib_blacklight/wiki/Google-Books-and-HathiTrust-Integration-Links#enhancement-splitting-hathitrust-etas-and-public-domain for requirements

## Include on/off toggle in `Settings`

When on: etas links for denies
When off: denies become "search inside" links at the record view and nothing shows for denies at the index view

## Link logic

```
allow + mono = link to scan with Access digital copy through HathiTrust
allow + multi = link to catalog record page with Access digital copy through HathiTrust
deny + mono = link to scan with ETAS
deny + multi = link to catalog record in ht with ETAS
```

**Comment by cdmo** [comment]
@ruthtillman I think I'm not yet clear on what exactly we're trying to do with the records in the overlap report that have the value "allow" in the "access" field (i.e., our "full view forever" items). I've looked at a couple records in the CAT that show up in the overlap report, for example:

*The township geology of Elk and Forest counties*...
https://cat.libraries.psu.edu/uhtbin/cgisirsi/x/0/0/57/5/0?searchdata1=1000103%7BCKEY%7D&searchfield1=GENERAL%5ESUBJECT%5EGENERAL%5E%5E&user_id=WEBSERVER

This item is in the overlap report as access:allow. It is also in HT: https://catalog.hathitrust.org/Record/007043464?type%5B%5D=all&lookfor%5B%5D=318366827&ft= (you can see the scan came from us).

Our record view in the CAT there is only a "Check out digital copy through HathiTrust" link that goes straight to the Hathi reader for that item. That language, to me, doesn't make a ton of sense seeing as how you don't need to check the book out, you can just read it straight away. Did we land on how we wanted to treat this link in the catalog? I think at this point given that we are even more explicitly telling patrons that the link is something they are checking out because of ETAS in the catalog, and because we've already got the data at the ready, I'm thinking that it'd be better user experience to just create a different treatment for full-text-always links. Something like "[HT logo] Access online throught HathiTrust."

Obviously we'd also want to make sure these items populate the "Online" value in the "Access" facet. Right now they don't seem too, that record mentioned above does not. But still kind blurry in my mind how we want the text/link to display. I know this was talked about at the last check in meeting but probably because of my being distracted by troubleshooting my dark MacBook I missed it 🙃.

**Comment by cdmo** [comment]
talked this through on Slack, read through https://github.com/psu-libraries/psulib_blacklight/wiki/Google-Books-and-HathiTrust-Integration-Links#enhancement-splitting-hathitrust-etas-and-public-domain. Think we're good now.

**Comment by banukutlu** [comment]
> allow + mono = link to scan with Access digital copy through HathiTrust
> allow + multi = link to catalog record page with Access digital copy through HathiTrust
> deny + mono = link to scan with ETAS
> deny + multi = link to catalog record in ht with ETAS

**Comment by banukutlu** [comment]
Thought I'd share some example catkeys I used when testing locally, maybe will helpful for you @ruthtillman while reviewing this work:

```
1077157 - ht_bib_key:000641127, access:allow
2251805 - ht_bib_key: 004144147, access:deny
2319014 - ht_id: mdp.39015047932549, access:deny
1742314 - ht_id: uc1.31210012674238, access:allow
```

**Comment by ruthtillman** [comment]
Tested the on/off with @cdmo this morning and it all behaved as expected!
