### ISSUE TITLE
Display a message for Availability when WebServices is not available

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#59]
In GitLab by @rkt6 on Jun 26, 2018, 10:23

If we cannot talk to the WebServices or we need to point the WebServices at the test server, we should be able to do so without breaking Blacklight's display/usability (beyond what's necessary).

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 4, 2018, 10:13

Note: this must be part of the first milestone to use interactive Web Services.

**Comment by banukutlu** [comment]
this is for when integrating WebServices

**Comment by banukutlu** [comment]
> if for any reason `WebServices` is not available, we need the site to be able to gracefully display a error message for `availability`. also think about `I want It` functionality as well.

@ruthtillman what is the text of the message to display in this case?

**Comment by ruthtillman** [comment]
@banukutlu first draft is here: https://github.com/psu-libraries/psulib_blacklight/wiki/Holdings-and-Availability-Display#error-message-when-webservices-not-available
