### ISSUE TITLE
Suppress/hide "I want it" button on records that have the Hathi ETAS 

### ISSUE THREAD

**Issue by mkutch** [psu-libraries/psulib_blacklight#594]
Request from Chris Holobar -

 Is there a way that, after we turn I Want It back on, we can suppress/hide it on records that have the Hathi ETA (Emergency Temporary Access) full-text?  I expect to have some of our staff back on-site sometime after July 4, with some pickup service available late July/early August. At that point we'd need to turn I Want It back on, but, to continue our access to the full-text Hathi ETA materials, we'd need to exclude them from I Want It, ideally at the CAT record. So, mid-late July?

**Comment by cdmo** [comment]
Thanks for passing along @mkutch 👍

**Comment by cdmo** [comment]
@ruthtillman did you see this?

**Comment by ruthtillman** [comment]
When I first saw this, I thought that for making it also work in The CAT, it would be something that needed to be addressed by something on @mkutch's end, like all items in all records matched in our spreadsheets get moved to a temporary, unavailable location. That would then automatically affect whether or not our I Want It button shows, same as https://catalog.libraries.psu.edu/catalog/2308333 and such work under normal conditions.

@mkutch -- does that align with how you're thinking of handling it?

If not, then we need to prioritize this ticket in upcoming work. Perhaps by detecting the presence of `hathitrust_struct` in the search result and not displaying the I Want It button if it's present? That seems fairly reversable... we could just remove the test later on. Does that make sense? Are there other ways folks can think of to do it? @cdmo @banukutlu.

**Comment by cdmo** [comment]
I think what we'd do is just add a check on whether or not etas is on - which is a config we store in the application's state via yaml.

**Comment by ruthtillman** [comment]
@cdmo and also check if there is hathitrust data associated with that record? Because it seems like we will be turning on the I Want It button (at the Symphony result level) for items which aren't in ETAS so people can do pickup.

**Comment by banukutlu** [comment]
@ruthtillman does it matter if the record is public domain or etas? should it be hidden for any records with hathi data?

**Comment by ruthtillman** [comment]
@banukutlu we only want to hide "deny" equivalent records.

**Comment by cdmo** [comment]
@ruthtillman this is on QA and ready for your review. I've changed the state of the catalog such that ETAS is on and holds are allowed for holdable items. I want it should only show up for non-ETAS items. Appears to be working to me.

**Comment by ruthtillman** [comment]
Reviewed and QAd using search https://blackcat01qa.libraries.psu.edu/?f%5Baccess_facet%5D%5B%5D=In+the+Library&q=human+aspects+of+library+automation&search_field=all_fields which includes items which are public domain and holdable, as well as items which are not in HathiTrust but also are not holdable... etc. Required checking the WebService responses to be sure that the books without I Want It were indeed not holdable, but everything is behaving correctly! 👍
