### ISSUE TITLE
Matomo integrated via webpacker

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#596]
See https://github.com/psu-stewardship/scholarsphere-4/pull/383

Better organized and more consistent code. Should probably see if we can do the same with ask a librarian widget code.

**Comment by awead** [comment]
@cdmo You can see my previous attempt here: https://github.com/psu-stewardship/scholarsphere-4/commit/1dcabc7ac7f43bb677309efed7534ffddda0f1b8

I don't think this would have worked because the ENV variables are determined at _compile_ time and not runtime.

**Comment by cdmo** [comment]
Hm. I'm probably missing something but I'd think both approaches would be viable. Like when the assets are compiled the environment variable would be there and be the same as what it would be at runtime. Trying to think why the environment variables would be different at compile versus runtime.
