### ISSUE TITLE
My Library Account

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#6]
In GitLab by @ful105 on Feb 21, 2018, 15:23

Assess account-specific functions available (e.g. Update Address), Renewal/Renew-ALL functions, Fines (is there any way to do better info about payment? -- do we gently persist this data?), Links to: borrowing privileges page, questions about library account page, and privacy policy (should be everywhere)

Bills!

--

Documenting what's currently in My Account and what functions/features we'll need: https://github.com/psu-libraries/psulib_blacklight/wiki/My-Account-Components

**Comment by banukutlu** [comment]
What do we expect to have done for initial release?

**Comment by banukutlu** [comment]
yes part of the initial release

**Comment by ruthtillman** [comment]
Closing because we are moving these to individual tickets.
