### ISSUE TITLE
Test cat backup

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#60]
In GitLab by @rkt6 on Jun 26, 2018, 10:25

Run a backup copy of the cat which points at Test CAT. See also #59.

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 26, 2018, 10:25

changed the description

**Comment by cdmo** [comment]
I am not sure what this issue means. "Run a copy of the cat"?
