### ISSUE TITLE
Ask a librarian does not show on /bookmarks when there are bookmarks

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#608]
works when there are no bookmarks

**Comment by cdmo** [comment]
Important note: only when viewing `/bookmarks` - right?

**Comment by banukutlu** [comment]
> Important note: only when viewing `/bookmarks` - right?

yes!

**Comment by ruthtillman** [comment]
looks good!

**Comment by banukutlu** [comment]
Reopening this since changes for #1037 broke this again, need to be revisited.
