### ISSUE TITLE
No Recalls

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#609]
To support the strategic plan's no-recalls work, develop logic for the "I Want It" button which directs users to a page which places the hold via ILLiad vs Symphony.

If the item has holdable:true, then we need to test:

 1. Are all items in ILL locations aka: https://github.com/psu-libraries/psulib_blacklight/blob/main/app/javascript/availability/libraries_locations.json#L780-L794
    - yes: trigger No Recalls
    - no: go to 2
2. Are items that are NOT checked out in non-holdable locations:
    - yes: trigger No Recalls
    - no: allow normal hold placement through Symphony.

We will need to figure out volumetrics.

Fuller logic and use cases are spelled out in the [No Recalls Logic](https://github.com/psu-libraries/psulib_blacklight/wiki/No-Recalls-Logic) page in our Wiki. Includes sample catkeys for the possible use cases and info on where to find copies of the WebServices results for those sample records (since checking in and out items will alter whether these are good samples, we can use static results/manipulate our own data on stage).

## WDDLL

- [x] If a record _normally_ contains holdable items but none can be checked out at this time, a user clicking "I Want It" goes to a page on My Account which places the hold in ILLiad vs. in the Catalog.
- [x] If the above but the user is a community borrower/PA borrower, they still get redirected to normal My Account holds page, where they will place a non-recalling hold.

**Comment by ruthtillman** [comment]
History:

Access Services emailed in August 2020 with the following requirements:

> To enhance our service to borrowers, we want to eliminate the automated
> recall process in Symphony. Specifically:
> 
>     The I Want It button will remain in the catalog for borrowers to place holds.
>     Holds on available copies will continue to be processed as usual.
>     If no copies are available, Symphony will no longer recall a checked-out copy, but will automatically populate a request in Illiad for the borrower requesting the hold.
> 
> Strategic Plan:
> 
>     Discovery Access and Preservation
>     Equity of Access
>     Empathy
>     Priority: High- High impact on users or operations
>     More information? This was discussed and approved by Access Services Council

We had a meeting about this on May 27 as well with Chris H and Meg M.
