### ISSUE TITLE
Previous/next session based 

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#611]
From INC1493779

Parent issue https://github.com/projectblacklight/blacklight/issues/2295

**Comment by cdmo** [comment]
@ruthtillman this is ready for review on QA. Do a search with some number of results, click a result, copy the URL, open new tab and paste it in: the previous/next links should not be there. In the production catalog they would be.

**Comment by ruthtillman** [comment]
Testing:
1. Original container: If I am in the Firefox container in which the search was performed, no matter how many new tabs I open and paste in the URL, I still DO see prev/next. Those prev/next do work for that original search.
2. New container: If I go paste the URL in a new tab in a new container, I DO NOT see prev/next.
3. Original container after viewing unrelated record: If I go to a completely unrelated record in Blackcat in the original container by pasting in a known URL, I DO NOT see prev/next. If I THEN paste in the original URL after viewing the unrelated record, I DO NOT see prev/next.
4. Original container after viewing _related_ record: If I page through results then _paste_ in the URL of the result in which I'm interested (vs. paging back to it), I DO NOT see prev/next.

Assessment: This addresses the concern. Prev/Next are **not** persisting after you've looked at another record, only if you return to one you were looking at earlier without looking at any other record in the interim (and I would guess there's probably also an expiration on that, but I don't have a few days to let it go stale).

**Comment by cdmo** [comment]
Yep, my scenario that I asked to be tested actually fails. What passes is now is that if you:

1. Do a search
1. Click on a result -> the page will have a prev/next link set
1. Go directly in a new tab _any_ other catalog record -> this won't have any prev/next toggle

In the catalog production right now:

1. Do a search
1. Click on a result -> the page will have a prev/next link set
1. Go directly in a new tab _any_ other catalog record -> this will have the same prev/next link as the item 2

So this problem is in _better_ shape for sure, but not fix entirely.

**Comment by ruthtillman** [comment]
Yes, and it's not entirely a bug to put people back in their earlier session/search as long as we're not doing it completely randomly like it currently is. It's... an ambiguous feature 😅 . So I am ok to go ahead with this.

**Comment by cdmo** [comment]
Yes the current craziness of the prev/next on stale sessions is almost completely fixed for sure. We'll deploy it up to prod and think about solving this last scenario another time. Thanks
