### ISSUE TITLE
Sinatra for web service responses in feature specs

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#631]
Would like us to do this so we don't have to play whack a mole with flakey specs that change depending on the status of the real live holding data

**Comment by cdmo** [comment]
Kinda curious - are you also moving the availability js work into a rails controller? I am not sure sinatra would work unless we did that because the web service requests come from the browser right? Just wondering the size of this issue - it might be big.

**Comment by nicktiberi** [comment]
@banukutlu - I think we can close this since we are using VCR to mock the availability responses. Do you agree?
