### ISSUE TITLE
Update CHECKEDOUT location description and link to ILLiad

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#632]
> ~RESERVE-EM and RESERVE-EG both have the following description - Unavailable for checkout, request pages via ILLiad~ (see #636 )
> 
> And CHECKEDOUT has a new description - Unavailable for checkout, request through Interlibrary Loan
> 
> Can we have ILLiad and Interlibrary Loan both link in the cat/catalog to Illiad?
> 
> Thanks!
> 
> Chris Holobar

**Comment by banukutlu** [comment]
some examples for testing:

```
RESERVE-EG - catkey 1056505
RESERVE-EM - catkey 78798
CHECKEDOUT - see catkey 261, 107943, 108540
```

**Comment by banukutlu** [comment]
URL for EG/EM reserve scans `https://psu-illiad-oclc-org.ezaccess.libraries.psu.edu/illiad/upm/illiad.dll?Action=10&Form=30&Genre=GenericRequestReserves`

**Comment by banukutlu** [comment]
>Just want to confirm the final language and linking for these locations:
>
>RESERVE-EM and RESERVE-EG both have the following description - Unavailable for checkout, request a chapter (link to ILLiad scan/chapter request form)
>
>CHECKEDOUT has a new description - Checked out, request through Interlibrary Loan (link to ILLiad book/loan request form)
>
>Thanks!
>
>Chris Holobar

**Comment by ruthtillman** [comment]
QAd. Looks good.
