### ISSUE TITLE
#render_facet_limit deprecation warning

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#655]
`DEPRECATION WARNING: Calling #render_facet_limit on a non-componentized facet is deprecated and will be removed in Blacklight 8. (called from block in render_facet_partials at /data/websites/psulib_blacklight/vendor/bundle/ruby/2.6.0/gems/blacklight-7.10.0/app/helpers/blacklight/facets_helper_behavior.rb:49)`

**Comment by cdmo** [comment]
latest release from project blacklight eliminates this warning, but adds many new ones that need to be addressed

**Comment by banukutlu** [comment]
seemed to be handled by #723
