### ISSUE TITLE
Previous/next stale edge scenario

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#657]
Upshot from #611 

The last piece not solved is: If I was in the catalog, did a search and clicked on a result it'd have some kind of prev/next. If later in the same browser (never closed the browser entirely) and I did a search from Bento and happened to click on the same exact record, the prev/next links would be the same as what they were before.

**Comment by ruthtillman** [comment]
https://github.com/psu-libraries/psulib_blacklight/issues/880
