### ISSUE TITLE
HATHIETAS item type

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#658]
We added a new item type to support ETAS. Add: `HATHIETAS` with label `HathiTrust Emergency Temporary Access` to `app/javascript/availability/item_types.json` 

It is also used in `psulib_traject/lib/translation_maps/bound_in.properties` which should be reviewed, but this is not the most helpful label to use there. We just need it not to break when indexing bound-in.

**Comment by ruthtillman** [comment]
@cdmo reviewed bound in and this will not break the indexing, it will just skip that field. Since an ETAS value would not be helpful in that field (we use it to disambiguate Book vs. Microformats), skipping is the preferred choice.

**Comment by cdmo** [comment]
@banukutlu did catch one small thing - that an empty parenthesis will be present in skipped bound-in formats. We'll fix that asap.

**Comment by cdmo** [comment]
This is tangentially related, but, when the `949t` changed to `ONLINE` for any record that previously had `ARCHIVES`, `INSTR-MATL`, `JUVENILEBK`, `REPORTER` or `STATUTE` will _potentially_ have lost it's correct format. For example [Chrostwaite's Pennsylvania municipal law reporter](https://catalog.libraries.psu.edu/catalog/151287) now is a "Journal/Periodical" where before the presence of `REPORTER` would have dictated the format "Reporter". This means it is displaying "incorrectly" and won't be part of the Format > Reporter faceting. Just wanted to spell this out for my own understanding. Hoping it'll revert back to what it was when ETAS is done.

**Comment by ruthtillman** [comment]
Yes, the 949t will revert when Maryam reverts things. And then indexing will work correctly again.

**Comment by cdmo** [comment]
Confirming that this is working in production
![Screen Shot 2020-09-28 at 9 30 20 AM](https://user-images.githubusercontent.com/523381/94438531-3cea8e80-016d-11eb-80b9-7ed2f04face8.png)
