### ISSUE TITLE
Add display for fields 255, 775, and 793

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#665]
See https://github.com/psu-libraries/psulib_traject/issues/244 for indexing.

Their locations for display are here: https://github.com/psu-libraries/psulib_blacklight/wiki/Blacklight-Catalog-Fields with temporary notes dated 2020-09-22 to make them easy to find.

Note: link 793 display to a keyword quote search for the term. e.g. "Allison Shelley"

**Comment by cdmo** [comment]
@ruthtillman regarding

> Note: link 793 display to a keyword quote search for the term. e.g. "Allison Shelley"

What are we expecting with the results? I assume that https://catalog.libraries.psu.edu/?search_field=all_fields&q=%22Allison+Shelley%22 is not good enough but I wanted to confirm. This search will find all sorts of matches including those records that have a collection matching "Allison Shelley" but any other record that matches "Allison Shelley" based on that phrase appearing elsewhere. Maybe this is ok? Or would we rather be more restrictive about the search (i.e., specifying that field only)

**Comment by ruthtillman** [comment]
It should be ok. Allison Shelley is quite a large collection. Let's start with that and I'll test it to see if we need to refine -- unless it's easier to just do the more restrictive linking.

**Comment by cdmo** [comment]
I made the collection a hidden facet, much like how we treat authors.

**Comment by ruthtillman** [comment]
These all look good!
