### ISSUE TITLE
Document how sample marc data is updated, how fixtures are updated. Also, generate fixtures appears to be not working

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#666]
```
➜  psulib_blacklight git:(master) ✗ bundle exec blackcat:traject:generate_fixtures
bundler: command not found: blackcat:traject:generate_fixtures
Install missing gem executables with `bundle install`
```

not sure what's up here yet, just recording the problem

We need some docs I think too, I am not finding anything.

**Comment by banukutlu** [comment]
I think this is the cmd `bundle exec rake blackcat:traject:create_fixtures`, it worked for me 🤔

**Comment by cdmo** [comment]
Ah dumb me I was using the wrong command! I was using a command in my bash history I found, don't know why it was there!

Anyway, using the right command,  now I am getting the following:

```
➜  psulib_blacklight git:(scan_sim-addition) bundle exec rails blackcat:traject:create_fixtures
[DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env` (called at /Users/cdm32/Projects/ruby/psulib_blacklight/lib/tasks/blackcat.rake:33)
Could not find chronic-0.10.2 in any of the sources
Run `bundle install` to install missing gems.
```

The `psulib_traject` app is bundle up-to-date'd.

So, is it possible to add to `sample_psucat.mrc`? Or how does that get modified? Let's say I want to add a few OA access examples. How would I go about that? MarcEdit?

Also, why do we deindex at the beginning of the `create_fixtures` task? I think that can be removed, but maybe I'm not understanding what's going on. Seems like it has nothing to do with creating/generating fixtures? 🤔

**Comment by banukutlu** [comment]
> Ah dumb me I was using the wrong command! I was using a command in my bash history I found, don't know why it was there!
> 

No worries, I think it was named liked that at some point and we changed.

> Anyway, using the right command, now I am getting the following:
> 
> ```
> ➜  psulib_blacklight git:(scan_sim-addition) bundle exec rails blackcat:traject:create_fixtures
> [DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env` (called at /Users/cdm32/Projects/ruby/psulib_blacklight/lib/tasks/blackcat.rake:33)
> Could not find chronic-0.10.2 in any of the sources
> Run `bundle install` to install missing gems.
> ```
> 
> The `psulib_traject` app is bundle up-to-date'd.
> 
Oh interesting, I am not getting this 🤔 

> So, is it possible to add to `sample_psucat.mrc`? Or how does that get modified? Let's say I want to add a few OA access examples. How would I go about that? MarcEdit?
> 
We generally asked Maryam to make an extract for the sample file when we wanted a change. If we want new records in, we can ask her.
Maybe we can edit it with MarcEdit as well but I haven't tried that yet. I use it for spec fixtures though, could work.

> Also, why do we deindex at the beginning of the `create_fixtures` task? I think that can be removed, but maybe I'm not understanding what's going on. Seems like it has nothing to do with creating/generating fixtures? 🤔

Yeah we might be able to get rid of that, I think it might be a leftover from before using Traject::JsonWriter?

**Comment by cdmo** [comment]
Ah ok, so yeah lets get rid of the emptying out of the solr index for sure ✅ 

I'll ping Maryam on Slack regarding modifying the source marc. ✅ 

No clue about why that command isn't working. But it is a brittle command to try and switch directories into another project and run a bundle command. Feels like a lot could go wrong. No, I don't have a better alternative :-) ❌

**Comment by cdmo** [comment]
I think I'll just plan on running the command myself in terminal when the rake task fails 🤷
