### ISSUE TITLE
How to run the core BL tests

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#67]
In GitLab by @ful105 on Jul 17, 2018, 14:24

https://github.com/projectblacklight/blacklight/wiki/testing

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 18, 2018, 09:53

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 17, 2018, 10:31

closing this since during the BL Summit we learned that others are not running core BL tests only tests for their custom work.

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 17, 2018, 10:31

closed

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Aug 17, 2018, 16:29

I don't know. I'd still like to know how that's done... Can we leave it open and remove the milestone?

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 20, 2018, 12:00

reopened

**Comment by cdmo** [comment]
I don't think this issue requires a milestone, can we remove mvp0?

**Comment by cdmo** [comment]
Maybe we should close this because we know how to do this now? And we did it already?
