### ISSUE TITLE
Review/revise link display to online content

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#672]
Requires https://github.com/psu-libraries/psulib_traject/issues/277
- [x] Links to our digital collections should be cool and more prominent kind of like HathiTrust
- [x] Links to general online content should overall be more eye-catching and grab the user better.

**Comment by ruthtillman** [comment]
1) Ruth, to-do create Traject ticket for the display label of 856.

2) Ruth, review other institutions' catalogs for online links.

**Comment by ruthtillman** [comment]
We'll be indexing link labels and notes IF they exist. Their use should be as follows:

1. No link label, no link note: use MVP default of displaying the domain.
2. Link label, no link note: use link label.
3. No link label, link note: use MVP default of displaying the domain, followed by the link note.
4. Link label, link note: use link label as label for link, follow with link note.

**Comment by ruthtillman** [comment]
(in progress)

## Display for Ordinary Links:

See comment above for the label/note aspects.

### Search Results 

Display "single record label" text within blue box a la (Online in these results) https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=Late+Soviet+Posters 

### Record display field

[let's look at the best way to display this? maybe just a slightly nicer version of this display? https://catalog.princeton.edu/catalog/11698380 or this https://searchworks.stanford.edu/view/13797514 ? ]

## Display for our Digital Collections:

- Blue box
- Box title: View in Penn State Digital Collections
- Lion shield to the left just like with our HathiTrust logo.

**Comment by ruthtillman** [comment]
domain test -- so far have identifier:

- digital.libraries.psu.edu
- libraries.psu.edu/collections 

and am asking Kevin C.

**Comment by ruthtillman** [comment]
Rather than using bullet points next to links in these boxes, let's use either https://fontawesome.com/icons/external-link-alt?style=solid or https://fontawesome.com/icons/link?style=solid (I am open to feedback on this)

**Comment by ruthtillman** [comment]
For the links, we need to refine all the way to these domains for actual digital collections because we have other library website links that might not be digital collections.

```
digital.libraries.psu.edu
libraries.psu.edu/collections
```

This one is doing exactly what it should: https://blackcat01qa.libraries.psu.edu/catalog/119281, as is this https://blackcat01qa.libraries.psu.edu/catalog/8400751 

This one is just to the finding aid and should not have the Digital Collections label: https://blackcat01qa.libraries.psu.edu/catalog/5535126 

This is a kind of tricky one because it's got both a digital collection and an archival finding aid link: https://blackcat01qa.libraries.psu.edu/catalog/2603978 we should use this one to see what happens when the domains are limited.

**Comment by nicktiberi** [comment]
@ruthtillman - for https://blackcat01qa.libraries.psu.edu/catalog/8400751, the links that are being indexed are for the domain `collection1.libraries.psu.edu`.

So should we add `collection<X>.libraries.psu.edu` to our list of links that are considered part of the digital collections?

Then our valid list would be:

```
digital.libraries.psu.edu
libraries.psu.edu/collections
collection<X>.libraries.psu.edu
```

**Comment by ruthtillman** [comment]
@nicktiberi yes, I think adding a wildcard there would be appropriate. thank you!
