### ISSUE TITLE
Document dev instructions for using Webpacker

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#68]
In GitLab by @bzk60 on Jul 17, 2018, 16:22

related to #64

* [x]  what goes in the various files for webpacker

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 16:36

assigned to @bzk60

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 18, 2018, 07:56

changed the description

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 18, 2018, 16:28

added ~938 label

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 18, 2018, 16:28

removed ~938 label

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 18, 2018, 16:29

see https://git.psu.edu/i-tech/psulib_blacklight/wikis/How-to-Use-webpacker (stubbed)

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 19, 2018, 7:38

also http://samuelmullen.com/articles/embracing-change-rails51-adopts-yarn-webpack-and-the-js-ecosystem/

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 20, 2018, 8:39

I reviewed and added some things to the doc.

**Comment by cdmo** [comment]
idk, i think the docs are pretty good. I'm going to close, but feel free to re-open if any part needs help
