### ISSUE TITLE
Update search tips and about page

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#691]
Updated search tips with new content which Karen Hackett has read through and corrected for use elsewhere on the libraries website. Focused on search tips vs. broader documentation. We may want to re-evaluate this once other docs are up.

Updated the about page with more up-to-date information about the status of the CAT and COVID-friendlier terms including removing references to browsing the shelf, adding an ETAS link, etc.

**Comment by banukutlu** [comment]
@ruthtillman is there anything else to be updated other than what it is in #692

**Comment by ruthtillman** [comment]
@banukutlu no, just those

**Comment by banukutlu** [comment]
@ruthtillman this is deployed to qa, pls check if OK then I will deploy to prod.

**Comment by ruthtillman** [comment]
@banukutlu changes to About now in https://github.com/psu-libraries/psulib_blacklight/tree/minor-about-changes - should I make new PR?

**Comment by banukutlu** [comment]
> @banukutlu changes to About now in https://github.com/psu-libraries/psulib_blacklight/tree/minor-about-changes - should I make new PR?

yes please new PR
