### ISSUE TITLE
Strip non-/ end punctuation from incoming links

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#697]
LibApps WYSIWYG editor and other systems like Word tend to incorporate punctuation that follows a link into that link itself. e.g. https://catalog.libraries.psu.edu/catalog/294532 would be come "https://catalog.libraries.psu.edu/catalog/294532." or "https://catalog.libraries.psu.edu/catalog/294532," or "https://catalog.libraries.psu.edu/catalog/294532;" Is it possible to compensate for this by stripping off any single punctuation mark at the end of the URLs? 

(note: librarian also putting in ticket w/LibApps)

**Comment by banukutlu** [comment]
@ruthtillman Are there other chars than `.` and `;` to be deleted?

**Comment by ruthtillman** [comment]
@banukutlu based on using these wysiwyg, I'd suggest the following characters:

```
.,;:?!"')]
```

**Comment by banukutlu** [comment]
@ruthtillman this is deployed to QA, ready for review.
