### ISSUE TITLE
As a user, I want to see if any available copies of an item exist on a search results page

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#7]
* [x] I want to know if a copy of the item is available.
* [x] If no copies of the item are available, I want to be able to request it from the search results.
* [x] If the item is available online, I want a link to get there

(because of data returned from Sirsi we may have to look at Stanford)

See also issue #8 for the full item results view.

Connected to #196

**Comment by ruthtillman** [comment]
Example of a bound-with volume, we need to be sure this displays ok: 1006921

**Comment by cdmo** [comment]
I emailed a colleague at NCSU just now, will keep you all posted

**Comment by ruthtillman** [comment]
More on overall

**Comment by banukutlu** [comment]
> Example of a bound-with volume, we need to be sure this displays ok: 1006921

@ruthtillman  there is no `ItemInfo` for `1006921`, what do we do for such bound-with records? 

```<TitleInfo>
<titleID>1006921</titleID>
<TitleAvailabilityInfo>
<totalCopiesAvailable>1</totalCopiesAvailable>
<libraryWithAvailableCopies>Pattee Library and Paterno Library Stacks (UP)</libraryWithAvailableCopies>
<totalResvCopiesAvailable>0</totalResvCopiesAvailable>
<locationOfFirstAvailableItem>DOC-US</locationOfFirstAvailableItem>
<holdable>true</holdable>
<bookable>false</bookable>
</TitleAvailabilityInfo>
<CallInfo>
<libraryID>UP-PAT</libraryID>
<classificationID>SUDOC</classificationID>
<callNumber>HE 20.6209:14/32</callNumber>
<numberOfCopies>0</numberOfCopies>
</CallInfo>
</TitleInfo>
```

**Comment by banukutlu** [comment]
> If no copies of the item are available, I want to be able to request it from the search results.

@ruthtillman do we have this documented anywhere in the wiki?

**Comment by ruthtillman** [comment]
Let's review this on 6/17. There are a couple ways we could do it. Things I can think of offhand include:

1) Put up "I Want It" button and make it link to Illiad instead.

2) Put up variation of "I Want It" which says something like "request via Interlibrary Loan"

2a) When the text says "This copy unavailable, submit request via Interlibrary Loan" - do we link that instead?

Here's some example records:

- https://blackcat01qa.libraries.psu.edu/catalog/1232415
- https://blackcat01qa.libraries.psu.edu/catalog/22080733

Similar question -- for something like https://blackcat01qa.libraries.psu.edu/catalog/1220805 , should we change the error to something like "Use 'I want It' to request from Annex" ? because it's more functional.

**Comment by banukutlu** [comment]
> > Example of a bound-with volume, we need to be sure this displays ok: 1006921
> 
> @ruthtillman there is no `ItemInfo` for `1006921`, what do we do for such bound-with records?
> 
> ```
> <TitleInfo>
>   <titleID>1006921</titleID>
>   <TitleAvailabilityInfo>
>     <totalCopiesAvailable>1</totalCopiesAvailable>
>     <libraryWithAvailableCopies>Pattee Library and Paterno Library Stacks (UP)</libraryWithAvailableCopies>
>     <totalResvCopiesAvailable>0</totalResvCopiesAvailable>
>     <locationOfFirstAvailableItem>DOC-US</locationOfFirstAvailableItem>
>     <holdable>true</holdable>
>     <bookable>false</bookable>
>   </TitleAvailabilityInfo>
>   <CallInfo>
>     <libraryID>UP-PAT</libraryID>
>     <classificationID>SUDOC</classificationID>
>     <callNumber>HE 20.6209:14/32</callNumber>
>     <numberOfCopies>0</numberOfCopies>
>   </CallInfo>
> </TitleInfo>
> ```

@ruthtillman there is this question as well, just making sure if you saw this or not?

**Comment by banukutlu** [comment]
> > Example of a bound-with volume, we need to be sure this displays ok: 1006921
> 
> @ruthtillman there is no `ItemInfo` for `1006921`, what do we do for such bound-with records?
> 
> ```
> <TitleInfo>
>   <titleID>1006921</titleID>
>   <TitleAvailabilityInfo>
>     <totalCopiesAvailable>1</totalCopiesAvailable>
>     <libraryWithAvailableCopies>Pattee Library and Paterno Library Stacks (UP)</libraryWithAvailableCopies>
>     <totalResvCopiesAvailable>0</totalResvCopiesAvailable>
>     <locationOfFirstAvailableItem>DOC-US</locationOfFirstAvailableItem>
>     <holdable>true</holdable>
>     <bookable>false</bookable>
>   </TitleAvailabilityInfo>
>   <CallInfo>
>     <libraryID>UP-PAT</libraryID>
>     <classificationID>SUDOC</classificationID>
>     <callNumber>HE 20.6209:14/32</callNumber>
>     <numberOfCopies>0</numberOfCopies>
>   </CallInfo>
> </TitleInfo>
> ```

@ruthtillman there is this question as well, just making sure if you saw this or not?

**Comment by ruthtillman** [comment]
@banukutlu yes I think we'll have to go over this and a few other cases today...

**Comment by ruthtillman** [comment]
`16007702`

Excerpt -- it appears that course reserve is being handled in two different ways. Can we walk through the logic of this in our meeting and how it should display?

```
 <CallInfo>
            <libraryID>ABINGTON</libraryID>
            <classificationID>LC</classificationID>
            <callNumber>BF724.5.B44 2015</callNumber>
            <numberOfCopies>1</numberOfCopies>
            <ItemInfo>
                <itemID>000078110250</itemID>
                <itemTypeID>BOOKFLOAT</itemTypeID>
                <currentLocationID>RESERVE-AB</currentLocationID>
                <homeLocationID>STACKS-AB</homeLocationID>
                <chargeable>true</chargeable>
                <reserveCollectionID>RESERVE-AB</reserveCollectionID>
                <reserveCirculationRule>RES-2HOUR</reserveCirculationRule>
                <fixedTimeBooking>false</fixedTimeBooking>
            </ItemInfo>
        </CallInfo>
        <CallInfo>
            <libraryID>SHENANGO</libraryID>
            <classificationID>LC</classificationID>
            <callNumber>BF724.5.B44 2015</callNumber>
            <numberOfCopies>1</numberOfCopies>
            <ItemInfo>
                <itemID>000078220454</itemID>
                <itemTypeID>BOOK</itemTypeID>
                <currentLocationID>RESERVE-SV</currentLocationID>
                <homeLocationID>RESERVE-SV</homeLocationID>
                <chargeable>true</chargeable>
                <fixedTimeBooking>false</fixedTimeBooking>
            </ItemInfo>
        </CallInfo>
```

**Comment by ruthtillman** [comment]
From review on 6/17 - updated ILL ticket #355 plus holdings/availability docs. We need to check logic to see if holdable = true but no copies are available, why I Want It isn't displaying. Example:

- https://blackcat01qa.libraries.psu.edu/catalog/22080733

**Comment by ruthtillman** [comment]
When an item is in the annex, the location should display as "Submit Request for Annexed Material" -- should we make this link to the same place as I Want It? Or should we change message? Thoughts?

**Comment by banukutlu** [comment]
> When an item is in the annex, the location should display as "Submit Request for Annexed Material" -- should we make this link to the same place as I Want It? Or should we change message? Thoughts?

@ruthtillman we will handle linking these with #377, right?
