### ISSUE TITLE
Find way to display "On Order" for ONLINE items which are on order.

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#704]
One clarification question we've had with the Catalog is what to do with items which are On-Order and also ONLINE. Nothing in the search result or item view page display indicates that they're not yet available. Because we don't display availability for ONLINE, it's not showing either the Availability or the link. This confuses users who think the item is broken somehow. It's a very reasonable concern.

**Logic:** If an item is ONLINE _and_ the ONLY currentLocationID on a record is ON-ORDER `<currentLocationID>ON-ORDER</currentLocationID>` (unique -- as there may be 5 of them but all ON-ORDER --shouldn't really be the case with ONLINE but let's unique it to be sure), then we display something indicating that it's On Order.

**Display options:** We could just display the normal Availability box and simply put a line in it which says "On Order." We could also display a box similar to the link boxes which says "Being acquired by the library"

**Sample record:**  https://catalog.libraries.psu.edu/catalog/33183518 (true on 2021-03-10)

Its webservices response:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><LookupTitleInfoResponse xmlns="http://schemas.sirsidynix.com/symws/standard"><TitleInfo><titleID>33183518</titleID><TitleAvailabilityInfo><totalCopiesAvailable>1</totalCopiesAvailable><libraryWithAvailableCopies>Online Resource</libraryWithAvailableCopies><totalResvCopiesAvailable>0</totalResvCopiesAvailable><locationOfFirstAvailableItem>ON-ORDER</locationOfFirstAvailableItem><holdable>true</holdable><bookable>false</bookable></TitleAvailabilityInfo><CallInfo><libraryID>ONLINE</libraryID><classificationID>AUTO</classificationID><callNumber>XX(33183518.1)</callNumber><numberOfCopies>1</numberOfCopies><ItemInfo><itemID>33183518-1001</itemID><itemTypeID>ONLINE</itemTypeID><currentLocationID>ON-ORDER</currentLocationID><homeLocationID>ON-ORDER</homeLocationID><chargeable>true</chargeable><fixedTimeBooking>false</fixedTimeBooking></ItemInfo></CallInfo><numberOfBoundwithLinks>0</numberOfBoundwithLinks></TitleInfo></LookupTitleInfoResponse>
```

**Comment by nicktiberi** [comment]
Talked with Ruth to make sure I was understanding the requirements properly, and confirmed that the "Being acquired by the library" message should show if:

- the item is online-only (i.e. there are no physical copies of this item) **AND**
- all of the `currentLocationId` fields for that item are `ON-ORDER`

**Comment by banukutlu** [comment]
@ruthtillman Is this case possible with bound-with items at all?

**Comment by ruthtillman** [comment]
good question. No it should never affect bound-withs

> @ruthtillman Is this case possible with bound-with items at all?

**Comment by ruthtillman** [comment]
Display looks good but is hanging in search results. Shared image on Teams. When a page contains one of these, the "Finding Items" never finishes displaying.
