### ISSUE TITLE
"I Want It" Button, add <marquee> effect

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#721]
In order to drive patron interaction with the "I Want It" button, please add the `<marquee>` effect.

I'm thinking that we should take the bold stance of having it move across the entire area as represented in:

![iwantitmarquee](https://user-images.githubusercontent.com/2687749/113717813-01032980-96ba-11eb-8212-fb8f051022ba.gif)

and

![iwantitmarquee_search](https://user-images.githubusercontent.com/2687749/113717838-06607400-96ba-11eb-96df-0a2ce42c2a93.gif)

but I could be ok with the more understated:

![iwantitmarquee_alt](https://user-images.githubusercontent.com/2687749/113717910-18421700-96ba-11eb-878f-725fdf64cab1.gif)

and

![iwantitmarquee_search_alt](https://user-images.githubusercontent.com/2687749/113717919-1bd59e00-96ba-11eb-9ab7-4fd2d11e9de0.gif)

@cdmo I think this is a fairly easy change, is this something you can do before you leave?

**Comment by cdmo** [comment]
this is some next level user engagement Ruth well done!
