### ISSUE TITLE
Use vault

### ISSUE THREAD

**Issue by awead** [psu-libraries/psulib_blacklight#722]
When setting up a new install, you need the `config/master.key` to decrypt credentials, even for local development. An alternative solution could be to move the management of credentials to Vault. This would, we think, remove the need for the local encrypted master key, and the various secrets and database passwords would be manged by vault for each server deployment.

@whereismyjetpack can weigh-in on the this, particularly regarding the feasibility of this.

**Comment by banukutlu** [comment]
thanks for adding this @awead 👍

**Comment by whereismyjetpack** [comment]
After #724 I think the only thing in there is `secret_key_base` and that can most certainly get injected via vault, or some other method. I'd be in favor of removing the credentials.enc file.
