### ISSUE TITLE
Constraints display issue

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#735]
Most of our search-related things worked as expected after the dependencies update, but we do have a few things which are not working as expected, all relating to facets (though some facets are working ok):

1. Behavior is correct but it's clearly doing something weird as you can see in the list of selected facets/search terms at the top of the page: https://blackcat01qa.libraries.psu.edu/?all_fields=&author=&f%5Bup_library_facet%5D%5B%5D=Pattee+Library+and+Paterno+Library+Stacks&f_inclusive%5Blibrary_facet%5D%5B%5D=Harrisburg&f_inclusive%5Blibrary_facet%5D%5B%5D=York&identifiers=&op=AND&publisher=&range%5Bpub_date_itsi%5D%5Bbegin%5D=2000&range%5Bpub_date_itsi%5D%5Bend%5D=&search_field=advanced&series=&sort=score+desc%2C+pub_date_itsi+desc%2C+title_sort+asc&subject=&title=  ... I would suggest doing a side-by-side comparison on this one to see exactly what the weirdness is.
2. Author/Creator and Subject search work fine, but when you click the link to get the controlled value facet-based search, it doesn't work: https://blackcat01qa.libraries.psu.edu/?f%5Ball_authors_facet%5D%5B%5D=Nurse%2C+Paul%2C+1949-  and https://blackcat01qa.libraries.psu.edu/?f[subject_facet][]=African+Americans%E2%80%94Politics+and+government%E2%80%9421st+century

related to #723

**Comment by banukutlu** [comment]
`#2` is handled by #746, it is deployed to QA. @ruthtillman

**Comment by ruthtillman** [comment]
Tested the different kinds and it looks good!
