### ISSUE TITLE
Use `PSUCATALOG` as clientID for webservice calls

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#767]

**Comment by nicktiberi** [comment]
@banukutlu - is this just changing `clientID` for our SIRSI/Symphony requests for availability?

I think there are just two of these:

- `https://cat.libraries.psu.edu:28443/symwsbc/rest/standard/lookupTitleInfo?clientID=BCCAT&includeAvailabilityInfo=true&includeItemInfo=true&includeBoundTogether=true&titleID=`
- `https://cat.libraries.psu.edu:28443/symwsbc/rest/standard/lookupTitleInfo?clientID=BCPAC&includeAvailabilityInfo=true&includeItemInfo=true`

So should we just change `BCCAT` AND `BCPAC` in both of these URLs to `PSUCATALOG`?

**Comment by banukutlu** [comment]
@mkutch would `PSUCATALOG` clientID work for both of the above urls?

**Comment by mkutch** [comment]
Yes, 

https://cat.libraries.psu.edu:28443/symwsbc/rest/standard/lookupTitleInfo?clientID=PSUCATALOG&titleID=2702238&includeAvailabilityInfo=true&includeItemInfo=true&includeCallNumberSummary=true&includeBoundTogether=true

https://cat.libraries.psu.edu:28443/symwsbc/rest/standard/lookupTitleInfo?clientID=PSUCATALOG&titleID=93&includeAvailabilityInfo=true&includeItemInfo=true
