### ISSUE TITLE
Post major ProQuest Outage info late 7/19 or early 7/20

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#771]
We will be experiencing a much bigger ProQuest outage on 7/24. There will be full details on Library alerts, so I'll indicate a place in the text to link to the Library alerts page to get more info. The Alerts post will go live early on 7/19 so we'll want ours to go up after:

```
Service Interruption: Due to a scheduled upgrade, many ProQuest resources will be unavailable on 7/24/21 from 10:00 am - 8:00 pm ET. See [library alerts] for a list of all resources affected.
```

**Comment by banukutlu** [comment]
@ruthtillman Is this the correct link to library alerts page  https://libraries.psu.edu/alerts/service-interruption-proquest-services-outage-72421-1000-am-800-pm-et to use for in the text.

**Comment by ruthtillman** [comment]
Yep! Thank you.

**Comment by banukutlu** [comment]
@ruthtillman announcement added to prod, could you pls review?

**Comment by ruthtillman** [comment]
looks good!
