### ISSUE TITLE
June 28 post alert for June 29 - 6am outage

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#772]
Post alert on morning of June 28, since we'll need to have the ProQuest outage banner on the site through Saturday the 26th:

```
Scheduled maintenance: Availability, I Want It, and My Account management will be unavailable on June 29, 2021 from approximately 6-6:30am EDT.
```

**Comment by banukutlu** [comment]
@ruthtillman Alert is up on BlackCat, should we add sth to MyAccount as well?

**Comment by ruthtillman** [comment]
@banukutlu good idea -- for language let's change the middle to ...`: I Want It, item renewals, and holds updates will be unavailable`...

**Comment by banukutlu** [comment]
> @banukutlu good idea -- for language let's change the middle to ...`: I Want It, item renewals, and holds updates will be unavailable`...

alert is up on MyAccount as well.
