### ISSUE TITLE
Remove HathiTrust box from search results

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#780]
Now that ETAS is gone, it's not a useful part of the search results, even if public domain. Let's just remove it for now and can consider adding in a public domain-only version if we want. There's some later enhancement work to do adding google books stuff so we might evaluate it all there.

**Comment by nicktiberi** [comment]
@ruthtillman - can you point me to a page where this box still appears? I'm not seeing it in prod anymore since ETAS was turned off, but maybe I'm not looking in the right place.

**Comment by ruthtillman** [comment]
https://catalog.libraries.psu.edu/?search_field=all_fields&q=conversations+with+god

**Comment by ruthtillman** [comment]
Looks great!
