### ISSUE TITLE
LC Call Number Browse Display

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#793]
Basic call number browse, with a simple interface similar to Princeton's [implementation](https://catalog.princeton.edu/browse/call_numbers?start=3800).

Note: This will _only_ cover LC-based call number classifications.

## TODO

- [ ] Sort and Search Call Numbers 
   - no search param: start from beginning with pagination
   - search for an existing call number: display the item with N before and after items
   - search for non existing/partial call number: display the non existing item in the context of related items
- [ ] Display Call Numbers
   - List of base call numbers with title(`title_display_ssm`) with link to the record, author, publication date, and image (same thumbnail used for item display) for the kind of bookshelf browse view
    
## Questions

1. Multiple solr documents(records) with same base call number

See https://github.com/psu-libraries/psulib_blacklight/wiki/Browse-Items-by-Library-of-Congress-Call-Number

**Comment by awead** [comment]
## Second Sprint TODO

* use shelf keys to browse forward and backward (and not the raw call numbers)

## Questions

How do we want to display multiple call numbers? Ex:

|Call Numnber | Title  | Location | Publication Info |
--- | --- | --- | ---- |
| AB 1234.5 2002 | Title 1 | Here | Info 1 |
|  | Title 2 | There | Info 2 |
|  | Title 3 | There | Info 3 |

### OR

|Call Numnber | Title  | Location | Publication Info |
--- | --- | --- | ---- |
| AB 1234.5 2002 | Title 1 | Here | Info 1 |
| AB 1234.5 2002 | Title 2 | There | Info 2 |
| AB 1234.5 2002 | Title 3 | There | Info 3 |

### OR 

?????

**Comment by banukutlu** [comment]
> ## Questions
> How do we want to display multiple call numbers? Ex:
> 
> ### OR
> Call Numnber	Title	Location	Publication Info
> AB 1234.5 2002	Title 1	Here	Info 1
> AB 1234.5 2002	Title 2	There	Info 2
> AB 1234.5 2002	Title 3	There	Info 3

Above is how we want to display multiple call numbers.

**Comment by ruthtillman** [comment]
Reviewed what we've got so far and it's going VERY well! I documented 2 issues, one in Blacklight display (#831) and one which captures small regex-related things https://github.com/psu-libraries/psulib_traject/issues/343. 

Overall I really enjoyed browsing through and seeing how well it works and actually getting to view all our books on quilting in one place (I also tested other sections of the call numbers)
