### ISSUE TITLE
As a user / as a librarian, I want to know what items are available for a record

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#8]
* [x] I want to see all items which exist.
* [x] If the item is available, I want to see its location and call number
* [x] If the item is available online, I want a link to get there
* [x] If the item is unavailable, I want to see that it is checked out / get an ILL link 
* [] If the item is Annexed, I want a link to request it. - will be handled by #377 

See also issue #7 for just the search results view

Connected to #196

**Comment by ruthtillman** [comment]
Example of a bound-with volume, we need to be sure this displays ok: 1006921

**Comment by ruthtillman** [comment]
More on overall aspects of availability display: https://github.com/psu-libraries/psulib_blacklight/wiki/Availability-Display

**Comment by banukutlu** [comment]
> If the item is unavailable, I want to see that it is checked out / get an ILL link

@ruthtillman we display a link for ILLEND, so should we display for all Checked Out as well?

**Comment by banukutlu** [comment]
> If the item is Annexed, I want a link to request it.

@ruthtillman could you pls update the wiki for this and add the link for it there?

**Comment by ruthtillman** [comment]
Updated wiki earlier today and in convo w/Banu updated the location statuses
