### ISSUE TITLE
Add call number dropdown option to search form

### ISSUE THREAD

**Issue by awead** [psu-libraries/psulib_blacklight#800]
Add an option to search for call numbers to the dropdown in the search form.

## WDLL

1. Add "browse call number" option after "subject"
2. executes a "nearby" browse search with the provided call number
3. It should work with or without spaces in the call number

**Comment by ruthtillman** [comment]
Not entirely sure if it should be in this issue or maybe it's impacted by #831 but when I do a search from this field for `NK9112` I get the URL:

https://catalog.qa.k8s.libraries.psu.edu/browse?nearby=NK9112

which, without the period in it, gives me:

```
NK9111.R4 1947 | Pennsylvania German coverlets / by Guy F. Reinert ; photographs by the author | Special Collections Library | Kutztown, Pa. : Kutztown pub. co., 1947.
None
NMB 1.7:229 (sumic) | Report to the President by Emergency Board No. 229  [microform] : submitted pursuant to Executive Order No. 13003, dated May  16, 1996 and section 10 of the Railway Labor Act, as amended :  investigation of disputes between certain railroads, represented by the  National Carriers' Conference Committee of the National Railway Labor  Conference including Consolidated Rail Corporation (including the  Clearfield Cluster), Burlington Northern Railroad Co. ... and their  employees represented by the Brotherhood of Maintenance of Way Employees | Dickinson Law (Carlisle) | Washington, D.C. : [National Mediation Board], [1996]
```

I then tried `NK 9112` to see whether a space worked but alas: https://catalog.qa.k8s.libraries.psu.edu/browse?nearby=NK%2B9112 didn't either.
