### ISSUE TITLE
Remove scan requests for engineering, EMS, PAMS

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#824]
We have been offering reserve scan requests for ENG, EMS, and PAMS library -- the libraries are set (link below). Until/unless we re-close, they're stopping offering these services. So we need to back this out but we **might** need to reinstate it if we close again. So the work should be the minimum amount to back it out while leaving the function available so we could turn it back on without too much effort. :-/ 

https://github.com/psu-libraries/psulib_blacklight/blob/63d0504d3469668d0005be6100891a4422082f00/app/javascript/availability/index.js#L525-L527

**Comment by nicktiberi** [comment]
@ruthtillman - right now the logic for this feature seems to add some params to the ILL link:

https://github.com/psu-libraries/psulib_blacklight/blob/63d0504d3469668d0005be6100891a4422082f00/app/javascript/availability/index.js#L438-L440

I don't fully understand this functionality, but does reverting this mean that basically just don't add these params to the ILL link, but still keep showing the link? It seems like that's how it was working before this PR: https://github.com/psu-libraries/psulib_blacklight/pull/639/files#diff-621ae34f880fd5de7db3707ac870f02ab22b12b4d01e21a2cd73a6563f1dab9cR502-R504

**Comment by ruthtillman** [comment]
I think that yes we would show the ILL link still and without the params you couldn't request a scan of it, just request the item via standard ILL? If we need to walk through it, my only critical calendar block today is 3pm and we could pick some time.

**Comment by nicktiberi** [comment]
That is kind of what I was thinking, so thanks for confirming! I should be able to get a PR for this up today.

**Comment by nicktiberi** [comment]
@ruthtillman - do you have a record we could use to test this? Thanks!

**Comment by ruthtillman** [comment]
So it seems like we've got:

28031766 & 2737027 & 28946051 & 32531217 & 23121953 & 371109 ... which don't appear to have any special link other than ILL. ... not sure what's up with that.
