### ISSUE TITLE
Add protection to /browse

### ISSUE THREAD

**Issue by awead** [psu-libraries/psulib_blacklight#829]
We want to release preliminary call number browse feature but in a limited way.

## WDLL

* limit `/browse` to specific users at Penn State via Apache configs
* add limitation to k8s config
* Allow all library staff users (whichever UMG that is...)

**Comment by whereismyjetpack** [comment]
the /browse endpoint is presently hidden behind users of the following umg:

```umg/psu.ul-up-staff-ft```
