### ISSUE TITLE
Implement search result testing

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#844]
I've created documentation on https://github.com/psu-libraries/psulib_blacklight/wiki/Search-Match-and-Weight-Testing for our expectations for search results.

Because our catalog will always be changing, this required some reflection and my initial recommendations are that we test results for:
1.  in the first X results, B field _contains_ Y (vs. catkeys or exact matches)
2. and we get fewer than Z results (vs. an exact number of results) where Z has different levels of padding from current results depending on whether it's a very specific query (small padding) or a very broad query (generous padding but not overkill)

Not urgent priority but something we can work on when we have the time.

**Comment by awead** [comment]
@ruthtillman One idea is to set aside a specific set of solr data that we use to test searching assertions. This would be separate from our usual fixtures that we use for typical application testing. This data set could also be used for testing browsing as well, as I'm already noticing some "fragility" when it comes to expecting certain subject headings on certain pages, etc.

OTOH, maybe we _want_ the tests to break...

**Comment by ruthtillman** [comment]
I think we've kind of handled this--anything new we'd do going forward.
