### ISSUE TITLE
Show basic ILL/Aeon links + different message if we can't retrieve data

### ISSUE THREAD

**Issue by nicktiberi** [psu-libraries/psulib_blacklight#848]
If we can't get the data for an ILL or Aeon link, instead of showing a link with a broken URL, hide the link and maybe show an error message instead.

Relevant code: 

https://github.com/psu-libraries/psulib_blacklight/blob/main/app/javascript/availability/components/ill_link.jsx#L22-L23

If `Object.keys(data).length === 0`, then we would be showing a broken link.

**Comment by banukutlu** [comment]
@ruthtillman Would you pls give us a default text or url as a fallback for the case Nick mentioned above ☝🏻 
This should not happen normally but we think we better cover this as well.
