### ISSUE TITLE
Document what should be in our BL catalog

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#86]
https://psu.app.box.com/notes/337786290129?

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Aug 22, 2018, 16:02

it'd be good to know what *is* in our catalog too, is there documentation somewhere?

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 22, 2018, 16:19

I do not know but maybe @rkt6 @mxk128 know if there are any docs?

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Aug 22, 2018, 16:21

What is the definition (or _type_) of "what"? :sweat_smile: (I'm not being facetious...are we talking about the kinds of records? other stuff?)

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 22, 2018, 16:22

yes to kinds of records. what can be other stuff?

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Aug 22, 2018, 16:22

So MARC records... then MARC records from different sources and types?

... then patron records? Is that the kind of thing we're talking about?

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 22, 2018, 16:24

along with that I think it would be helpful for me (and maybe others like me) to know the types such as books, e-resources etc.

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Aug 22, 2018, 16:25

Ahhh and that is a kind of thing I need to work out in Traject... what kinds of things are we going to have in the materials type.

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Aug 22, 2018, 16:29

there's a lot of stuff in the catalog. books, ebooks, theses, database titles, lending devices, etc. It'd be interesting if there were sort of an enumerated list of sources/workflows for the various buckets of things and what those buckets are... Banu mentioned something about how some stuff is even screen scraped on a regular basis for example. I just think it'd be educational if nothing else to know more about how the catalog works (and I'm talking about items/records, not account info or Workflows).

so it sounds like we need to start documenting all this stuff as we encounter it whilst working on traject indexing then... 

thinking out loud here.

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Aug 22, 2018, 16:31

Yes, I'm thinking documenting characteristics of these as we encounter them in traject will be part of the process. For example, there are records, primarily for e-things, which have autogenerated bits, e.g. the table of contents is machine-generated via screenscrape because... I cannot even tbh.

So identifying buckets as we index and logging here makes sense.

**Comment by ruthtillman** [comment]
https://github.com/psu-libraries/psulib_blacklight/wiki/Sources-of-Data-in-The-CAT
