### ISSUE TITLE
Browse Form Capitalization Issues

### ISSUE THREAD

**Issue by nicktiberi** [psu-libraries/psulib_blacklight#863]
Any search in the browse form is capitalized, but if a user types in an all-caps search, it lowercases letters after the first, causing unexpected results:

<img width="1145" alt="Screen Shot 2021-09-03 at 11 42 22 AM" src="https://user-images.githubusercontent.com/639920/132032462-02c4cc12-e50d-4b49-a83d-9237897de94a.png">

<img width="1155" alt="Screen Shot 2021-09-03 at 11 42 34 AM" src="https://user-images.githubusercontent.com/639920/132032475-662143dd-1017-496c-a721-0e5eb79f0c9a.png">

We should consider attempting to only capitalize the first letter, or maybe even better, make the prefix search case-insensitive if performance wouldn't suffer.

**Comment by awead** [comment]
We can't do a case-insensitive search because it's going off the actual facet values. We should probably just roll our own capitalization method instead of using Rails' `capitalize!`.
