### ISSUE TITLE
Combine AeonLink/IllLink into SpecialRequestLink

### ISSUE THREAD

**Issue by nicktiberi** [psu-libraries/psulib_blacklight#869]
Since the `<AeonLink />` and `<IllLink />` React components are basically the same except the URL and label, consider combining them into a single `<SpecialRequestLink />` component to avoid duplicating so much logic.

**Comment by ruthtillman** [comment]
Just tested these on QA:

✅ scan request boxes in Thesees still working correctly
✅ archival material request links work correctly!
✅ regular "Request via Interlibrary Loan" is working correctly, e.g. https://catalog.qa.k8s.libraries.psu.edu/catalog/510015 
❓ https://catalog.qa.k8s.libraries.psu.edu/catalog/140905 - Neither the Request Scan for Microform nor ILLiad links are populating any fields, just taking you to ILLiad. Same with https://catalog.qa.k8s.libraries.psu.edu/catalog/13855626 which isn't using complex logic. Also seeing that on prod, so not sure what's up with it, maybe we never had that code? by contrast, the scan link here https://catalog.qa.k8s.libraries.psu.edu/catalog/109237 is perfect.

**Comment by ruthtillman** [comment]
Per conversation, I've created https://github.com/psu-libraries/psulib_blacklight/issues/1123 to handle the OpenURL issue
