### ISSUE TITLE
Traject in kubernetes / job 

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/psulib_blacklight#871]
Currently we run traject as a deployment pod, and one issue it's causing is some resource contention issues. once the traject pod reaches a certain level of memory useage, the pod will sit in the cluster, and consume that memory

```
catalog-browsing                     catalog-browsing-traject-67464f4585-vcr5d                         5m           6525Mi
catalog-djb44                        catalog-djb44-traject-6d75c7d697-jmztj                            4m           6264Mi
catalog-genre-full-facet             catalog-genre-full-facet-traject-6cd67578d6-pszj5                 3051m        4073Mi
catalog-qa                           catalog-qa-traject-f876486bf-55jxg                                11m          5806Mi
catalog-search-weighting             catalog-search-weighting-traject-65d6dd777c-277d8                 3m           6156Mi
catalog-userlogin                    catalog-userlogin-traject-84b59db96c-p2fd4                        3m           4256Mi
```

My current thought is to refactor traject incremental into kubernetes `CronJob` objects. this will allow the hourlies to run as they are, but release resources when they are done. For full indexes, we'd have to create a 1 time job that does what the hourlies. we could also pin these jobs to a specific 'batch' node, as to not overwealm our cluster. if 10x jobs get fired off at once, kuberntes will handle queuing them up based off their requests. 

as for full indexes, my thought would be to have the catalog maybe create a `Job` object via a rake task, it could take the path, and version as an argument and create the jobspec. The struggle i'm having with this approach is what "interface" the developers use to trigger the full index, or the iterate and index workflow. if we do this all from rake tasks, we can crib off of some of the solr manager stuff we already have. As things get a bit more complex, rake doesn't seem like the best vessel for this? With this approach we could simplify the deployments a bit, (remove traject, and sidekiq)

I think coding this up in a MVP would be super easy, the one question I have is how to manage the traject version a deployment has/wants. we could pass it to the deployment as a parameter, that's overridable? right now we pass `traject.version` from the argoCD application, we could inject that into the deployment as an ENV VAR (kind of related to #868  -- but it would be a hint as to what version it should use. a developer should be able to override this to test other artifacts?

Sorry for the brain dump of text. I've been spending the past 2 weeks thinking about this and wanted to write it down.

**Comment by awead** [comment]
This sounds really cool. My initial thoughts are:

1. use a cli and not rake
2. could we make an API for this?

A while back you had suggested implementing something like what we have in Scholarsphere with the metadatata listener. In this case, the catalog would initiate indexing requests. Is this where we might be headed with this? I can see the catalog sending a request to an endpoint with the solr information, and potentially, which _version_ of traject it's expecting to use.

**Comment by whereismyjetpack** [comment]
I like the idea of an api. The dream still is that catalog would initiate these jobs, ideally eventually bubbling up to an /admin/traject route or something. 


I'm wondering if a `traject-job-creator` service would be too much..

**Comment by whereismyjetpack** [comment]
We've kind of changed gears on this one, and we've moved to using argo workflows for creating traject jobs. we're still testing this process, and will need to run prod through it's paces before closing
