### ISSUE TITLE
Setup Continuous Integration (Consider Travis and Circle)

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#88]
In GitLab by @ful105 on Aug 24, 2018, 13:50

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 20, 2018, 15:39

assigned to @cdm32

**Comment by cdmo** [comment]
Can't be turned on because you need to be an admin of the org that owns the repo

**Comment by cdmo** [comment]
Looking into CircleCI too

**Comment by cdmo** [comment]
Some examples:

* https://github.com/sul-dlss/SearchWorks/blob/master/.travis.yml
* https://github.com/tulibraries/tul_cob/blob/master/.travis.yml
* https://github.com/psu-libraries/cho/blob/master/.travis.yml
* https://github.com/pulibrary/orangelight/blob/master/.circleci/config.yml

**Comment by cdmo** [comment]
experimenting in a fork for now: 

https://travis-ci.com/cdmo/psulib_blacklight/jobs/149352123

**Comment by cdmo** [comment]
I know we have an issue for Coveralls, but we should consider https://codeclimate.com/ too

**Comment by cdmo** [comment]
Building successfully now as a starting point with Travis: https://travis-ci.com/psu-libraries/psulib_blacklight

**Comment by cdmo** [comment]
So I added `rubocop` and... it's not happy https://travis-ci.com/psu-libraries/psulib_blacklight/jobs/149508353

**Comment by cdmo** [comment]
Interesting! https://github.com/psu-libraries/niftany

**Comment by cdmo** [comment]
trying out niftany, it seems like a great way to bootstrap our ci with some good default lint settings for ruby, erb and scss

**Comment by cdmo** [comment]
at this point i think i'm going to put in a pr for @banukutlu and we'll go over IRL
