### ISSUE TITLE
sharding on dev solr instance

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#880]
You should be able to set shard count higher. You need to also set a flag to allow it

<img width="364" alt="Screen Shot 2021-09-10 at 5 03 47 PM" src="https://user-images.githubusercontent.com/3694886/132917524-1dec60b9-508b-45ce-a30c-293b1c1ef5ab.png">

numshads, and maxshardspernode will allow a multi-shard single node setup. 

the day we were doing testing we thought it was the node count that was tripping us up, and i think it's just if a collection has shards >1

_Originally posted by @whereismyjetpack in https://github.com/psu-libraries/psulib_blacklight/issues/879#issuecomment-917209226_

**Comment by whereismyjetpack** [comment]
This is entirely independent of how folks spin up their local instance, we are kind of fragmented in how we all like to work, so it might make sense to document in the setup somewhere, that we should have at least two

**Comment by ruthtillman** [comment]
Closed after 5/8/23 standup discussion
