### ISSUE TITLE
Code coverage service investigation

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#89]
In GitLab by @ful105 on Aug 24, 2018, 13:51

To setup with Coveralls, Requires #88 

Requires #33

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 20, 2018, 15:40

assigned to @cdm32

**Comment by cdmo** [comment]
Some institutions do not use a code coverage service at all. Princeton, for example, does and they use Coveralls. CHO, developed by our own colleagues, are using Code Climate. Codecov is another and there are many others.

https://www.slant.co/topics/2188/versus/~codecov_vs_coveralls_vs_code-climate

Codacy is another, https://www.codacy.com/

I don't think this is as much a necessity as running rspec during CI.

Also, ruby has something called Coverage as part of the standard library http://ruby-doc.org/stdlib-2.1.0/libdoc/coverage/rdoc/Coverage.html.

And here's yet another option: `simplecov` which is a gem that extends Coverage by outputting to pretty html (as far as I can tell with a quick look): https://github.com/colszowka/simplecov

I think we should remove the milestone on this issue and revisit this later.

**Comment by cdmo** [comment]
well, we're passing linters now, but coveralls still doesn't run. I'm guessing it'll only run on PRs.

**Comment by cdmo** [comment]
I just ran another test of this setup on branch 88 (see https://travis-ci.com/psu-libraries/psulib_blacklight/builds/88093537), and I think this point we should split this issue into two. This one can be about the investigation and can be closed. A second issue can be opened for setting up Coveralls. I would say we need to handle #96 and getting tests locally consistently working first. I'm proposing putting this in the backlog, though still MVP 0

**Comment by cdmo** [comment]
I just ran another test of this setup on branch 88 (see https://travis-ci.com/psu-libraries/psulib_blacklight/builds/88093537), and I think this point we should split this issue into two. This one can be about the investigation and can be closed. A second issue can be opened for setting up Coveralls. I would say we need to handle #96 and #69, getting tests locally consistently working first. I'm proposing putting this in the backlog, though still MVP 0

**Comment by banukutlu** [comment]
@cdmo yes I agree let's close this one and another issue for Coveralls.
