### ISSUE TITLE
Both Genre Facet and Genre Full Facet are appearing on search results page

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#893]
edited for clarity: Can we remove the genre_full_facet box from the sidebar? example https://catalog.libraries.psu.edu/catalog?commit=Search&op=AND&all_fields=&title=moby+dick&author=&subject=&identifiers=&series=&publisher=&range%5Bpub_date_itsi%5D%5Bbegin%5D=&range%5Bpub_date_itsi%5D%5Bend%5D=&sort=score+desc%2C+pub_date_itsi+desc%2C+title_sort+asc&search_field=advanced

**Comment by awead** [comment]
Note: suppressing the facet means it won't show up, but it's still in the Solr response for every search result.

**Comment by awead** [comment]
Suppressing the genre_full_facet will break the facet-to-record integration. Links like https://catalog.libraries.psu.edu/?f[genre_full_facet][]=Streaming+audio will not work as expected because the selected facet will not appear on the left. Can you label the other "Genre" facet something else, like "Topic"? It doesn't seem to line up with a linked field in the bib record.

**Comment by ruthtillman** [comment]
Sorry I wasn't clear, I meant just in the sidebar. We don't put quite a few facets in the sidebar, e.g. the all_authors_facet.

**Comment by awead** [comment]
Just so I understand, you want to break the current fact-to-record behavior. If I remove `genre_full_facet` from the facet config, links in the genre field from an item will still take the user to a search results page with all the items that have that corresponding genre, but _no_ facets will appear as select on the left.

**Comment by ruthtillman** [comment]
Correct.  genre_full_facet was never supposed to be in the sidebar. The other genre facet box takes care of that. Fixing an issue in record pages led to its inclusion in the sidebar. It should behave like all_authors_facet and other facets which are linked in the record, which take users to a search result page, but which are not in the facet sidebar.
