### ISSUE TITLE
Maintain list of pickup places

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#9]
In GitLab by @ful105 on Feb 21, 2018, 15:26

We will need to include and maintain (or pull regularly from somewhere) a list of all places where one can pick up a book / office delivery where appropriate.

Requires #53

Aha! Link: https://penn-state-university-libraries.aha.io/features/STPROJ-72

**Comment by cdmo** [comment]
Took the above comment and made a separate issue of it. https://github.com/psu-libraries/psulib_blacklight/issues/609
