### ISSUE TITLE
Manual tests

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#90]
In GitLab by @cdm32 on Aug 27, 2018, 13:46

what to click to test functionality

**Comment by cdmo** [comment]
We should look at what Blacklight's tests and look around at other institution's as well to bootstrap our own. We'll make our tests in human friendly language and then make some automated tests from these.

**Comment by banukutlu** [comment]
@ruthtillman @cdmo Let's schedule a meeting to start thinking about these tests.

**Comment by cdmo** [comment]
Just to help guide us: [Introduction to Writing Acceptance Tests with Cucumber](https://semaphoreci.com/community/tutorials/introduction-to-writing-acceptance-tests-with-cucumber)

```
Feature: <feature title>
As a <persona|role>
I want to <action>
So that <outcome>
```

**Comment by cdmo** [comment]
Couple ideas, things I wrote down during our checkin today:
```
Feature: Regional discovery
As a user in the capital region 
I want to find a book in Harrisburg or York
So that I can get a book today near me
```
```
Feature: Campus
As a user
I want to find a book at any University Park location
So that I can get a book today near me
```

These should be refined, but just thought I'd give it a whirl

**Comment by banukutlu** [comment]
https://github.com/tulibraries/tul_cob/blob/master/spec/features/record_page_fields_spec.rb

**Comment by banukutlu** [comment]
we will divide up and work on acceptance tests in each MVP so closing this issue to add one for each MVP.

**Comment by cdmo** [comment]
did you make a Box note?

**Comment by ruthtillman** [comment]
@cdmo just got back from getting tea: https://psu.app.box.com/notes/346675757749

**Comment by cdmo** [comment]
oh ha, thanks @ruthtillman, wasn't sure if Banu or you would, just a question 😅

**Comment by banukutlu** [comment]
We will cover these (https://github.com/psu-libraries/psulib_blacklight/wiki/Acceptance-Tests) with #233
