### ISSUE TITLE
Display Thesis Department With Search Links / Add to Advanced Search

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#914]
Requires: https://github.com/psu-libraries/psulib_traject/issues/368

## Display

Display thesis department **linked to controlled search for the field's value.** Label: Graduate Thesis Department.

Add field below "Additional Creators" in single item view.

## Advanced Search

Add to Advanced Search above Classification.  Label: Graduate Thesis Department.

see also https://github.com/psu-libraries/psulib_blacklight/wiki/Thesis-Department

**Comment by ruthtillman** [comment]
@ajkiessl can we update labels for display to **Graduate Program**? 

Basically, they may not be 1:1 matches to departments, but they do match graduate programs that exist or have existed.

**Comment by ajkiessl** [comment]
@ruthtillman Yup.  I'll see what I can do.
