### ISSUE TITLE
Update access levels to call number browse before Sunset

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#915]
We'll be removing access restrictions on browse author & subject and but keep restrictions on browse call number and everything will be added to the dropdown and unhide the nearby on shelf on item view (that is with availability section)

**Comment by whereismyjetpack** [comment]
For clarification:

`/browse` is opened. 
`/browse/call_numbers` is any logged in user

**Comment by banukutlu** [comment]
> For clarification:
> 
> `/browse` is opened. `/browse/call_numbers` is any logged in user

Thanks Dann!

**Comment by whereismyjetpack** [comment]
I'm happy to report that it took me 3 days to do 5 minutes of work. 

This should be done in prod.
