### ISSUE TITLE
Traditional and simplified Chinese searching not behaving interchangeably

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#950]
Just received a report that our traditional and simplified Chinese character results are not behaving interchangeably. This means that if materials are described with simplified Chinese characters but the person searches using traditional Chinese, they will not find the materials. And vice-versa.. The CAT handled this successfully as does WorldCat.

Examples provided were:

```
梵蒂冈图书馆所藏汉籍目录  / 梵蒂岡圖書館所藏漢籍目錄

林则徐全集 / 林則徐全集
```

I can work with our Chinese-language catalogers to get some more examples.

It's a high priority because it affects access to all our Chinese materials. Unfortunately, this was only just now reported because the reporter had not been using the Catalog until the CAT went away. 

CBeer shared in Blacklight Slack that they handle it this way:

https://github.com/sul-dlss/SearchWorks/blob/master/config/solr_configs/schema.xml#L481

and with https://github.com/sul-dlss/CJKFilterUtils 

JRochkind suggested we look for a Solr analyzer. We might also be able to work with Radu on it?

**Comment by ruthtillman** [comment]
Michael Gibney at Penn adds:

You want solr.ICUTransformFilterFactory: https://solr.apache.org/guide/8_11/filter-descriptions.html#icu-transform-filter.
The Stanford and Princeton examples are great; I'll add this (adapted/redacted) from Penn:

```
<fieldType name="search" class="solr.TextField" positionIncrementGap="100">
    <analyzer>
        <charFilter class="solr.ICUNormalizer2CharFilterFactory" name="nfkc"/> <!-- no case folding initially -->
        <charFilter class="solr.MappingCharFilterFactory" mapping="mapping-cjkMarcCompatibility.txt"/>
        <charFilter class="solr.ICUTransformCharFilterFactory" id="Traditional-Simplified"/>
        <charFilter class="solr.ICUTransformCharFilterFactory" id="Katakana-Hiragana" />
        <tokenizer class="solr.ICUTokenizerFactory" />
        <filter class="solr.ICUFoldingFilterFactory"/>
    </analyzer>
</fieldType>
```

But stock Solr does not have ICUTransform as a charFilter, only as a post-tokenization filter, so you'd need:

```
<fieldType name="search" class="solr.TextField" positionIncrementGap="100">
    <analyzer>
        <charFilter class="solr.ICUNormalizer2CharFilterFactory" name="nfkc"/> <!-- no case folding initially -->
        <charFilter class="solr.MappingCharFilterFactory" mapping="mapping-cjkMarcCompatibility.txt"/>
        <tokenizer class="solr.ICUTokenizerFactory" />
        <charFilter class="solr.ICUTransformFilterFactory" id="Traditional-Simplified"/>
        <charFilter class="solr.ICUTransformFilterFactory" id="Katakana-Hiragana" />
        <filter class="solr.ICUFoldingFilterFactory"/>
    </analyzer>
</fieldType>
```

**Comment by ruthtillman** [comment]
This is a 2013 analysis from Stanford which means that Solr has changed a good bit but might still have some relevant aspects http://discovery-grindstone.blogspot.com/2013/10/cjk-with-solr-for-libraries-part-1.html

**Comment by ajkiessl** [comment]
If you strip the last character off the search that isn't working like this: `宪政・中国 : 从现代化及文化转变看中国宪政发`, it works.  Which is frustrating and confusing since that last character `展` is the same in traditional and simplified.

**Comment by ruthtillman** [comment]
Wow, that is indeed confusing.
