### ISSUE TITLE
Call Number Browse updates to use custom sort plugin

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#961]
### WDLL

- Use [call number sort plugin](https://github.com/psu-libraries/call_number_sort) for call number browse, replace the current terms query.

Requires #960 and Related to psu-libraries/psulib_traject#391

**Comment by ruthtillman** [comment]
Note from gathering examples -- if I do a "nearby" with the "starting" call number of the bad URL, e.g. E29.N3.C38 2009 I sometimes get ok data but then when I try moving forward it breaks, so I'm not 100% sure where the bad record starts -- just that it's on that page. Using the 20 record defaults setting.

## Example One

broken: https://catalog.libraries.psu.edu/browse/call_numbers?classification=lc&starting=E..0029.N3.M36--2020

previous: https://catalog.libraries.psu.edu/browse/call_numbers?classification=lc&starting=E..0029.N3.C38--2009

**Comment by banukutlu** [comment]
Notes:

- `HD9525.A2E82353`, `HD9525.A2E82353` should be a exact match but it is not
-  With solr plugin, using stringdiff, how to handle when a record has multiple call numbers of the same type? eg. 'G5761.F7 1963.G7', 'JS4012.L7G7'
  <img width="1135" alt="Screen Shot 2022-04-06 at 5 23 23 PM" src="https://user-images.githubusercontent.com/6477867/162073636-cf2b3a5c-b264-46fc-a8f8-419beac5291f.png">

**Comment by banukutlu** [comment]
@ruthtillman preview branch is here https://catalog-stringdiff.dev.k8s.libraries.psu.edu/ ready to be tested for LC and DEWEY call number browse with the solr plugin.

**Comment by ruthtillman** [comment]
(incomplete) Notes from testing on custom sort:

- the "Ask at" call numbers should be AUTO, which is a field we will never be adding to Call Number Browse (vs. ASIS, which we will use for things like Fiche). Because there are only a few, I'm fixing manually.
- because it's paged, the call numbers next to each other can be really confusing, particularly if they're on the top or bottom of the results page. So we will want to either make it very clear that they're grouped (which may still be confusing) or remove them (which would be ideal) 
  - can we get the matching call # ?

**Comment by ruthtillman** [comment]
Thought on grouping display in the Call # Browse list: once we know we're displaying the right one, maybe we just display it and don't worry about a dropdown/showing the others. For now though it's definitely helpful to help me see what options are.

for this one, it's choosing the wrong call number to display: https://catalog-stringdiff.dev.k8s.libraries.psu.edu/browse/call_numbers?classification=lc&nearby=AP3.M33 (record https://catalog.qa.k8s.libraries.psu.edu/catalog/34855912)

Comparatively, G5761.F7 1963.G7 and JS4012.L7G7 are both working perfectly!

**Comment by ruthtillman** [comment]
More notes from looking at catkeys Maryam got me:

This page is kind of... wild in terms of which one's showing up: https://catalog-stringdiff.dev.k8s.libraries.psu.edu/browse/call_numbers?classification=lc&nearby=LB1103.S6

Seems to relate to:

- 998577
- 998641
- 998647

Not showing browse nearby on shelf?

- 1000477

Good display: 

- 1039
- 617669
- 1000006
- 1000180
- 100039
- 1000424
- 1001129
- 1001658
- 1001894
- 1002604

**Comment by ruthtillman** [comment]
This page is doing a loop from Ws into RC because of proximity, etc. https://catalog-stringdiff.dev.k8s.libraries.psu.edu/browse/call_numbers?classification=lc&length=50&starting=WY.00161.C357-N.2020

**Comment by ruthtillman** [comment]
For some reason, it's stopping here: https://catalog-stringdiff.dev.k8s.libraries.psu.edu/browse/call_numbers?classification=lc&starting=G..3824.S8.0002.P4.E67--1995C000400210001MPMCU0114 

but there's more pretty close, e.g. https://catalog-stringdiff.dev.k8s.libraries.psu.edu/browse/call_numbers?classification=lc&starting=G..3850 ...maybe because of the degree to which these break down with the colons (this isn't about where the colons are ordered, just a break in the paging through)

**Comment by ruthtillman** [comment]
Same thing on:

https://catalog-stringdiff.dev.k8s.libraries.psu.edu/browse/call_numbers?classification=lc&starting=ZA.3075.T43.2006

and

https://catalog-stringdiff.dev.k8s.libraries.psu.edu/browse/call_numbers?classification=lc&starting=ZA.3090

**Comment by banukutlu** [comment]
> (note -- the above seem to be working on QA... so maybe they're good? @banukutlu which should I be looking at?)

stringdiff is the one that has the plugin and the related changes, qa still has the previous implementation.
I will take a look into that issue you found out, good catch, thanks!

**Comment by banukutlu** [comment]
> For some reason, it's stopping here: https://catalog-stringdiff.dev.k8s.libraries.psu.edu/browse/call_numbers?classification=lc&starting=G..3824.S8.0002.P4.E67--1995C000400210001MPMCU0114
> 
> but there's more pretty close, e.g. https://catalog-stringdiff.dev.k8s.libraries.psu.edu/browse/call_numbers?classification=lc&starting=G..3850 ...maybe because of the degree to which these break down with the colons (this isn't about where the colons are ordered, just a break in the paging through)

@ruthtillman  I added a fix for the Next button, could you review when you get a chance?

**Comment by banukutlu** [comment]
> Same thing on:
> 
> https://catalog-stringdiff.dev.k8s.libraries.psu.edu/browse/call_numbers?classification=lc&starting=ZA.3075.T43.2006
> 
> and
> 
> https://catalog-stringdiff.dev.k8s.libraries.psu.edu/browse/call_numbers?classification=lc&starting=ZA.3090
> 
> ... then
> 
> https://catalog-stringdiff.dev.k8s.libraries.psu.edu/browse/call_numbers?classification=lc&starting=ZA.3250.U6.I58--1996
> 
> and if I do just https://catalog-stringdiff.dev.k8s.libraries.psu.edu/browse/call_numbers?classification=lc&starting=ZA.4075 (these are following off what they end with)
> 
> and if I end with the 4060 https://catalog-stringdiff.dev.k8s.libraries.psu.edu/browse/call_numbers?classification=lc&ending=ZA.4060.K586--2016 then it shows Next but not Previous.

@ruthtillman  Next is showing up for these now, I am looking into the Prev.

**Comment by ruthtillman** [comment]
Checking the Nexts now!

**Comment by banukutlu** [comment]
@ruthtillman I added a fix for prev button, it should be displaying for https://catalog-stringdiff.dev.k8s.libraries.psu.edu/browse/call_numbers?classification=lc&ending=ZA.4060.K586--2016 now. Could you also review it?

**Comment by ruthtillman** [comment]
Awesome -- and I navigated back and forth a bit, changed the page sizes, and then went all the way to the end of the alphabet (which is ZA 5100, so not that far away). I think it's looking good! I'll put aside a little time today (maybe at 11?) to just browse back and forth for a while and make sure nothing else is breaking.

**Comment by ruthtillman** [comment]
I did a little more last night while I was attending a virtual thing on my work computer and had the tabs ready to hand. Still going ok!
