### ISSUE TITLE
Call Number Browse error when searching for non-matching query and "You're looking for" is the first result

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#964]
When searching for a non-matching query that does not have any before items, it throws an error.

eg. search for https://catalog.libraries.psu.edu/browse/call_numbers?classification=lc&nearby=A

**Comment by ruthtillman** [comment]
Looks good. I also tested https://catalog.qa.k8s.libraries.psu.edu/browse/call_numbers?classification=lc&nearby=0 - which brought me to "A" which seems right!
